- xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/service/polling/PoloniexTradeServiceRaw.java
Typically an exchange only requires an `orderId` parameter to cancel an order.
The Poloniex cancelOrder API method requires 2 parameters: `orderId` and `currencyPair`
The current `xchange-poloniex` implementation will make an extra call to getOpenOrders() to find the CurrencyPair of an order; the order is then cancelled by providing `orderId` + `currencyPair` to the Poloniex API.
I've added an override to Poloniex's cancelOrder raw method to avoid the extra getOpenOrders() API call (if the caller already knows the CurrencyPair).
> [Poloniex] add CurrencyPair param to cancelOrder() raw method

- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/BitVcAdapters.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/BitVcExchange.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/Huobi.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/dto/account/HuobiAccountInfo.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/service/polling/BitVcMarketDataServiceRaw.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/service/polling/BitVcTradeService.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/service/polling/BitVcTradeServiceRaw.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/HuobiAccountService.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/HuobiAccountServiceRaw.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/HuobiBaseTradeService.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/HuobiTradeServiceRaw.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/TradeServiceRaw.java
BitVc is already using Huobi market data, with the new configurable param `use_huobi` you can switch to Huobi completely, for market data, account and trading. The APIs are extremely similar, that's why this merge makes sense, sharing the adapter methods almost completely.
> Support Huobi trading in BitVc adapter

- xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/dto/account/HuobiAccountInfo.java
- xchange-bitvc/src/main/java/com/xeiam/xchange/huobi/service/polling/HuobiAccountServiceRaw.java
HuobiAccountInfo is using "msg" instead of "message" for returning failure reasons.
> Adjust HuobiAccountInfo parsing of error messages

- xchange-btcchina/src/main/java/com/xeiam/xchange/btcchina/BTCChinaAdapters.java
- xchange-btcchina/src/main/java/com/xeiam/xchange/btcchina/dto/account/BTCChinaAccountInfo.java
Added support for http://btcchina.org/api-trade-documentation-en#trade_api_v2012. 
Loans will be deduced from the overall wallet, just like the other implementations that support loaning btc. If loan value has to be accessed
> BTCChina: Support loan wallet

- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/BitstampAuthenticated.java
- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/dto/account/BitstampRippleDepositAddress.java
- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountServiceRaw.java
Note that due to a bug in Bitstamp's implementation, ripple withdrawal only works if Google Authenticator authentication is disabled for the Bitstamp account.
> Bitstamp: Ripple stuff: deposit address, withdraw to ripple.

- xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/ANXAdapters.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEAdapters.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEExchange.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/dto/marketdata/BTCETradeServiceHelper.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCEAccountService.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCETradeService.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCETradeServiceRaw.java
- xchange-core/src/main/java/com/xeiam/xchange/currency/CurrencyPair.java
- xchange-core/src/main/java/com/xeiam/xchange/dto/account/AccountInfo.java
- xchange-core/src/main/java/com/xeiam/xchange/service/BaseExchangeService.java
- xchange-core/src/main/resources/xchange.properties
- xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyAdapters.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcAdapters.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcExchange.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/dto/marketdata/HitbtcTradeServiceHelper.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcAccountService.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcBasePollingService.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcTradeService.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcTradeServiceRaw.java
- xchange-hitbtc/src/test/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcAccountServiceTest.java
BTC-e API currently reports fee of .002 (.2%) for all listings, so I put one of the values in the AccountInfo.
Hitbtc fees vary between listings, so AccountInfo.getTradingFee() return value is configurable through xchange.properties.
All the fees are available through HitbtcTradingServiceHelper
ANX: make AccountInfo.getTradingFee() return fraction instead of percent.
> Add trading fee to AccountInfo @ BTC-e and Hitbtc

- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinTradeService.java
Cancellation of open LTC orders was not possible when no BTC orders open, due to wrongly caught exception.
> OkCoin: Cancellation of LTC when no BTC orders open

- xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/service/polling/ANXAccountServiceRaw.java
- xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/service/polling/ANXBasePollingService.java
- xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/service/polling/ANXMarketDataServiceRaw.java
- xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/service/polling/ANXTradeServiceRaw.java
- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCEBasePollingService.java
- xchange-core/src/main/java/com/xeiam/xchange/FrequencyLimitExceededException.java
- xchange-core/src/main/java/com/xeiam/xchange/FundsExceededException.java
- xchange-core/src/main/java/com/xeiam/xchange/NonceException.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcAccountServiceRaw.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcBasePollingService.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcMarketDataServiceRaw.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcTradeService.java
- xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcTradeServiceRaw.java
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenBasePollingService.java
and insufficient funds.
I'd like to push issue #684 forward.
I can handle programatically nonce error and throttling. @mmazi's example with insufficient funds is a good one too.
Until all the exchanges are modified, some of the exchanges will throw exceptions that don't extend ExchangeException - we break the generic interface.
I guess we will have to live with `catch(ExchangeException | IllegalArgumentException e)` for the time being.
`FrequencyLimitExceededException extends IllegalStateException` because It represents a transient state of the exchange - internal counter that at some point exceeds some threshold.
`FundsExceededException extends IllegalArgumentException` - it could bee seen as illegal argument (requested order exceeds the funds) or illegal state (funds are insufficient to …
> Introduce exception types for nonce error, throttling

- pom.xml
I't useful and unlike javadoc, doesn't influence build time
> [pom] Bring back source plugin to the default build

- xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEExchange.java
- xchange-btce/src/test/java/com/xeiam/xchange/btce/v3/BTCEExchangeTest.java
- xchange-core/src/main/java/com/xeiam/xchange/utils/nonce/TimestampIncrementingNonceFactory.java
I'm hoping to end the BTC-e nonce troubles once and for all. This is a v3 / SynchronizedValueFactory re-implementation of the nonce factory I implemented and described in #756. (Please see that issue or/and the test included in this PR if you're interested why this PR is necessary. Tl;dr: it supports several exchange instances operating at the same time.)
I've reviewed the many previous BTCE nonce issues and pull requests and I believe this should resolve all of them. (It doesn't resolve my GAE issue 100%, but it's good enough.)
This PR includes a test that fails with the `AtomicLongIncrementalTime2013NonceFactory` that is currently used for BTC-e, and passes with the new `TimestampIncrementingNonceFactory`.
A few notes:
* I think the new `TimestampIncrementingNonceFactory` is the best …
> Added a more robust integer nonce factory. Use it for BTC-e.

- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinExchange.java
Refactor of exchange spec. params broke the `Use_Intl` switching of OkCoin. This should fix it.
Addresses https://github.com/timmolter/XChange/issues/860#issuecomment-75395198
> Apply exch. spec. params before instantiating MDS due to refactor

- xchange-btctrade/src/main/java/com/xeiam/xchange/btctrade/BTCTradeAdapters.java
The initial capacity should be 5:
1. BTC
2. LTC
3. DOGE
4. YBC
5. CNY.
> Fix ArrayList initial capacity in BTCTrade wallets adpating.

- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/HuobiAdapters.java
Huobi changed the sort order of the ask side of their orderbook at `http://market.huobi.com/staticmarket/depth_btc_json.js`
Sorting is not necessary anymore.
> Huobi: remove sorting of ask side of orderbook

- .gitignore
- xchange-btce/src/test/java/com/xeiam/xchange/btce/v3/ExchangeConfiguration.java
- xchange-btce/src/test/java/com/xeiam/xchange/btce/v3/ExchangeUtils.java
- xchange-btce/src/test/java/com/xeiam/xchange/btce/v3/service/polling/AccountInfoFetchIntegration.java
- xchange-btce/src/test/resources/v3/sampleExchangeConfiguration.json
This adds an integration test for the BTCE getInfo call as well as an ExchangeConfiguration which can be loaded from a json file in the resources folder. The test passes if no such configuration is present.
I am providing this in preparation for work providing the TransHistory API call. Trying to provide smaller chunks of work to pull.
> Account getInfo integration test.

- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinFuturesMarketDataService.java
To instantiate a futures market data service on Okcoin.com you will have to pass an instance of `FuturesContract` instead of a string value. I leave this in for backwards compatibility, and added the exchange specific param `Futures_Contract_String` to instantiate the enum via a string (e.g. via config file) more easily.
> OkCoin: Instantiate FuturesContract via valueOf

- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinFuturesTradeService.java
Added methods to `OkCoinFuturesTradeService` which allows to liquidate open positions using same `MarketOrder` and `LimitOrder` semantics as the "place" (a.k.a "open long/open short") methods.
> OkCoin: Liquidate open positions using market order or limit order

- xchange-examples/src/main/java/com/xeiam/xchange/examples/huobi/marketdata/polling/HuobiDepthDemo.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/BitVcFutures.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/BitVcFuturesAdapter.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/FuturesContract.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/HuobiExchange.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/dto/marketdata/futures/BitVcExchangeRate.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/dto/marketdata/futures/BitVcFuturesDepth.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/dto/marketdata/futures/BitVcFuturesTicker.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/dto/marketdata/futures/BitVcFuturesTrade.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/service/polling/BitVcFuturesMarketDataService.java
- xchange-huobi/src/main/java/com/xeiam/xchange/huobi/service/polling/BitVcFuturesMarketDataServiceRaw.java
*No functional changes for existing code in the Huobi adapter*
Support for BitVc futures market data (trading functionality coming soon). This futures data also acts as Huobi's futures market. To see how to use it, check the `HuobiDepthDemo`.
> Huobi: Support for futures market data

- xchange-core/src/main/java/com/xeiam/xchange/dto/Order.java
- xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/Trade.java
- xchange-core/src/main/java/com/xeiam/xchange/dto/trade/UserTrade.java
- xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/dto/account/CryptsyTransfers.java
- xchange-cryptsy/src/test/java/com/xeiam/xchange/cryptsy/dto/account/CryptsyAccountJsonTest.java
- xchange-cryptsy/src/test/resources/account/Sample_MyTransfers_Data.json
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenAdapters.java
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/trade/KrakenOrderFlags.java
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/trade/KrakenStandardOrder.java
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenBasePollingService.java
- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenTradeServiceRaw.java
- xchange-kraken/src/test/java/com/xeiam/xchange/kraken/KrakenAdaptersTest.java
- xchange-kraken/src/test/java/com/xeiam/xchange/kraken/service/polling/KrakenBasePollingServiceTest.java
Added an extra field to the Order and Trade classes to hold additional data, the rationale behind this is:
* on order entry some exchanges will support flags to tag the order with additional information, this does not currently seem possible to do in a generic manner using the existing implementation. 
* on trade message from the exchange additional information is sometimes provided above and beyond the standard trade facts. If this information is of interest it can be stored in the additional data map. In the example below the calculated quantity (1.130102248) does not match the cost returned in the message (1.13010). 
```
Order Entry
pair=XXBTXLTC&type=sell&ordertype=limit&price=162.60003&volume=0.010147599&position=0&oflags=fcib
Trade …
```
> Order class flags variable and Trade additional data map (with Kraken implementation)

- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/CoinbaseExDigest.java
There's still quite frequent "invalid signature" 400 HTTP errors, not quite sure why. This reduces the failures a bit but does not fully solve it.
> Coinbase digest utf-8 fix

- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseEx.java
- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseExAdapters.java
- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/marketdata/CoinbaseExTrade.java
- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExMarketDataService.java
- xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExMarketDataServiceRaw.java
Implement missing trades extraction. Currently by default just polls the last 100 trades. Coinbase supports elaborate pagination, can be implemented another time.
> CoinbaseEx: polling of trades

- xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyExchange.java
Override getPollingMarketDataService so that it returns the public
service if apiKey is null.
> [Cryptsy] Public market data service fix

- xchange-clevercoin/src/main/java/com/xeiam/xchange/clevercoin/CleverCoinAuthenticated.java
Change the request method and the url of the cancel limited order
endpoint. The old one will be deprecated soon.
> Update cancel limited order endpoint

- xchange-mexbt/src/main/java/com/xeiam/xchange/mexbt/MeXBTExchange.java
> [MeXBT] Change nonce factory to epoch time in milliseconds, to align with MeXBT ruby client.

- xchange-core/src/main/java/com/xeiam/xchange/dto/Order.java
- xchange-core/src/main/java/com/xeiam/xchange/dto/trade/LimitOrder.java
As discussed with @rafalkrupinski [here](https://github.com/timmolter/XChange/commit/3f29273f80a64a2447934b25a3eaf45829c6e7f8#commitcomment-12137423) the LimitOrder.Builder from(...) method needs improvement. Also as agreed by @timmolter the parent Order class should be abstract, orders should be a MarketOrder or LimitOrder.
> [core] made Order abstract and improved LimitOrder.Builder

- xchange-bter/src/main/java/com/xeiam/xchange/bter/service/polling/BTERPollingTradeServiceRaw.java
- xchange-examples/src/main/java/com/xeiam/xchange/examples/bter/trade/BTERTradeDemo.java
Please see issue: https://github.com/timmolter/XChange/issues/1001
This updates placeBTERLimitOrder method to return exchange reference (provided by exchange) instead of boolean.  This is in line with other feeds.  Tested and verified working.
>  BTER order API returns 'true' instead of order id.

- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/service/polling/BittrexTradeService.java
- xchange-btctrade/src/main/java/com/xeiam/xchange/btctrade/service/polling/BTCTradeTradeService.java
- xchange-bter/src/main/java/com/xeiam/xchange/bter/service/polling/BTERPollingTradeService.java
- xchange-clevercoin/src/main/java/com/xeiam/xchange/clevercoin/service/polling/CleverCoinTradeService.java
- xchange-coinmate/src/main/java/com/xeiam/xchange/coinmate/CoinmateAdapters.java
- xchange-coinmate/src/main/java/com/xeiam/xchange/coinmate/service/polling/CoinmateTradeService.java
- xchange-core/src/main/java/com/xeiam/xchange/service/polling/trade/PollingTradeService.java
- xchange-core/src/main/java/com/xeiam/xchange/service/polling/trade/params/TradeHistoryParamsZero.java
- xchange-core/src/main/java/com/xeiam/xchange/utils/DateUtils.java
- xchange-independentreserve/src/main/java/com/xeiam/xchange/independentreserve/service/polling/IndependentReserveTradeService.java
- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinFuturesTradeService.java
All exchanges with implemented PollingTradeService.getTradeHistory(Object...) now have TradeHistoryParams version as well.
PollingTradeService.getTradeHistory(Object...) is now market as @Deprecated and may be removed in a future release (see #933)
> Migrate PollingTradeService.getTradeHistory(Object...) to TradeHistoryParams

- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/dto/RippleException.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/service/polling/RippleTradeServiceRaw.java
For Ripple added trade history error handling to protect against any future occurrences similar to https://github.com/ripple/ripple-rest/issues/384 when failure or Ripple REST to parse (what turned out to be) a non-trade transaction was causing total failure of the trade history query. 
Fixed bug so that when trade history count limits are set to zero the check is disabled.
> [ripple] added trade history error handling and fixed trade history count limits bug

- xchange-core/src/main/java/com/xeiam/xchange/service/streaming/ReconnectService.java
- xchange-core/src/main/java/com/xeiam/xchange/service/streaming/StreamingExchangeService.java
- xchange-core/src/main/java/com/xeiam/xchange/service/streaming/WebSocketEventProducer.java
- xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/MonitorTask.java
Hi,
it would seem that com.xeiam.xchange.okcoin.service.streaming.WebSocketBase should automatically handle reconnects of the websockets.
How is it suggested to  handel certain exceptions such as hostnotfound in the event the connectivity is lost, or if the channel is not alive, nor do those exceptions seem to be bubbled up as call backs to the calling thread, so the main application cannot handel them by resubmitting another thread until connectivity is restored.
Quick simulation is to add a static route to okcoin.com once the streaming service has processed a set of events.
route -n add 58.96.162.1/24 192.168.0.20
route -n delete 58.96.162.0
> okcoin streaming not reconnecting

- xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitTradeService.java
- xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitTradeServiceRaw.java
Rather than hardcoding the XBTUSD currency, available currencies are fetched from the exchange and then open orders are requested for each of the valid CurrencyPairs.
Fixes #1018
> ItBit: Use all exchange currencies for PollingTradeService.getOpenOrders()

- xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAuthenticated.java
Remove @Consumes from ItBit GET requests as they are not expected to have body content. Corrects warnings from rescu.
> Remove @Consumes from GET requests

- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/RippleAdapters.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/RippleExchange.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/RipplePublic.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/dto/RippleAmount.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/dto/trade/IRippleTradeTransaction.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/dto/trade/RippleOrderTransaction.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/dto/trade/RipplePaymentTransaction.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/service/polling/RippleTradeService.java
- xchange-ripple/src/main/java/com/xeiam/xchange/ripple/service/polling/RippleTradeServiceRaw.java
- xchange-ripple/src/test/java/com/xeiam/xchange/ripple/RippleAdaptersTest.java
- xchange-ripple/src/test/java/com/xeiam/xchange/ripple/dto/account/trade/RippleNotificationTest.java
- xchange-ripple/src/test/java/com/xeiam/xchange/ripple/dto/account/trade/RippleOrderTest.java
- xchange-ripple/src/test/java/com/xeiam/xchange/ripple/dto/account/trade/RipplePaymentTest.java
- xchange-ripple/src/test/resources/trade/example-notifications.json
- xchange-ripple/src/test/resources/trade/example-payment-passthrough.json
- xchange-ripple/src/test/resources/trade/example-trade-buyBTC-sellBTC.json
- xchange-ripple/src/test/resources/trade/example-trade-buyXRP-sellBTC.json
- xchange-ripple/src/test/resources/trade/example-trade-sellXRP-buyBTC.json
* added support for trades presented as passthrough payments
* fixed bug causing incorrect buy/sell direction to be reported if a DTO was adapted more than once
* order ID on trades now matches that on original order
* request wait for validation of successful order entry/cancel moved to an option
> [ripple] trade history improvements and fixes

- xchange-btcmarkets/src/main/java/com/xeiam/xchange/btcmarkets/service/polling/BTCMarketsTradeService.java
The guys at BTCMarkets fixed the server to not require a price that is close to the current market price to be submitted with a market order, so we can just always submit 0 now.
> BTCMarkets: fix market orders

- xchange-core/src/main/java/com/xeiam/xchange/service/polling/trade/params/DefaultTradeHistoryParamPagingSorted.java
- xchange-loyalbit/src/main/java/com/xeiam/xchange/loyalbit/service/polling/LoyalbitTradeService.java
The most recent trades are now retrieved first when using pagination/limit.
> Loyalbit: set default trade history sort order to descending

- xchange-examples/src/main/java/com/xeiam/xchange/examples/quoine/QuoineExamplesUtils.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineAuthenticated.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineExchange.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/QuoineSignatureDigest.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineAccountServiceRaw.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineBasePollingService.java
- xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineTradeServiceRaw.java
Quoine exchange provides 2 modes of authentication: token-based, which is the one currently supported by XChange, and secret-based, which is not. Token-based is deprecated and will be removed in a future release (see [https://developers.quoine.com/#1.1-token-based-(deprecated)](https://developers.quoine.com/#1.1-token-based-(deprecated)).
This pull request implements secret-based authentication for xchange-quoine. Token-based authentication is no longer possible after this pull request is merged, and thus it should be considered as not backwards compatible.
> Change mode of authentication for Quoine

- xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenAdapters.java
- xchange-kraken/src/test/java/com/xeiam/xchange/kraken/KrakenAdaptersTest.java
The vwap value will be the 24h weighted average provided by the kraken API:
https://www.kraken.com/help/api#get-ticker-info
> Adds missing value vwap for Ticker from Kraken

- xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/dto/trade/PoloniexTradeResponse.java
Poloniex orderNumber is a Long not an Integer. Since saturday ( 11/21/2015 ),
ETH Market order number overflow integer value.
> Poloniex: switch orderNumber to Long

- xchange-examples/pom.xml
- xchange-examples/src/test/java/com/xeiam/xchange/examples/AllIntegration.java
I crammed 240 tests into one class so I could use one parameterized test fixture.
Basically it reveals all the services which require more than one argument to their methods.  Some which need updates.  BTCCentral needs a custom trustmanager written to allow its expired certificate to pass (without blindly trusting all certificates as its current integration test does).
I think something like this test class is important to have for major refactoring changes, to verify there are no regressions.  I also think a worthwhile ideal is to find ways to fix up things for the abnormal services so all services may be accessed by unified interfaces, such that one day all these tests pass.
fixes #1120
> [examples] AllIntegration tests polling marketdata for each exchange.

- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/BitstampAdapters.java
- xchange-core/src/main/java/com/xeiam/xchange/dto/account/Balance.java
Two commits, two changes:
- Bistamp balance withdrawing amount
- Log a warning instead of an exception when balances don't add up. I don't think the situation when balances don't add up is critical (individual balances are still useful). Also, I suspect many exchange implementations currently have issues in the implementation here (like Bitstamp) so I suggest we fail more gracefully to allow us some time to fix these.
The code was tested with Bitstamp.
@baffo32, please review. Thanks!
> Bitstamp balance withdrawing

- xchange-core/src/main/java/com/xeiam/xchange/dto/account/Balance.java
Don't give an false log warning if the calculated balance is equal to the expected one but has a different number of decimals.
> Don't give false exception on balance

- xchange-cexio/src/main/resources/cexio.json
Many markets are removed on cexio. 
Using the old markets gives an exception in getting open orders.
> Removed removed markets in json file

- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/BittrexAdapters.java
- xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/dto/marketdata/PoloniexCurrencyInfo.java
- xchange-poloniex/src/test/java/com/xeiam/xchange/poloniex/dto/marketdata/PoloniexMarketDataTest.java
- xchange-poloniex/src/test/resources/marketdata/currency-info.json
* There was a [Poloniex upgrade yesterday](https://twitter.com/Poloniex/status/678258485704990720) - I guess that is when the maxDailyWithdrawal field was deprecated, field is still present but is a string with the text "DEPRECATED". 
* Bittrex returns commission information in its trade history response, but this was not being copied to the UserTrade object.
> [poloniex] removed deprecated maxDailyWithdrawal from currency info, [bittrex] added fee information to trade history

- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampMarketDataServiceRaw.java
Added `DAY` option in enum which is used in `getBitstampTransactions`.
*Bitstamp documentation:*
Transactions GET https://www.bitstamp.net/api/transactions/
Params: time - time frame for transaction export ("minute" - 1 minute, "hour" - 1 hour, "day" - 1 day).
> Added 'DAY' option to BitstampTime enum

- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/BittrexAdapters.java
- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/BittrexUtils.java
- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/dto/trade/BittrexLimitOrder.java
- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/dto/trade/BittrexOpenOrder.java
- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/dto/trade/BittrexUserTrade.java
- xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/service/polling/BittrexAccountService.java
Related to issue #1153. 
* Open order query has been changed to return BittrexLimitOrder objects allowing access to quantity remaining and price per unit. 
* Trade query altered so that trade time is order close time rather than order creation time. 
* Fix timestamp parsing method to not generate parsing exceptions for times without millisecond component.
> [bittrex] open order and trade query changes

- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/BitstampAuthenticated.java
- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountService.java
- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountServiceRaw.java
- xchange-examples/src/main/java/com/xeiam/xchange/examples/bitstamp/account/BitstampAccountDemo.java
Bitstamp Bitcoin addresses start with 1 and Ripple with r. So I think it's a pretty safe implementation.
> Withdraw to Ripple for Bitstamp if address starts with 'r'

- xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountService.java
According to [Bitstamp docs](https://www.bitstamp.net/api/) Bitcoin withdrawal returns an integer ID but ripple withdrawal returns `true`. So in this case of ripple withdrawal it's null. Check the following line https://github.com/nakedpony/XChange/blob/a1f3a29d28f1a360e154a52972fc27c9ffcd6386/xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountServiceRaw.java#L53
> [bitstamp] Resolve Nullpointer for Ripple withdrawal

- xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java
Previous implementation could format amount with the `,` as a decimal separator depending on the locale of the machine. Now it's `.` as itbit accepts.
Also made `DateFormat` and `DecimalFormat` non static because they are not thread safe. Don't think that it would impact performance anyhow.
> [itbit] fix format for the requests

- xchange-gatecoin/src/main/java/com/xeiam/xchange/gatecoin/service/polling/GatecoinTradeService.java
Order type for open orders was reported wrong. 
Xchange order type is order side for gatecoin (ask or bid)
Gatecoin order type is limit order or market order.
> Open orders on gatecoin contains wrong order type

- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/CryptoFacilitiesAdapters.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/account/CryptoFacilitiesAccount.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/account/CryptoFacilitiesAccountInfo.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/account/CryptoFacilitiesBalance.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFill.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFills.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesTrade.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesTrades.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesAccountService.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesAccountServiceRaw.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeService.java
- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeServiceRaw.java
- xchange-cryptofacilities/src/test/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesAccountJSONTest.java
- xchange-cryptofacilities/src/test/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFillsJSONTest.java
- xchange-cryptofacilities/src/test/resources/marketdata/example-account-data.json
- xchange-cryptofacilities/src/test/resources/marketdata/example-fills-data.json
Addition of account and fills functionality from version 2 of the CF
api to the raw interface and hook up to the generic interface. #1204 
- getTradeHistory now returns associated order id's with trades(fills) using the new /v2/fills endpoint replacing the /trades endpoint.
- getAccountInfo now returns available BTC = total deposited BTC - BTC held for margin using the new /v2/account endpoint replacing the /balance endpoint.
/trades and /balance endpoints are deprecated but still available from the raw interface.
> [CryptoFacilities] add v2 api account + fills endpoints

- xchange-anx/src/main/resources/anxpro.json
Alison replied:
Hi,
Recently we have upgrade our website, the tradable Amount increased to 750.
Would you please try again?
Alison
Customer Support Team
ANX
> Minimal order size on anx of XRP has been changed

- xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFill.java
#1204 : #1208 bug fix
Adaption of raw CF fill time zone to correctly include time zone. E.g. BST
> CryptoFacilities v2 api : fills TZ bug fix

- xchange-bleutrade/src/main/java/com/xeiam/xchange/bleutrade/BleutradeAdapters.java
- xchange-bleutrade/src/test/java/com/xeiam/xchange/bleutrade/BleutradeExchangeTest.java
- xchange-bleutrade/src/test/java/com/xeiam/xchange/bleutrade/BleutradeTestData.java
Tested on a real trade. A trade has 0.25 % fee. (old assumption that fee was calculated for base and counter coin was incorrect)
> Corrected meta data reported fee on bleutrade.

- xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/BitfinexAuthenticated.java
- xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/service/polling/BitfinexTradeServiceRaw.java
I am not sure why this was removed. It was perhaps a little quirky to get working initially because the list of orders for new order multi was < Order > and not <? extends Order>, forcing a cast, but I have corrected that. There are other diffs for formatting that can be reverted if desired. I would like to know why the code was commented out if anyone knows.
> Add back new order multi and cancel order multi

- xchange-cexio/src/main/resources/cexio.json
Cexio now also supports eth:
Welcome the launch of Ethers on CEX.IO!
We are glad to announce launching Ether trading on CEX.IO.
From now on, you can trade ETH/BTC and ETH/USD, as well as simply buy Ethers with your Visa or MasterCard, or via bank transfer.
We at CEX.IO are glad to support outstanding innovations, such as Ethereum, and welcome everyone to buy, sell, and trade Ethers.
> Cexio now also supports eth

- xchange-btce/src/main/java/org/knowm/xchange/btce/v3/BTCEAdapters.java
- xchange-btce/src/main/java/org/knowm/xchange/btce/v3/service/polling/BTCETradeService.java
Btce added eth and DASH. But dash is signaled as dsh which is a different coin. 
Translate the incorrect dsh in dash.
> Btce signals DASH as DSH

- xchange-cexio/src/main/resources/cexio.json
Minimal order size eth on cex.io is now 0.5
> Minimal order size eth on cex.io is now 0.5

- xchange-cexio/src/main/resources/cexio.json
https://cex.io/transaction-fee
Meet great news from CEX.IO!
To express our support for crypto, we have set the fee for trading cryptocurrency pairs to 0%. EUR and RUB pairs experienced fee halving down to 0.1%, which in our opinion will drive growth of respective markets at CEX.IO
The full updated fee schedule is now as follows:
ETH/BTC: 	0%
LTC/BTC: 	0%
GHS/BTC: 	0%
BTC/EUR: 	0.1%
LTC/EUR: 	0.1%
BTC/RUB: 	0.1%
BTC/USD: 	0.2%
LTC/USD: 	0.2%
ETH/USD: 	0.2%
GHS/USD: 	0.2%
We welcome you to enjoy the ease of instant deposits and withdrawals to payment cards, extremely low fees for SEPA payments, as well as trading at far better conditions. Thank you for using CEX.IO.
> Updated cexio with new fee structure

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinExchange.java
Resolves hosts correctly on instantiation depending on exchange specific parameters. Resolves to
- okcoin.com for international spot, international futures
- okcoin.cn for china spot
> OkCoin: resolve hosts correctly on instantiation

- xchange-kraken/src/main/resources/kraken.json
Kraken removed NMC market, http://blog.kraken.com/post/144921846637/kraken-delists-namecoin
> Kraken removed NMC market

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexAccountServiceRaw.java
- xchange-poloniex/src/test/java/si/mazi/rescu/PoloniexAccountJsonTest.java
added parameter "account='all'" for retrieving all balances (including margin + lending balances).
As described on https://poloniex.com/support/api/:
> (returnCompleteBalances) set the "account" POST parameter to "all" to include your margin and lending accounts.
> Poloniex: retrieve all balances (including margin + lending balances)

- xchange-therock/src/main/java/org/knowm/xchange/therock/TheRock.java
TheRock returns 404 because URL is different.
+ look at getTicker and getOrderbook because API documentation says other paths.
> FIX: either api url has changed or this newer worked.

- xchange-anx/src/test/java/org/knowm/xchange/anx/v2/dto/trade/OpenOrdersJSONTest.java
- xchange-core/src/main/java/org/knowm/xchange/utils/DateUtils.java
- xchange-core/src/test/java/org/knowm/xchange/utils/DateUtilsTest.java
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/ItBitAdapters.java
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/dto/marketdata/ItBitTrade.java
Two things fixed:
- ISO8601 parsing – if text ends with 'Z', it is always in UTC 
- change in itbit API – returns timestamp as ISO8601 text instead of date representing millis from start of era.
> Fix for  #1269

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/polling/KrakenTradeServiceRaw.java
I was receiving rejects from Kraken when order requests were sent using exponential notation for the quantity field. Updated limit price to match - not sure if this was necessary but works fine.
> [Kraken] For order submission use BigDecimal toPlainString() method for price and quantity

- xchange-bitstamp/src/main/resources/bitstamp.json
Minimal order amount is 5 usd.
As long as btc is above 500 euro these values are correct.
> Corrected minimal order amounts

- xchange-kraken/src/main/resources/kraken.json
I think these pairs are not valid for the kraken exchange?
> removed incorrect pairs for kraken exchange

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/polling/BitstampTradeService.java
eur/usd pair was missing in open order query.
> Added eur/usd pair

- xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java
- xchange-core/src/main/java/org/knowm/xchange/Exchange.java
- xchange-core/src/main/java/org/knowm/xchange/ExchangeFactory.java
When creating an Exchange with ExchangeFactory, you can now use
setFlag() to set certain options for your ExchangeFactory.
Example:
`ExchangeFactory.INSTANCE.setFlag(ExchangeFactory.DO_REMOTE_INIT_FALSE);`
> Added flagging capability for ExchangeFactory

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexExchange.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexAdapters.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexExchange.java
- xchange-examples/src/main/java/org/knowm/xchange/examples/bitfinex/marketdata/SymbolsDemo.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/marketdata/PoloniexCurrencyInfo.java
Simple implementation of `remoteInit()` for these two exchanges. I haven't yet added `CurrencyMetaData` or `CurrencyPairMetaData`, but this solution works if you just need dynamic currency pairs.
> Implemented remoteInit() for Bitfinex/Bittrex, and fixed a DTO for Poloniex.

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexUtils.java
I kept getting errors about unknown currency pairs on Polonies. PoloniexUtils has the base and counter the wrong way around.
> Switched the base and counter in PoloniexUtils

- xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiExchange.java
Make BitVC work again via exchangeSpecificParams `use_bitvc=true`. This must have broken with the introduction of `initServices`.
> Huobi: conclude host parameters inside initServices

- xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java
- xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/marketdata/IndependentReserveOrderBook.java
- xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReserveOpenOrder.java
- xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReserveTrade.java
use the data type converter in JAXB, since JAXB must be able to parse ISO8601 date string according to the XML Schema specification
> [independentreserve] fixed the ISO8601 timestamp parsing

- xchange-therock/src/main/java/org/knowm/xchange/therock/dto/TheRockException.java
the meta structure could not fir error messages sent by therock
for example 
`{"errors":[{"message":"Not enough balance","code":"21","meta":{"amount":{"value":0.5,"currency":"BTC"},"trading_balance":{"value":0.19913927,"currency":"BTC"}}}]}`
the "meta" object is more complex than "Map<String, String>"
> [therock] fixed the exception structure for error messages

- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/BitbayExchange.java
From https://market.bitbay.pl to http://bitbay.net according specification at https://bitbay.net/public-api
> BitBay API host name changed

- xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/MarketOrder.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/LimitOrderTest.java
I've found that LimitOrder.Builder does not reflect status set to the builder when is building the order.
Is it bug? Attached failing unit test. Can attach fix if agreed.
> LimitOrder.Builder does not set order status properly

- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/BitbayAdapters.java
- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/dto/trade/BitbayOrder.java
- xchange-bitbay/src/test/java/org/knowm/xchange/bitbay/BitbayAdapterTest.java
- xchange-bitbay/src/test/resources/trade/example-orders-data.json
Bitbay is returning "actual" price instead of "limitPrice" for the orders.
> LimitPrice fix for BitBay's open orders.

- xchange-huobi/src/main/java/org/knowm/xchange/huobi/BitVcFutures.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/BitVcFuturesAdapter.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiExchange.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/BitVcFuturesAccountInfo.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/BitVcFuturesPlaceOrderResult.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/BitVcFuturesPosition.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/BitVcFuturesPositionByContract.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/BitVcBaseTradeService.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/BitVcFuturesAccountService.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/BitVcFuturesMarketDataServiceRaw.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/BitVcFuturesServiceRaw.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/BitVcFuturesTradeService.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiBaseTradeService.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiDigest.java
Supporting trading futures on BitVc. Placing limit orders, open positions, and account info implemented to start with.
> Initial support for trading futures on BitVc

- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/service/ItBitHmacPostBodyDigest.java
...because:
- byte[] was represented as BigInteger (not a canonical form, ignores leading zeros)
- UTF-8 encoding was not used when converting strings to byte[].
Details: https://api.itbit.com/docs#faq-2.-how-do-i-sign-a-request?
> FIX: signature was wrongly constructed 

- xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineExchange.java
- xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/trade/QuoineNewMarginOrderRequest.java
Quoine allows trading on margin without explicit borrowing, fiat as collateral and "netout" which functions going long and short just like in spot (if you are long 2 and sell 3 you are short 1).
> xchange-quoine: Default netting strategy and leverage fixes

- xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineAccountService.java
The various account API calls together with how BTC is accounted for between spot and margin is quite confusing. This fix adjusts getting the "fiat" accounts (which include BTC) for spot and margin. This is probably more sane and in line with other margin exchange implementations.
> xchange-quoine: AccountInfo fixes

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampExchange.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
Bitstamp open orders was ignoring xrp orders. Changed implementation to all exchange symbol pairs in stead of local hardcoded pairs
> Bitstamp open orders was ignoring xrp orders

- xchange-examples/src/main/java/org/knowm/xchange/examples/poloniex/trade/PoloniexTradeDemo.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeService.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
Note that this is breaks compile-time compatibility with old client code using the raw interface (the generic interface is fine). If anyone is using this, this can be fixed with minor code changes (detected by the compiler):
Clients calling `PoloniexAuthenticated::returnOpenOrders` should change the last parameter from `"all"` to `PoloniexAuthenticated.AllPairs.all`.
`PoloniexTradeServiceRaw::returnOpenOrders()` now returns a `Map` instead of a `HashMap`.
@timmolter I'd like to see this merged asap, but I'm leaving the decision whether to wait for a version bump or not to you.
> Poloniex: Support getting open orders only for selected currency pair.

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexCancelOfferRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexCancelOrderMultiRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexCancelOrderRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexOfferStatusRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexOrderStatusRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexOrderStatusResponse.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java
- xchange-bitfinex/src/main/resources/bitfinex.json
Bitfinex order numbers are now to high to fit in a signed int. (resulting in errors at placing orders and retrieving open orders. Error at place order is a real problem, the order is executed, but result results in an error)
Increased order number to long type.
Added new coins, also conversion of dsh to dash
> Bitfinex errors solved and added new coins

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
Dash pairs don't contain the x or z identification
> Dash pairs don't contain the x or z identification on kraken

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
USDT and DASH asset pairs are 7 chars long (normal 6)
This resulted in open order pairs like: DAS/BTC for DASH/USD or USD/USD for USDT/USD
> Kraken: Openorders can contain a 7 size string for assets pairs

- xchange-core/src/main/java/org/knowm/xchange/ExchangeFactory.java
Noticed these convenience methods could reduce the initialization boilerplate by a few lines for most users.
But this PR actually stems from a separate issue I ran into. By mistake I set the API keys only after constructing the `Exchange`, which resulted in a signing exception, since (it took me a while to find that) during initialization the secret key was not yet set when it was passed to `KrakenDigest` in the `KrakenBaseService` constructor. Other exchanges likely have the same issue.
A possible solution would be to create a `ExchangeSpecificationBuilder` class that returns an immutable `ExchangeSpecification`. That way I couldn't call a setter after the value had already been used, and it would allow moving the default specification out of the instance method, which may then enable …
> Add convenience methods to ExchangeFactory

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexUtils.java
Bittrex has some responses that use milliseconds, and some that don't. I guess that's why this was originally changed to use javax.xml.bind. I fixed this by just have a date parser for each of the possible two date formats that Bittrex responds with.
> [Bittrex] added date parser with no milliseconds

- xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiExchange.java
Use correct api url. "http://market.huobi.com/staticmarket" is obsolete.
> [Huobi] Update api url

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinExchange.java
Support for okex.com, the futures exchange endpoint of okcoin.com.
Let's see if this is enough, or if okex.com requires its own module at some point.
https://github.com/timmolter/XChange/issues/1484
> xchange-okcoin: Use new URIs for okcoin.com futures

- xchange-yobit/src/main/java/org/knowm/xchange/yobit/YoBitAdapters.java
To maintain consistency with the rest of the API, the volume in the ticker should be in the BASE currency.
That value can be acquired via `vol_cur` of the API call
> [#hotfix] Yobit volume should be in the base currency

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinExchange.java
Adjust instantiation to allow for:
- okcoin china (okcoin.cn)
- okcoin international spot (okcoin.com)
- okcoin international futures (okex.com)
> xchange-okcoin: Fix wrong configuration

- xchange-ccex/src/main/java/org/knowm/xchange/ccex/CCEXAdapters.java
If there is no any bid or ask we have null instead of zero length list and fall with NPE.
> [CCEX] - fix NPE in order book adapter

- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/dto/marketdata/GeminiTicker.java
It looks like Gemini changed what is returned on their ticker call:
https://docs.gemini.com/rest-api/#ticker
With this change "TickerFetchIntegration" runs without throwing an exception
> Fix Gemini Ticker Serialization

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexUtils.java
> replace("USD","USDT")
this is not a very clean way to handle currencies
in our application we use explizit USDT currency, now after passing it through this, we get "USDTT", which leads to an error of course
i would like to change it back, if you do not mind
thanks
> [poloniex] dropped the usdt mapping

- xchange-core/src/main/java/org/knowm/xchange/ExchangeSpecification.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexBaseService.java
I've added a HTTP read timeout configuration to the ExchangeSpecification class to allow the read timeout to be configured on a per exchange basis. I've implemented this for Kraken and Poloniex since in the last couple of months or so these exchanges have required longer timeouts. The exchange specific timeout will override the global rescu configuration, e.g. from rescu.properties. 
Also contains minor fix for GDAX trade history and improvement to Gemini timestamp conversion.
> [Core, Kraken, Poloniex] HTTP read timeout configurable by exchange

- xchange-bitmarket/src/main/java/org/knowm/xchange/bitmarket/BitMarketUtils.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexAuthenticated.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/service/BittrexTradeService.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/service/BittrexTradeServiceRaw.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/BleutradeAdapters.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/BleutradeAuthenticated.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/BleutradeTradeService.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/BleutradeTradeServiceRaw.java
- xchange-bleutrade/src/test/java/org/knowm/xchange/bleutrade/service/BleutradeTradeServiceTest.java
- xchange-dsx/src/main/java/org/knowm/xchange/dsx/dto/meta/DSXMetaData.java
- xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/v1/trade/BittrexTradeDemo.java
* fixed incorrect use of == in BitMarket utils that can prevent ccy pairs from being recognised	
* implemented getTradeHistory for BleutradeTrade	
* made DSK metadata suport the 'standard' fields
* implemented OpenOrdersParamCurrencyPair in BittrexTradeService
> some fixes

- xchange-coinbase/src/main/resources/coinbase.json
Coinbase added both ETH/USD and LTC/USD.
> [Coinbase] Update coinbase.json for ETH and LTC

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexAuthenticated.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexUtils.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/service/BittrexTradeService.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/service/BittrexTradeServiceRaw.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/BleutradeTradeServiceRaw.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeService.java
[bittrex] made getTradeHistory optionally support TradeHistoryParamCurrencyPair [bittrex] made getBittrexOpenOrders support currency pairs that already have BTC as the base currency (like BTC_XRP) 
[hitbtc] made getTradeHistory optionally support TradeHistoryParamPaging and TradeHistoryParamCurrencyPair
[bluetrade] implemented TradeHistoryParamCurrencyPair and changed the default trade history so it doens't return cancelled trades (as this isn't really supported in the UserTrade class)
> [hitbtc, bittrex, bluetrade] improvements to getTradeHistory and getOpenOrders

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/BittrexUtils.java
This logic broke the ticker ability for Bittrex.
> Removing Logic added in Bittrex Utils at 916f3b32647f4d3255b5907a4d266d56d5fd05fa. 

- xchange-jubi/src/main/java/org/knowm/xchange/jubi/Jubi.java
- xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiAdapters.java
- xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiExchange.java
- xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiBaseService.java
- xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiMarketDataService.java
- xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiMarketDataServiceRaw.java
- xchange-jubi/src/test/java/org/knowm/xchange/jubi/service/marketdata/TickerFetchIntegration.java
1. Move MarketData RestProxy from BaseService down to JubiMarketDataServiceRaw, which allow us to decouple different proxies(market data, account, trade...) in the next development. 
2. Add getAllTickers interface to fetch all e-coins' tickers by one restful request (Path：/api/v1/allticker/).
> [Jubi] Add getAllTickers interface to fetch all e-coins' tickers by one request

- xchange-examples/src/main/java/org/knowm/xchange/examples/gdax/GDAXTickerDemo.java
Looks to be a copy paste mistake. Updated the name to reference gdax as opposed to bitstamp in this gdax example.
> Update GDAXProductTicker obj name from bitstampTicker to gdaxTicker

- xchange-kraken/src/main/resources/kraken.json
Usdt minimal order amount seems to be 5 usdt. (non documented on their support pages, found this amount with trying)
> Updated kraken non documented minimal usdt order amount

- xchange-kraken/src/main/resources/kraken.json
These pairs are not supported anymore by Kraken.
https://github.com/timmolter/XChange/issues/1673
> Removed XRP/GBP and REP/CAD

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinAdapters.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/dto/trade/OkCoinOrder.java
`OkCoinOrder` didn't reflect the actual filled price. `price` is from the order client placed and `avg_price` is the actual filled price. 
`adaptOpenOrder()` didn't include the order status and filled size. `adaptOrderStatus` and `dealAmount`should be added.
> [okcoin] add averagePrice and status for limit order

- xchange-cexio/src/main/resources/cexio.json
Cexio changed the minimal amounts for bch. These values are from their webinterface indicated as minimal amount. (strange value for bch/btc but smaller orders do indeed fail on the api)
> CexIO changed the minimal amounts for bch

- xchange-bitstamp/src/main/resources/bitstamp.json
ETH added to bitstamp json file. Changed min amount of BTC and XRP to latest market values.
https://www.bitstamp.net/article/free-ether-trading-limited-time-only/
> Bitstamp added ETH

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinAdapters.java
The date returned from server is already in millisecond. Shouldn't multiply by 1000L. 
https://www.okcoin.com/about/rest_api.do
URL https://www.okcoin.com/api/v1/account_records.do
> [okcoin] Fix adaptDate

- xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXMarketDataService.java
- xchange-bitcoinium/src/main/java/org/knowm/xchange/bitcoinium/service/BitcoiniumMarketDataService.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexMarketDataService.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/v1/service/BittrexMarketDataService.java
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/BleutradeMarketDataService.java
- xchange-btcchina/src/main/java/org/knowm/xchange/btcchina/service/rest/BTCChinaMarketDataService.java
- xchange-btce/src/main/java/org/knowm/xchange/btce/v3/service/BTCEMarketDataService.java
- xchange-btctrade/src/main/java/org/knowm/xchange/btctrade/service/BTCTradeMarketDataService.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOMarketDataService.java
- xchange-coinfloor/src/main/java/org/knowm/xchange/coinfloor/service/CoinfloorMarketDataService.java
- xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaMarketDataService.java
- xchange-dsx/src/main/java/org/knowm/xchange/dsx/service/DSXMarketDataService.java
- xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/service/GatecoinMarketDataService.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataService.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcMarketDataService.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenMarketDataService.java
- xchange-luno/src/main/java/org/knowm/xchange/luno/service/LunoMarketDataService.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinFuturesMarketDataService.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinMarketDataService.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexMarketDataService.java
- xchange-ripple/src/main/java/org/knowm/xchange/ripple/service/RippleMarketDataService.java
- xchange-taurus/src/main/java/org/knowm/xchange/taurus/service/TaurusMarketDataService.java
I was testing out cryptopia exchange support and I was getting NullPointerException because the implementation of `CryptopiaMarketDataService.java` assumes `args` is not null when in reality null should be a perfectly valid value.
I did a quick find/grep for every implementation that wasn't doing null checks and added them.
> add null checks to MarketDataService classes

- xchange-core/src/main/java/org/knowm/xchange/service/BaseExchangeService.java
Poloniex's currency pair meta data doesn't seem to ever have a minimum amount. This means that the verifyOrder method typically fails on Poloniex. I'm happy to make the pull request better, but there doesn't seem to be any other meta data about the currency pair that one could check to stay in line with the spirit of the verifyOrder method. Poloniex does tend to have the price scale int value, making a call to metaData.getPriceScale() valid but that seems like it would return an int value of price scale for the quote currency. I'm not sure we can infer that the tradeable amount's scale must be less than (or equal to?) the quote currency's price scale. If that is a good assumption I'm happy to put it in and throw an IllegalArgumentException.
> add null check for minimum amount (for poloniex)

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/WithdrawalRequest.java
bitstamp reports the status "10" for some withdrawals, this status is not documented
to avoid the IllegalArgumentException lets assume the status is "in_process"
> [bitstamp] support status value 10

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/WithdrawalRequest.java
very annoying
after adding the status value of "10" (see https://github.com/timmolter/XChange/pull/1709), what ever that means, now i get "8"
the values are still not documented by bitstamp, support request is on the way...
i just changed the method, by adding an "unknown" status, so at least we do not get the IllegalArgumentException
> [bitstamp] support unknown status values

- xchange-kraken/src/main/resources/kraken.json
Kraken removed some pairs: 
In order to help mitigate the strain on our platform caused by recent exponential
growth, we are delisting some of our illiquid trading pairs and temporarily
suspending all advanced order types. *These changes will go into effect on Tuesday,
August 22 around 6 am UTC (Monday August 21 around 11 pm Pacific).*
* XBT/GBP
* ETH/GBP
* XRP/CAD
* XRP/JPY
* EOS/EUR
* EOS/USD
* XLM/EUR
* XLM/USD
* GNO/EUR
* GNO/USD
* REP/USD
you will only be able to create basic limit and market orders)
Open orders will remain open until cancelled or executed, but you will no longer be
able to create new orders in any of the following advanced types:
* Stop Loss
* Take Profit
* Stop Loss, Take Profit
* Stop Loss, Take Profit Limit
* Stop Loss Limit
* Take Profit Limit
* Trailing Stop
* …
> Updated kraken.json

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
The iso currency code was returned for open orders in stead off the commenly used currency code (XBT was reported iso BTC)
> Kraken: Return commenly used currency codes for open orders

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoin.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountService.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountServiceRaw.java
- xchange-okcoin/src/main/resources/okcoin_china.json
- xchange-okcoin/src/main/resources/okcoin_intl.json
Update Okcoin json to include min_amount and ETH.
Partially fix withdraw crypto by adding withdraw target, correcting currency symbol and fees.
API reference: 
https://www.okcoin.com/about/rest_api.do
https://www.okcoin.com/api/v1/withdraw.do
> [Okcoin] Update json and withdraw crypto

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinDigest.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinUtils.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountService.java
- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountServiceRaw.java
This would fix withdrawal issues arises when 'tradepwd' includes characters that encoded differently in  Unicode and ASCII. tradepwd should be encoded in ASCII.
Default target should be external address, so 'address' is appropriate.
> Issue #1710 resolves [Okcoin] Withdraw crypto not working

- xchange-examples/src/main/java/org/knowm/xchange/examples/quoine/QuoineExamplesUtils.java
- xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineExchange.java
- xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineBaseService.java
Currently, xchange-quoine uses it's own specification parameter for setting api(or, token, in the terms of quoine exchange) and secret key.  This does not follow convention, so I thought it would be better to use the ordinal interface of `ExchangeSpecification#getApiKey()` and `ExchangeSpecification#getSecretKey()`.
(Can revent new people stumbling on this peculiarity, e.g. #1398 , IMO.. )
> [quoine] use getApiKey and getSecretKey

- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/Gemini.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataService.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataServiceRaw.java
Gemini lets you increase the number returned to 1000, the default is 50.
> Add limit_trades param to Gemini getTrades

- xchange-kraken/src/main/resources/kraken.json
Updates `kraken.json` regarding the latest decimal place modification effective September 6 around 6 am UTC. Kraken mail notification:
> 
> Effective Wednesday September 6 around 6 am UTC (Tuesday September 5 around 11 pm PT) we will be changing the allowed decimal place precision for placing orders. We had a lot of feedback from clients after the previous change in precision, with most saying they would like to see the precision reduced even further in some pairs, though we are increasing the precision for a few pairs as well. Reducing price precision can help order books operate more efficiently by reducing the volume of canceled (unfilled) orders as traders continually jump in front of each other by a small fraction in price.
> 
> Below is a list of all trading pairs showing the new …
> Update decimal place precision for Kraken

- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXAccountService.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
Update Kraken's adaptLimitOrder to use original amount and filled amount. Notice there is a proposed change of LimitOrder to include 
```
OriginalAmount
FilledAmount
RemainingAmount
```
While we are still waiting for the upper level change, I think this is good for now. 
This PR also add `adaptOrderStatus`.
> [kraken] Adapt limit order

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
Homepage - https://omg.omise.co/
Stats / MarketCap - https://coinmarketcap.com/assets/omisego/
Trading Exchanges - https://www.coingecko.com/en/coins/omisego/trading_exchanges
OMG pairs at Bitfinex - https://www.bitfinex.com/stats
> Add OmiseGO (OMG) currency and related currency pairs OMG/USD, OMG/BTC and OMG/ETH

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
I propose set remaining amount instead of original to LimitOrder on adapting Bitfinex open orders (reason: amount in open orders never change until full order operation)
> issue #1767: Bitfinex open orders adaptation

- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiExchange.java
- xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/GeminiAdaptersTest.java
- Fix LimitOrder getFilledAmount. 
- Update Gemini and Gdax's open order adapters to include original, remaining and filled amount. 
- Use `AtomicLongCurrentTimeIncrementalNonceFactory` instead of `AtomicLongIncrementalTime2013NonceFactory` because according to Gemini, "e recommend using a timestamp at millisecond or higher precision"
https://docs.gemini.com/rest-api/#private-api-invocation
`AtomicLongIncrementalTime2013NonceFactory` is rounding down the precision.
> [Core] Fix getFilledAmount [Gemini] [Gdax] Adapt open order

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAuthenticated.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexFundingTradeResponse.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexPastFundingTradesRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java
- xchange-examples/src/main/java/org/knowm/xchange/examples/bitfinex/trade/BitfinexTradeDemo.java
I implemented to fetch the lending history for Bitfinex. 
I also tested it (and left a test in the bitfinex-examples) and it works.
The only thing I'm not sure: The Bitfinex docs state that there's a RateLimit of 45reqs/min. Does that have to be considered somewhere? 
And, just out of curiousity: Is the Ratelimit per Api Key or per Server?
Please, since it's my first commit to this project, doublecheck it. If approved, please merge it into develop :)
Kind regards,
David
> Bitfinex Lending history implemented

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java
On Kraken exchange, getFundingHistory(...) only returns BTC or USD
funding events with the default TradeHistoryParams. Modify default
TradeHistoryParams instantiation so that the funding events for all
currencies are returned. Fixes #1829.
> Kraken - Get funding history for all currencies

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAdapters.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
Order class already holds cumulativeAmount, so remainingAmount can be directly retrieved via originalAmount.subtract(cumulativeAmount). 
- Order.getRemainingAmount() method for that purpose. LimitOrder.remainingAmount was removed.
- C'tors and Builders were updated accordingly
- All relevant exchanges adapters were updated accordingly.
NOTE: Consider removing LimitOrder.getFilledAmount() which is the same as Order.getCumulativeAmount and causes confusion.
> Implement remainingAmount via cumulativeAmount

- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Ticker.java
This PR is a suggestion to add `open` attribute to the `Ticker` class.
A lot of exchanges support it and they either set this value to "the price from 24h ago" or "the price at 00:00 on a given day" for example:
* Bitstamp - https://www.bitstamp.net/api/ticker/ - `open` attribute is the "First price of the day"
* Bittrex - https://bittrex.com/api/v1.1/public/getmarketsummaries - `PrevDay` attribute - "the price at 24h ago"
If this PR is accepted, I can edit few of the `Ticker` implementations to add support for that attribute, but I'm sure that there are many changes which don't support it
> Add 'open' field to 'Ticker'

- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/dto/trade/GeminiCancelOrderRequest.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/dto/trade/GeminiLimitOrder.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/dto/trade/GeminiOrderStatusRequest.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/dto/trade/GeminiOrderStatusResponse.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiTradeService.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiTradeServiceRaw.java
- xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/GeminiAdaptersTest.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/KrakenAdaptersTest.java
This was causing deserialization exceptions. e.g. 
```
si.mazi.rescu.HttpStatusIOException: Can not deserialize value of type int from String "2147483855": Overflow: numeric value (2147483855) out of range of Integer (-2147483648 - 2147483647)
at org.knowm.xchange.gemini.v1.service.GeminiTradeServiceRaw.getGeminiOpenOrders(GeminiTradeServiceRaw.java:39)
at org.knowm.xchange.gemini.v1.service.GeminiTradeService.getOpenOrders(GeminiTradeService.java:51)
```
I've also removed a couple of compiler warnings, and fixed a Kraken unit test (example-assetpairs-data.json had changed 3 months ago) for for #1866.
> [Gemini] changed order ID to a long since it now exceeds Integer.MAX_VALUE

- xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineAdapters.java
- xchange-quoine/src/test/java/org/knowm/xchange/quoine/dto/QuoineAdaptersTest.java
Bug Fix for Quoine, ticker last price change from LastPrice24h to LastTradedPrice
Before this fix
Ticker [currencyPair=BTC/USD, open=null, **last=5948.35**, bid=6669.81, ask=6730.0, high=null, low=null,avg=null, volume=1207.39716996, timestamp=null]
QuoineProduct{id=1, productType='CurrencyPair', code='CASH', name=' CASH Trading', marketAsk=6730.0, marketBid=6669.81, indicator=1, currencyPairId='null', currency='USD', currencyPairCode='BTCUSD', symbol='$', btcMinimumWithdraw=0.02, fiatMinimumWithdraw=15.0, pusherChannel='product_cash_btcusd_1', takerFee=0.0, makerFee=0.0, lowMarketBid=5886.2, highMarketAsk=6775.60145, volume24h=1207.39716996, **lastPrice24h=5948.35**, cashSpotAsk=null, cashSpotBid=null, **lastTradedPrice=6730.0**, quotedCurrency='USD', baseCurrency='BTC'}
> Bug Fix for Quoine, ticker last price change from LastPrice24h to LastTradedPrice

- xchange-anx/src/test/java/org/knowm/xchange/anx/v2/bootstrap/ANXGenerator.java
- xchange-bitfinex/src/main/resources/bitfinex.json
- xchange-bitstamp/src/main/resources/bitstamp.json
- xchange-bittrex/src/main/resources/bittrex.json
- xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/BleutradeAdapters.java
- xchange-btce/src/main/java/org/knowm/xchange/btce/v3/BTCEAdapters.java
- xchange-btce/src/main/resources/btce.json
- xchange-cexio/src/main/resources/cexio.json
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyMetaData.java
- xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/CryptopiaAdapters.java
- xchange-dsx/src/main/java/org/knowm/xchange/dsx/DSXAdapters.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
- xchange-kraken/src/main/resources/kraken.json
- xchange-poloniex/src/main/resources/poloniex.json
- xchange-yobit/src/main/java/org/knowm/xchange/yobit/YoBitAdapters.java
Withdrawals fees are usually fixed and I think they can be part of the currency metadata class.
JSON resource file is currently updated only to 7 exchanges.
> Minor: Add withdrawals fees on exchanges meta data

- xchange-examples/src/main/java/org/knowm/xchange/examples/therock/trade/TheRockTradeRawDemo.java
- xchange-therock/src/main/java/org/knowm/xchange/therock/TheRockAuthenticated.java
- xchange-therock/src/main/java/org/knowm/xchange/therock/service/TheRockTradeServiceRaw.java
Until now the implementation only contains a single "orders" method,
which accepts only a single argument (the fundId/tradingPair).
This commit adds a second "orders" method, which supports all query
parameters supported by the "/v1/funds/:fund_id/orders" API endpoint:
- "after" (filter orders after a certain timestamp)
- "before" (filter orders before a certain timestamp)
- "status" (accepted values are: active, conditional, executed)
- "side" (filter orders by side. Accepted values are: buy, sell)
- "position_id" (filter orders by margin position ID)
- "page" (used for pagination, if results are more than 1 page)
See API-documentation here:
https://api.therocktrading.com/doc/v1/index.html#api-Trading_API-ListOrders
> TheRock: add all query parameters for /orders request

- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/CoinMarketCap.java
Existing method was always limited to 100 results
> Overloaded CoinMarketCap.getTickers with limit

- xchange-liqui/pom.xml
- xchange-liqui/src/main/java/org/knowm/xchange/liqui/LiquiAdapters.java
From liqui spec:
start_amount: The initial amount at the time of order creation.
amount: The remaining amount of currency to be bought/sold.
> fixed filled amount

- xchange-poloniex/src/main/resources/poloniex.json
Closes #1910 , removed exchange symbols NAUT/BTC, NOTE/BTC.
> Closes #1910 , removed exchange symbols NAUT/BTC, NOTE/BTC.

- xchange-core/pom.xml
- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/test/java/org/knowm/xchange/CurrencyTest.java
The current equal() implementation doesn't work when using deserialized objects, this change fixes it.   (also fixes #1782)
> [core] fix Currency equals/hashCode for deserialized objects

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java
PR #1972 causes NullPointerExceptions for open order query if the default params object is used without setting a currency pair. (There is already a check for null in the trade history query.)
> [Bittrex] open order query check for null currency pair

- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java
- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateOpenOrdersEntry.java
- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateTradeService.java
It was causing that currencyPair was missing if input parameter currencyPair was null.
It don't allows return list of all pending transaction without limiting it to one type.
> [CoinMate] fill currencyPair in the open orders result with real value returned from API instead of optional input parameters

- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateUtils.java
- xchange-coinmate/src/main/resources/coinmate.json
API rate limit is based on
https://coinmate.docs.apiary.io/#reference/request-limits/get
> [CoinMate] added BCH support and fixed API rate limit

- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/service/CoinMarketCapMarketDataService.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/service/CoinMarketCapMarketDataServiceRaw.java
Fixing CoinMarketCap ticker retrieval.
Only the first 200 results are returned by using `/tickers` endpoint without `limit` request parameter and that leads to missing currency pairs in loaded tickers.
Please review my fix, I am open to your thoughts, thanks.
> Retrieve all tickers from CoinMarketCap by setting `limit=0` request param

- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java
The order status returned from the current GDAXTradeService implementation is completely bogus (always returned as a LimitOrder, even if it's a MarketOrder. And it never includes a status other than Pending_New). See Issue #1860
Intend to fix in the future. But we need the implementation to fail gracefully, rather than return bogus
statuses just for GDAX.
> Removed broken GDAX order status implementation. 

- xchange-gemini/src/main/resources/gemini.json
The following documentation for Gemini shows that the precision ("minimum increment) for ETH should be 6 not 8. 
https://docs.gemini.com/rest-api/#symbols-and-minimums
> Gemini ETH precision correction

- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAdapters.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAuthenticated.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeService.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRaw.java
This PR implements the `getOrder(String... orderIds)` method for `HitbtcTradeService`. A new remote method `getHitbtcOrder` has been implemented in `HitbtcAuthenticated`. This new method calls the `history/order` endpoint providing the `clientOrderId` of the order the user wants to retrieve.
Furthermore, a new order status adapter has been implemented, alongside some other minor refactors in `HitbtcAdapters`
> [Hitbtc] implements HitbtcTradeService#getOrder

- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/service/CoinMarketCapMarketDataService.java
`CoinMarketCapMarketDataService` caches all tickers permanently. This allows refreshing new tickers to the user.
Please review.
> [CoinMarketCap] possibility to retrieve fresh tickers

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java
- xchange-coinfloor/src/main/java/org/knowm/xchange/coinfloor/service/CoinfloorOpenOrdersParams.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParamCurrencyPair.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParamMultiCurrencyPair.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParams.java
Bitfinex API does not provide filtering option. So we should filter orders ourselves
> [BitFinex] Implemented XChange-side open orders filtering

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceTicker24h.java
I'm trying to implement ticker subscriptions in xchange-streams and the market data DTOs are needed. The other DTOs in this package are public. Unsure if there's any reason this isn't already public
> Make binance ticker dto constructor public

- xchange-bitmex/pom.xml
- xchange-core/pom.xml
Moved guava-collections from xchange-core to xchange-bitmex (the only place it is used) and upgraded it to the latest version of guava. But I suggest that this dependency be removed, as it's a rather large one.
> Fix for old guava-collections include from recent bitmex merge

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/marketdata/BitfinexTicker.java
When using xchange-stream's Bitfinex implementation it fakes the timestamp because Bitfinex somehow forgot to include one in their Ticker payload. It runs `System.currentTimeMillis() / 1000` which, when stored as a float, was giving me times that were sometimes as much as 90 seconds in the future. Fixing the `BitfinexTicker` to use a double instead has made the math work properly and my timestamps are now all in the past, where they're supposed to be.
> [Bitfinex] Floats don't have enough precision to store timestamps.

- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
- xchange-gdax/src/test/java/org/knowm/xchange/gdax/GDAXAdaptersTest.java
The `open` field was not being populated for GDAX tickers, this change fixes that.
> Add "open" to GDAX ticker

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexUtils.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexPrivateOrder.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountService.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountServiceRaw.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexDigest.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataService.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
This PR fixes a couple issues with the BitMEX adapter:
- BitMEX's API key scheme is URL-encoded.
- BitMEX allows testing via `testnet.bitmex.com`. Testnet lists different instruments than the production site, but the currency pairs were locked in from first connecting to the live site. Connecting to testnet would not update the currency pairs, and raise an exception.
> BitMEX client

- xchange-core/src/main/java/org/knowm/xchange/dto/trade/OpenOrders.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXOrder.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
- xchange-gdax/src/test/java/org/knowm/xchange/gdax/GDAXAdaptersTest.java
- xchange-gdax/src/test/resources/order/example-stop-order-filled.json
- xchange-gdax/src/test/resources/order/example-stop-order-new.json
- xchange-gdax/src/test/resources/order/example-stop-order-stopped.json
I figure that returning "non book" orders might represent a material change to the API of `OpenOrders` which might break existing clients, so I've suggested a new `OpenOrders.getHiddenOrders` method to expose those.  This could be used for other non book orders like hidden orders on BFX.
Implements #1865, #2177
> [gdax] Allow listing/checking open stop orders.

- xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIO.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOExchange.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexIOApiResponse.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/account/CexIOFeeInfo.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/marketdata/CexIOCurrencyLimits.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOAccountServiceRaw.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOMarketDataServiceRaw.java
- xchange-cexio/src/test/java/org/knowm/xchange/cexio/dto/account/CexIOFeeInfoTest.java
- xchange-cexio/src/test/java/org/knowm/xchange/cexio/dto/marketdata/CexIOCurrencyLimitsTest.java
- xchange-cexio/src/test/java/org/knowm/xchange/cexio/service/marketdata/RemoteInitIntegration.java
- xchange-cexio/src/test/java/org/knowm/xchange/cexio/service/marketdata/RemoteInitTest.java
- xchange-cexio/src/test/resources/account/sample_get_myfee.json
- xchange-cexio/src/test/resources/marketdata/sample_currency_limits.json
This irked me a bit - cex.io actually has a fairly varied set of limits, and the included json was static data, so needed to fix.
> [Cex IO] Adding a remote init to get the correct minimumAmounts

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataServiceRaw.java
This PR fixes an issue where getTrades() would be limited to 100 responses.
> [bitmex] add pagination for getTrade requests with > 100 responses

- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/Abucoins.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/AbucoinsAdapters.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/AbucoinsAuthenticated.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/account/AbucoinsDepositHistory.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/account/AbucoinsDepositsHistory.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/account/AbucoinsHistory.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/account/AbucoinsWithdrawalHistory.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/account/AbucoinsWithdrawalsHistory.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/marketdata/AbucoinsFullTicker.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/dto/trade/AbucoinsOrder.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsAccountService.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsAccountServiceRaw.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsMarketDataService.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsMarketDataServiceRaw.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeHistoryParams.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeService.java
Also replacing deprecated calls with current naming convetion.
Also, ran into a situation where a value that was modeled as an enum
was returned with a new value that I hadn't seen in the documentation.
This causes the mapping to fail during the json marshalling.
To improve the failure behavior in this case, I internally switched the
field to be a String so that json parsing would succeed.  I do however
continue to use the enum at the Pojo API level, it just treats strings
it doesn't recognized as 'unknown'.  This seems like more desirable
behavior as the API continues to work, it may just be that your status
isn't mapped to a known value.  If you aren't using the status, has no
impact, if you need the status, then there's a raw method for obtaining
the string value.  It made debugging …
> [abucoins] API was updated on abucoins, adding new methods

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexAccountServiceRaw.java
- Actually throw an ExchangeException, instead of just returning a 0 id
in case of an error in the withdrawal response.
- Adding an undocumented, but tested to be working bgold 'type' for BTG
- variable name spelling error withdrawRepsonse => withdrawResponse
> [bitfinex] bugfixes

- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java
Fixed:
`java.lang.NumberFormatException: For input string: "1.519321274396496E12"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:589)
at java.lang.Long.valueOf(Long.java:803)
at org.knowm.xchange.livecoin.LivecoinAdapters.adaptOpenOrder(LivecoinAdapters.java:178)`
> [Livecoin] Support parsing of numbers in exponential notation

- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java
- xchange-itbit/pom.xml
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/ItBitAdapters.java
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/service/ItBitTradeService.java
[itbit] merges multiple fills for a single order into a single UserTrade and uses the order id to represent the trade id (because itbit doesn't have the concept of a trade id).
[itbit] translates XBT to BTC for the itbit response data.
[itbit] Added some checks in `getTradeHistory` to avoid potential invalid ClassCastExceptions  
[coinmate] more statuses for funding
> [itbit, coinmate] fixes

- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsAccountService.java
- xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeService.java
I sat down to update the Abucoins implementation to support the last generic API call (for creating stop orders).
It turns out their API doesn't support this, so I corrected the exception.
> [abucoins] Abucoins doesn't support stop orders

- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/ItBitAdapters.java
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/dto/marketdata/ItBitTrade.java
Via https://api.itbit.com/docs#market-data-get-recent-trades-get:
```json
{
count: 3,
recentTrades: [
{
timestamp: "2015-05-22T17:45:34.7570000Z",
matchNumber: 27475,
price: "351.45000000",
amount: "0.00010000"
},
{
timestamp: "2015-05-22T17:01:08.4270000Z",
matchNumber: 27474,
price: "352.00000000",
amount: "0.00010000"
},
{
timestamp: "2015-05-22T17:01:04.8630000Z",
matchNumber: 27473,
price: "351.45000000",
amount: "0.00010000"
}
]
}
```
> [itbit] fix trade tid to matchNumber

- xchange-anx/pom.xml
- xchange-anx/src/main/java/org/knowm/xchange/anx/v2/ANXAdapters.java
- xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXAccountService.java
- xchange-anx/src/test/java/org/knowm/xchange/anx/v2/service/account/FundingRecordTest.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/BinanceCurrencyPairMetaData.java
Essentially, the walletHistory from ANX provides separate records for trades, deposits, withdrawals and fees. Fees can be matched to appropriate transactions using the transaction id.
binance has a minNotional order size filter, which blocks orders, even if they fall between the min and max order quantity. Adding a way to get this for using a CurrencyMetadata subclass.
> [ANX, binance] multiple changes

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountService.java
Can't currently use requestDepositAddress for Bitmex due to issue with currency code. Fixed in pull request.
> bitmex uses a lower-case 't' in XBT when getting deposit address and sandbox support

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/OrderType.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/OpenOrders.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/DefaultCancelOrderParamId.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/DefaultQueryOrderParam.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java
added gdax support for new getOrder function implemented in pr #2361
added support for getOpenOrders without currency mentioned in issue #2287
> added support for newly implemented getOrder to gdax and getOpenOrders without currency to binance

- xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinTradeService.java
PR #2367 broke my application because cancelOrder(CancelOrderParams) now requires an instance of OkCoinCancelOrderParam rather than using interface CancelOrderByIdParams as before. 
While I agree that it is good to have removed the multi-api calls that were previously in place for cancelOrder(String orderId) I think the current situation can be improved by reverting back to CancelOrderByIdParams and having an additional requirement for CancelOrderByCurrencyPair. 
I've also changed OkCoinCancelOrderParam to implement both these interfaces. 
@cymp I hope this is OK with you.
> [OkCoin/OKEX] change cancelOrder(CancelOrderParams) to be more flexible

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataServiceRaw.java
b47c580 fixes the 4.3.4 NPE was from "Use_Sandbox" not being initialized
92613a8 fixes the exception from remoteInit:  `IllegalArgumentException: value already present: H18`
> [bitmex] fix exception and NPE

- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java
we can now specify if we want to sort bids and asks at orderbook creation
> [core] Added OrderBook sorted constructors

- xchange-abucoins/api-specification.txt
Just noticed there was still a references to cex.io in one of the documentation files.
> [abucoins] Fixed minor cut-n-paste error.

- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/KucoinTradeHistoryParams.java
Actually a followup PR to support querying trade history with specific start- and end-time (see #2453).
> [kucoin] Allow to specify (optional) timespan on trade history params.

- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/Bitbay.java
- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/service/BitbayMarketDataServiceRaw.java
Lets you download up to 150 trades in one request instead of the default 50
> Limit parameter for bitbay trades history

- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java
- xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
Also renamed the after parameter. The current name
actually incorrectly explains the behaviour. The names
that GDAX assigns to them are also confusing:
* before - returns trades after this trade ID
* after - returns trade before this trade ID
However, consistency with the API seemed the best way to go.
> [GDAX] Adds before param to getFills

- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAuthenticated.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcOrderType.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTimeInForce.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeService.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRaw.java
1. clientOrderId now supported
2. custom Time-in-force now supported for limit orders
3. Order type and Time-in-force now placed in the separate enum
> Update HITBTC placeOrder functionality

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/marketdata/BitstampTicker.java
The Bitstamp Ticker, both generic and raw, were not returning the `open` price. This patch adds open into the Bitstamp dto and adapter.
Previous ticker output:
```
Ticker [currencyPair=BTC/USD, open=null, last=9270.00, bid=9270.00, ask=9271.30, high=9328.09, low=8974.62,avg=9145.57, volume=11788.29697217, quoteVolume=null, timestamp=1525877122000, bidSize=null, askSize=null]
BitstampTicker [last=9270.00, high=9328.09, low=8974.62, vwap=9145.57, volume=11788.29697217, bid=9270.00, ask=9271.30, timestamp=1525877122]
```
Updated ticker output:
```
Ticker [currencyPair=BTC/USD, open=9181.52, last=9276.56, bid=9276.57, ask=9279.00, high=9328.09, low=8974.62,avg=9145.61, volume=11782.53647669, quoteVolume=null, timestamp=1525877215000, bidSize=null, askSize=null]
BitstampTicker [open=9181.52, …
```
> [bitstamp] bug fix of null open ticker values

- xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexExchange.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeService.java
Poloniex does not support market orders directly, but will instantly fill limit orders with very low or high prices. So this is implementation has  the same effect as a market order. Poloniex has maximums for each 'rate' (limit price) but does not provide them. So this method must find the current market price and make the limit order guaranteed to be filled instantly.
> [Poloniex] implement market order

- xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java
Cex order status conversion didn't evaluate status field returned from rest service. With this patch is available a better algorithm that consider status field and amounts.
> [CexIO] improved adaptOrderStatus

- xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaAccountService.java
- xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaAccountServiceRaw.java
Transform CryptopiaFundingHistoryParams into a standard TradeHistory implementation :
- Remove use of specific "Deposit / Withdraw" enum inside the classs ( prefer adapt on getFundingHistory method)
- Rename "count" to "limit"
- Add HistoryParamsFundingType, TradeHistoryParamLimit interfaces (useful for instanceof testing)
- Set the hard writed 100 limit into a static field
- Change the default Type value from Deposit to null ( Deposits and Withdraws )
> [cryptopia] Set HistoryParamsFundingType, TradeHistoryParamLimit interfaces to CryptopiaFundingHistoryParams

- xchange-liqui/src/main/java/org/knowm/xchange/liqui/service/LiquiTradeService.java
- xchange-liqui/src/main/java/org/knowm/xchange/liqui/service/LiquiTradeServiceRaw.java
- Use a respectful default class of trade history params (LiquiTradeHistoryParams) with no currency pair ( avoid loop by default )
- Fix an error on LiquiTradeServiceRaw getTradeHistory method ( don't get the CurrencyPair in case of CurrencyPair )
- Remove unused multiples getTradeHistory methods in LiquiTradeServiceRaw ( should not be used somewhere else than LiquiTradeService )
> [Liqui.io] Fix CurrencyPair not fetched on TradeService

- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java
- xchange-livecoin/src/test/java/org/knowm/xchange/livecoin/LivecoinAdaptersTest.java
Livecoin has a currency `Bricktox (XBT)` which is different from `XChange` `Bitcoin (XBT)`.
The `Get All Currencies` call to `Livecoin` returns all currencies including those with 0 balance.
As a result, `XBT`overrides `BTC`, so `BTC` becomes 0 (in most cases). Even if we manage to work around the problem of `Overriding BTC by XBT`, we will still parse `XBT` as `Currency.XBT`, which is `Bitcoin`, which would be different from what `Livecoin` refers to.
This PR contains [LivecoinAdaptersTest](https://github.com/knowm/XChange/pull/2605/files#diff-ecac3431b8f2d8fa6386a4b48b27eddd) which reveals the problem.
This PR is about **excluding XBT** in `Livecoin` client.
Also, this PR contains minor improvement: removed redundant map.put when element is already in the map.
> [Livecoin] Exclude currency Bricktox(XBT)

- xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexioCancelReplaceOrderRequest.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOCancelReplaceOrderResponse.java
- xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java
Implement cex.io specific function, that allows to cancel and place an order with a single command.
> [Cex.io] Add `cancel_replace_order` to private implementation

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
ZenCash is becoming increasingly popular and is available on an already impressive and growing number of exchanges. We want to use this XChange package in our own projects, and this PR gives us that option.
> Add ZenCash currency pairs

- xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOArchivedOrder.java
Remove base/counter price calculation, use API-supplied price instead.
> Fix filled.get(counter)==NULL when adapting a cancelled order.

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
The Kraken error "invalid amount" was mapped to "FundsExceeded" - which is not correct. Invalid amount refers to the precision of the price.
> [Kraken] Fix for "invalid amount" error mapping to "FundsExceeded"

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexPrivateOrder.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/trade/BitmexOrderStatus.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
Querying order history fails if it contains rejected orders.
> [bitmex] Add REJECTED order status to adapter.

- xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiAdapters.java
- xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiTradeServiceRaw.java
Provide an average price for the trading of huobi
Market orders for huobi require an account id parameter
The original amount precision in huobi must be less than 4
> Fixed some issues of the huobi market

- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/CoinMarketCap.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/dto/marketdata/CoinMarketCapArrayData.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/dto/marketdata/CoinMarketCapQuote.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/dto/marketdata/CoinMarketCapTicker.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/service/CoinMarketCapMarketDataService.java
- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/service/CoinMarketCapMarketDataServiceRaw.java
- xchange-coinmarketcap/src/test/java/org/knowm/xchange/coinmarketcap/dto/marketdata/CoinMarketCapMarketDataJsonTest.java
- xchange-coinmarketcap/src/test/java/org/knowm/xchange/coinmarketcap/service/marketdata/TickerFetchIntegration.java
- xchange-coinmarketcap/src/test/resources/org/knowm/xchange/coinmarketcap/dto/marketdata/example-ticker-data-v2.json
This modification/update was the result of the need for the 'convert' parameter in `/ticker`. While checking out the code, I realized that I had to update the API, too. So here it is. 
All CoinMarketCap tests pass and I have added a test JSON file for the new version.
Some code might not be optimal (but should be functional) because I haven't ever used jax-rs stuff or Jackson more extensively.
> Updated CoinMarketCap API to version 2 and added support for convert parameter

- xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaMarketDataService.java
Other implementation use Integer as first arguments.
This add support for Integer argument.
> Cryptopia: Improve consistency with other implementations of getOrderBook

- xchange-examples/src/main/java/org/knowm/xchange/examples/gateio/trade/GateioTradeDemo.java
- xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAuthenticated.java
- xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioTradeService.java
- xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioTradeServiceRaw.java
cancelOrder(String orderId) is not supported by the API, cancelOrder(CancelOrderParams orderParams) must be used with GateioCancelOrderParams as the implementation of CancelOrderParams.
> [Gate.io] Fixed cancelOrder

- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountService.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountServiceTest.java
As per the btcmarkets API page, the withdraw funds page returns a fixed string 'Pending Authorization'.
```
{"success":true,"errorCode":null,"errorMessage":null,"status":"Pending Authorization"}
```
This does not conform to the API's return type which expects the method to return a transaction ID that might be used later on.
The lack of a usable return value has been raised with BTCMarkets in the following issue https://github.com/BTCMarkets/API/issues/137 but this has not been addressed.
> [btcmarkets] - Changed withdrawFunds to return null 

- xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerAdapters.java
- xchange-bitflyer/src/test/java/org/knowm/xchange/bitflyer/service/BitflyerTickerIntegration.java
The last traded price for the Bitflyer ticker is null, even though it is present in the returned ticker data.
> Fix Bitflyer last traded price

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountService.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java
library creates request with double slash in the end: https://dev-publicapi.cryptonit.net/api/v2/user_transactions//
So Bitstamp understands this request like try to get trading pair related transactions but not funding history and throws error: {"status":"error","reason":{"MARKET_UNKNOWN":[]}}"; line: 1, column: 1]
Solution is to use implementation of web service call without currencyPair parameter,
> Issue #2703. Bitstamp Funding request bug fix

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataService.java
It's currently useless for XChange, but helpful in xchange-stream project
> Extracted Binance order book convertion method.

- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/Coindirect.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/CoindirectAdapters.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/CoindirectAuthenticated.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/CoindirectExchange.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/dto/account/CoindirectAccountChannel.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/service/CoindirectAccountServiceRaw.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/service/CoindirectMarketDataService.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/service/CoindirectMarketDataServiceRaw.java
- xchange-coindirect/src/main/java/org/knowm/xchange/coindirect/service/CoindirectTradeServiceRaw.java
Apologies for this, access of *Raw constructors was incorrect, need this for the xchange-stream implementation.
> [coindirect] fixed incorrect access of raw constructors + path tweaks

- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/DefaultOpenOrdersParam.java
- xchange-liqui/src/main/java/org/knowm/xchange/liqui/LiquiAdapters.java
- xchange-liqui/src/main/java/org/knowm/xchange/liqui/dto/trade/LiquiOrderInfo.java
Fix for https://github.com/knowm/XChange/issues/2727:
[Liqui] Fixed retrieved order amounts 
[core] Added cumulativeAmount in LimitOrder "from" builder
> [Liqui] Fixed retrieved order amounts

- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataService.java
This PR only connects functionality that was already there to the previously unimplemented method getTickers().
> Implement getTickers() for HitBTC.

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
- xchange-bitmex/src/test/java/org/knowm/xchange/bitmex/service/BitmexBulkOrderTest.java
This Pull Request adds support for linked orders on Bitmex by adding the parameters `clOrdLinkID` and `contingencyType` to limit, stop and bulk orders.
> Bitmex: Add support for linked orders

- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/dto/trade/BTCMarketsPlaceOrderResponse.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsTradeServiceTest.java
Increasing the size of the Id field on the placeOrder return, matching the current API returned values.
> [btcmarkets] - Changed type of BTCMarketsPlaceOrderResponse.id from Int to Long matching API return values

- xchange-bx/src/main/java/org/knowm/xchange/bx/service/BxTradeService.java
- xchange-bx/src/main/java/org/knowm/xchange/bx/service/BxTradeServiceRaw.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/CancelOrderByPairAndIdParams.java
Add new `org.knowm.xchange.service.trade.params.CancelOrderByPairAndIdParams`
cancel parameter type to cancel order using instrument and order id;
Use CancelOrderByPairAndIdParams for bx.in.
> [bx.in] Add required by exchange instrument parameter at order cancel

- xchange-quadrigacx/src/main/java/org/knowm/xchange/quadrigacx/QuadrigaCxAdapters.java
Very annoying warning after fetching the account info by quadrigacx:
```
10:15:57.052 [main] WARN  o.knowm.xchange.dto.account.Balance - 7404.59 = total != available + frozen - borrowed + loaned + withdrawing + depositing = 7404.58
```
just spent a couple of minutes to find out, why. Quadriga serves the account balancings wrong in the last digit sometimes, i.e. this is a reply, i get
```
"usd_available":"7225.11","usd_reserved":"179.47","usd_balance":"7404.59"
```
we get deservedly the warning. To get rid of this behaviour, one can simply ignore the xxx_reserved amounts.
> [quadrigacx] ignore the reserved balance, since its wrong in the last digit sometimes

- xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioAccountServiceRaw.java
- xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioHmacPostBodyDigest.java
see https://support.gate.io/hc/en-us/articles/360000808354-How-to-Withdraw-XRP
> [gate.io] fixed the withdraw method, where a tag is passed (i.e. for XLM, XRP)

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexException.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java
- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/CancelAllOrders.java
Add `org.knowm.xchange.service.trade.params.CancelAllOrders` parameter type to use to cancel all orders;
Use CancelAllOrders parameter type to cancel all limit orders;
Optimize opened orders receiving - instead of receiving all order and filter, request exchange to return the opened orders only;
Fix quantity silent trimming to int at order placing by making `orderQuantity` as BigDecimal;
Fix the wrong format of BitmexException;
> [Bitmex] Refactoring and optimisation

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticated.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampOrder.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java
Bitstamp orders have exceeded [Integer.MAX_VALUE](https://docs.oracle.com/javase/7/docs/api/constant-values.html#java.lang.Integer.MAX_VALUE) leading to 
``` java
Caused by: org.knowm.xchange.bitstamp.dto.BitstampException: null (HTTP status code: 200)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_151]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_151]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.9.2.jar!/:2.9.2]
at …
```
> [bitstamp] Fix: order ids have exceeded integer max value. Changed to longs

- xchange-bx/src/main/java/org/knowm/xchange/bx/BxAdapters.java
- xchange-bx/src/main/java/org/knowm/xchange/bx/dto/marketdata/BxTicker.java
- xchange-bx/src/main/java/org/knowm/xchange/bx/service/BxMarketDataServiceRaw.java
- xchange-bx/src/test/java/org/knowm/xchange/bx/BxPublicApiIntegration.java
Remove extra request to /api/tradehistory/ to get open, high, low, avg,  volume from the exchange. This data was nice to have, but additional request removal helps to reduce traffic between exchange.
> [Bx.in] Remove extra request to history for each ticker request

- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/DefaultQueryOrderParamCurrencyPair.java
- xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeService.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/KucoinAdapters.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/trading/KucoinOrderDetail.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/trading/KucoinOrderQueryParams.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/KucoinTradeService.java
Hitbtc requires currency pair to be passed when getting order, it means that getOrder(String... ids) method can't be used here. Changed this to a QueryOrderParams version. Also added DefaultQueryOrderParamCurrencyPair implementation to the core.
> [Hitbtc] changed incorrect getOrder method with only string ids as params to QueryOrderParams version

- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountService.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountServiceTest.java
Added support for RippleWithdrawFundsParams in the BTCMarkets withdrawal code.
> BTCMarkets - Added support for RippleWithdrawFundsParams

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenExchange.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
Allows new assets to be dynamically loaded when creating a new KrakenExchange instance or performing a remoteInit. Currently assets can only be loaded once during initial kraken exchange initialization.
> Clear Kraken assets and assetPairs during a remote init. 

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/test/java/org/knowm/xchange/CurrencyTest.java
See attached testcase , Currencies.XBT.toString() should not return BTC, since various implementations use toString to determine the currency code that gets send to the exchange.
> [core] - Reverted changes to currency class and added test to validate toString behaviour

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
- xchange-bitfinex/src/main/resources/bitfinex.json
Remove deprecated workaround with pair renaming: DASH <=> DSH, QTUM <=> QTM.
> [Bitfinex] Remove deprecated workaround for DSH and QTM

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexNewOrderRequest.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexMarketDataServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java
Add cancel all;
Parse exceptions raised for exchange symbols and symbols details requests;
Use BigDecimal instead of String for order amount and price;
Move order flags conversion into adapter class.
Remove unused `adaptCurrencyPairs`.
> [Bitfinex] Add cancel all. Cleanup and refactoring

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
New Bitcoin and Altcoin Quarterly Futures Contracts
December 13, 5:29 AM
On 17th December 2018, the March 2019 quarterly ADA, BCH, EOS, ETH, LTC, TRX, and XRP futures contracts will be listed:
BitMEX Cardano / Bitcoin 29 March 2019 futures contract (ADAH19)
BitMEX Bitcoin Cash / Bitcoin 29 March 2019 futures contract (BCHH19)
BitMEX EOS Token / Bitcoin 29 March 2019 futures contract (EOSH19)
BitMEX Ether / Bitcoin 29 March 2019 futures contract (ETHH19)
BitMEX Litecoin / Bitcoin 29 March 2019 futures contract (LTCH19)
BitMEX Tron / Bitcoin 29 March 2019 futures contract (TRXH19)
BitMEX Ripple / Bitcoin 29 March 2019 futures contract (XRPH19)
On the same date, the June 2019 quarterly BTC futures contract will be listed:
BitMEX BTC / USD 28 June 2019 futures contract (XBTM19)
> [Bitmex] added new Altcoin Quarterly Futures Base

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
The Binance API guide states that it should be omitted. This is moot since I haven't found any pairs where such orders are actually allowed, but at least this means if Binance adds the support for such orders, XChange will be ready.
> [binance] Don't set time-in-force for stop orders with no limit price.

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java
The implementation of `placeStopOrder` is harmless enough; I've just aliased the previous very bitfinex-specific flag-based method of submitting stop orders with the newer API based on `StopOrder`.
However, the change to `getOrders` is a breaking change. It brings Bitfinex in line with Coinbase Pro and Binance in that stop orders are returned in the "hidden orders" side of `OpenOrders` rather than the limit orders side, thus existing code will have to change to pick up stop orders.  My intention is to also do this for some other exchanges and standardise on it.
I have considered the possibility of a feature toggle allowing the behaviour to be reverted to the old behaviour for existing users.  Please let me know if that would be useful, and if so, the most consistent way to implement it.
> [bitfinex] add placeStopOrder support, consistent getOrders behaviour with other exchanges

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
Divide by 100 000 000 to get BTC instead of satoshis amount
> [Bitmex] Add missing amount correction 

- xchange-btcturk/src/main/java/org/knowm/xchange/btcturk/BTCTurkExchange.java
- xchange-btcturk/src/test/java/org/knowm/xchange/btcturk/service/account/AccountDataFetchIntegrationTest.java
- xchange-btcturk/src/test/java/org/knowm/xchange/btcturk/service/trade/TradeDataFetchIntegrationTest.java
If the api key is defined after running "ExchangeFactory.INSTANCE.createExchange" command, authenticated services were null.
> Fixed NULL Error for Authenticated Services

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAdapters.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/trade/BittrexOpenOrder.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/trade/BittrexOrder.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/trade/BittrexOrderBase.java
- xchange-bittrex/src/test/java/org/knowm/xchange/bittrex/BittrexAdaptersTest.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
Bittrex: fixed BigDecimal calculation with now possible null values, due to Bittrex 02/27/2019 backend update
Kraken: fixed null pointer exception cases on not supported currency pairs
> [Bittrex-Kraken] various fixes

- xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/pro/v1/CmcExchange.java
- xchange-coinmarketcap/src/main/resources/CoinMarketCap.json
This is a follow-up fix to #2900 which was already implemented and merged in the PR #2944. 
The implementation in #2944 worked perfecty for me in the Xchange unit tests, but failed with "missing api-key" errors when used in my own project.
After investigating the difference I found that the order of initialization was the problem:
The `marketDataService` (and therefore the CmcBaseService) gets created within in the `initServices()` method, which was called directly from the constructor as can be seen here: [CmcExchange.java#L18](https://github.com/jakubkalicki/XChange/blob/da615747aecd1462e8a9358285779fc8ed5751b8/xchange-coinmarketcap/src/main/java/org/knowm/xchange/coinmarketcap/pro/v1/CmcExchange.java#L18)
As the `applySpecification(..)` method (where the ExchangeSpecification and the …
> [CoinMarketCap] Fix initialization (API key was not initalized)

- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/dto/CobinhoodAdapters.java
Hi,
i noticed that there is a problem in orderbook: limit orders have amount with "count" value returned from cobinhood api instead of "volume" value.
It is an index mistake, you can find more information here: https://cobinhood.github.io/api-public/?http#get-orderbook
Cobinhood orderbook orders are returned with these value: price, count, volume.
Thank you
> [Cobinhood] fix order amount in orderbook

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
In some cases there is a leading space on Bitfinex transactions, this simple patch just removes them.
> [bitfinex] fixed leading space when extracting tx hash

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/Kraken.java
Ensures that `SocketTimeoutException` and similar exceptions are propagated unwrapped.
> [kraken] Fix UndeclaredThrowableException when fetching tickers

- xchange-wex/src/main/java/org/knowm/xchange/wex/v3/service/WexMarketDataService.java
The javadoc says the method expects an Integer, not a Number.
> Fixed the type operand of 'instanceof'.

- xchange-dragonex/src/main/java/org/knowm/xchange/dragonex/Dragonex.java
- xchange-dragonex/src/main/java/org/knowm/xchange/dragonex/dto/marketdata/Depth.java
- xchange-dragonex/src/main/java/org/knowm/xchange/dragonex/service/DragonexMarketDataService.java
- xchange-dragonex/src/main/java/org/knowm/xchange/dragonex/service/DragonexMarketDataServiceRaw.java
- added new 'depth' method to fetch the order book
- additionally added the "count" parameter, so we can fetch 50 orders (default is 10)
> [dragonex] added new 'depth' method to fetch the order book

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticatedV2.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountService.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeHistoryParams.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java
This will make it possible to fetch historic trades based on unix timestamp. Setting a startTime on a TradeHistoryParamsTimeSpan will fetch all UserTrades since that time, inclusive. The resolution is seconds and any milliseconds will be truncated from the timestamp before sending the request.
> Bitstamp: Support for since_timestamp for user_transactions

- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java
- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinErrorAdapter.java
- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrder.java
- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrderBook.java
- xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrdersDeserializer.java
- xchange-livecoin/src/test/java/org/knowm/xchange/livecoin/service/MarketDataIntegration.java
Livecoin added a third value to their order book entries which broke the current parsing mechanism - it was returning empty order books.
```
{
"timestamp": 1553777858097,
"asks": [
[
"0.03430012",
"0.01498781",
1553777852095
],
[
"0.03430013",
"0.00478876",
1553777849476
],
```
I've implemented parsing of these type of arrays in a more proper way
> [livecoin] orderbooks parsing fix

- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java
Kucoin symbol is an optional parameter for most methods, this should be supported by passing null as CurrencyPair
> [kucoin] CurrencyPair is nullable

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
- xchange-bleutrade/src/test/java/org/knowm/xchange/bleutrade/BleutradeTestData.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyPairMetaData.java
Add the amount step size to `CurrencyPairMetadata`. On Binance, for each currency pair, all trade amounts have to be a multiple of the specified amount otherwise you get a `LOT_SIZE` filter error on placing an order.
I'm assuming Binance can't be the only exchange with this sort of behaviour, so have added it to the core API.
> [binance] Add step size to metadata

- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParamCurrencyPair.java
support null values for currency pair inside OpenOrdersParamCurrencyPair class
> [core] support null values for currency pair

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexOrderType.java
Also report unhandled order types in the future and warn where the data returned won't be accurate.
This code really needs to be moved to the v2 API which fully supports all order types.
> [bitfinex] Fix NPE when fetching open stop-limit orders

- xchange-bleutrade/src/test/java/org/knowm/xchange/bleutrade/BleutradeTestData.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyPairMetaData.java
- xchange-core/src/test/java/org/knowm/xchange/dto/meta/ExchangeMetaDataTest.java
- xchange-core/src/test/resources/org/knowm/xchange/core/meta/exchange-metadata.json
This is a relatively small PR to address one of the issues raised in https://github.com/knowm/XChange/issues/1544 , it adds a new field `tradingFeeCurrency` to the CurrencyPairMetaData class. 
Future changes can leverage this to better calculate and present fee's to the client even if not returned by the API.
I have not gone through all the exchanges to populate the metadata but am happy to cover some exchanges if this PR gets merged. We could add a default mechanism to always fallback to the counter but that might give users a false sense of quality so i did not do that as part of this PR.
> [core] - Added support for tradingFeeCurrency to CurrencyPairMetaData

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
- xchange-binance/src/test/java/org/knowm/xchange/test/binance/AccountServiceIntegration.java
As described in #3073, the meta data for certain currencies and currency pairs such as IOTX/BTC is not correctly stored and retrieved for Binance. 
The root cause of this problem is in the initialization routine for Binance.  
Within the `remoteInit()` method in `BinanceExchange.java` we find the following code:
```Symbol[] symbols = exchangeInfo.getSymbols();
for (BinancePrice price : marketDataService.tickerAllPrices()) {
CurrencyPair pair = price.getCurrencyPair();
for (Symbol symbol : symbols) {
if (symbol
.getSymbol()
.equals(pair.base.getCurrencyCode() + pair.counter.getCurrencyCode())) {
```
Interestingly, this routine combines two for-loops while only one is necessary since you want to iterate just once over the currency pairs. Additionally, we see two ways of receiving the …
> [Binance] Fix for wrong information for some currencies and currency pairs in meta data

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexDeposit.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexWithdrawal.java
- xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/PoloniexAdapterTest.java
- xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/dto/account/PoloniexFundingsDataTest.java
- xchange-poloniex/src/test/resources/org/knowm/xchange/poloniex/dto/account/deposits-withdrawals.json
Withdrawal from Poloniex have Field "fee" which was missing in the DTO.
While fixing that I also added the field "paymentID" in PloniexWithdrawal and the fields "depositNumber" and "category" in PoloniexDeposit
> [poloniex] Adding missing fields and tests for AccountService.getFundingHistory

- xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerAdapters.java
- xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerUtils.java
Bitflyer sometimes sends dates with a millisecond `.SSS` on the end and sometimes without. This change detects the dot and selects the appropriate `SimpleDateFormat` to match both date variants as necessary.
> [bitflyer] more forgiving date parsing

- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/CoinbeneBigDecimalDeserializer.java
- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/dto/CoinbeneAdapters.java
- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/dto/marketdata/CoinbeneTicker.java
- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/service/CoinbeneMarketDataService.java
- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/service/CoinbeneMarketDataServiceRaw.java
- Added API call to retrieve all tickers from Coinbene XChange, as documented [here](https://github.com/Coinbene/API-Documents/wiki/1.1.0-Get-Ticker-[Market])
- Created custom BigDecimal deserializer for "bid" and "ask" values of a ticker, in order to handle the "--" string case
> Coinbene Tickers API and Custom BigDecimal Deserializer

- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/Cobinhood.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/CobinhoodAdapters.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/CobinhoodExchange.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/dto/marketdata/CobinhoodCurrencyPair.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/dto/marketdata/CobinhoodTradingPairs.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/service/CobinhoodMarketDataService.java
- xchange-cobinhood/src/main/java/org/knowm/xchange/cobinhood/service/CobinhoodMarketDataServiceRaw.java
- xchange-cobinhood/src/test/java/org/knowm/xchange/cobinhood/service/dto/CobinhoodMarketDataDtoTest.java
- xchange-cobinhood/src/test/resources/org/knowm/xchange/cobinhood/dto/currencypair-example.json
- Implemented remote Metadata retrieval for Cobinhood Exchange
- Added trading_pairs API call to get the list of currency pairs
- Fixed the CobinhoodCurrencyPair DTO to align it with the structure of the API response
- Fixed test according to modifications of CobinhoodCurrencyPair DTO
> Added tradingPairs and remoteInit to Cobinhood exchange

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
The function getTradeHistory(TradeHistoryParams params) in KrakenTradeService sorts the trades by ID. However, the ids in Kraken have no natural order so the trade history should be sorted by timestamp as default. The ids have the format of A-B-C which A, B, C being strings. I believe they refer to individual ledger entries in Kraken.
Fixes issue #3126.
> [Kraken] Changed deafult sorting to timestamps rather than ids

- xchange-binance/src/main/java/org/knowm/xchange/binance/Binance.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataService.java
- Implemented missing API call to retrieve all book tickers from Binance
- Since the base getTickers() function has been implemented yet and returns the 24h tickers data, a new method getAllBookTickers() has been implemented
- In order to call it, it is necessary to explicitly cast a generic MarketDataService instance to a more specific BinanceMarketDataService first
> [Binance] added allBookTickers API call

- xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/dto/CoinbeneAdapters.java
Added more metadata to CurrencyPairMetaData structure for Coinbene exchange, inside the CoinbeneAdapters class. Data are taken from the API call http://api.coinbene.com/v1/market/symbol
> [Coinbene] Added metadata to currency pairs

- xchange-coinmate/src/main/resources/coinmate.json
Core validation of  XChange lib (verifyOrder) get scale from minimum amount:
Class: org.knowm.xchange.service.BaseExchangeService:
`
BigDecimal minimumAmount = metaData.getMinimumAmount();
if (minimumAmount != null) {
if (amount.scale() > minimumAmount.scale()) {
throw new IllegalArgumentException("Unsupported amount scale " + amount.scale());
....
`
So coinmate.json min_amount cannot be: 0.0002 (scale = 4) but 0.00020000 (scale = 8) 
Example configuration of Bitstamp:
`
"BTC/EUR": {
"price_scale": 2,
"trading_fee": 0.0025,
"min_amount": 0.00085000
}
`
> [Coinmate] fix - coinmate.json configuration

- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/MarketOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/StopOrder.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/LimitOrderTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/MarketOrderTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/StopOrderTest.java
Fix order builders:
- missing fee/cumulativeAmount copy in Builder.from methods
- MarketOrder.fee method was setting cumulativeAmount instead of fee
- missing javadoc
- missing tests
> [Core] Fix order DTO builders

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
- xchange-core/src/main/java/org/knowm/xchange/dto/LoanOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/AccountInfo.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/Balance.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/Fee.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/FundingRecord.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/Wallet.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/LoanOrderBook.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBookUpdate.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Ticker.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trade.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trades.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyMetaData.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyPairMetaData.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/ExchangeMetaData.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/FeeTier.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/RateLimit.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/FixedRateLoanOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/FloatingRateLoanOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/MarketOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/OpenLoanOrders.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/OpenOrders.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/StopOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrade.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrades.java
In order to improve serialization portability across different versions of the library, explicit serialVersionUID has been added to all currency and dto objects in xchange-core module
> Added serialVersionUID to serializable dto objects

- xchange-bleutrade/src/test/java/org/knowm/xchange/bleutrade/BleutradeExchangeIntegration.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/BTCMarketsExchangeTest.java
- xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java
The input exchange spec name was used here instead of the member initialized in the above code and checked before executing this read. This bug was causing crashes during the initialization of the cexio streaming exchange in the xchange-stream project.
> Fix bug where a potentially null exchange spec was read

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexAdjustment.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexDepositsWithdrawalsResponse.java
- xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/PoloniexAdapterTest.java
- xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/dto/account/PoloniexFundingsDataTest.java
- xchange-poloniex/src/test/resources/org/knowm/xchange/poloniex/dto/account/deposits-withdrawals.json
Added new Type PoloniexAdjustment to the PoloniexDepositsWithrawalsResponse-Object and changed adapter to convert it to a Deposit-FundingRecord
API mothod for AccountService.getFundingHistory returns an additional type named Adjustment, which can be airdrops other other forms of "gifted" funds:
[Documentation](https://docs.poloniex.com/#returndepositswithdrawals)
This commit adds the new Type to the PoloniexDepositsWithdrawalsResponse and proposes a non-invasive way to adapt it to a Deposit-FundingRecord. It (miss)uses the description field to place all the extra information until there is a better solution to handle this kind of deposit variation.
>  [poloniex] Added new Transfer-Object: PoloniexAdjustment

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java
This stepSize works only for XBT/USD pair. I am sorry for this mistake on the implementation.
> [Bitmex] Reverting back stepSize on bitmex placeOrder

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
- xchange-tradeogre/pom.xml
There is an issue when adaptOrder method formats timestamp if timestamp lenght is bigger or equal to 13. Kraken's REST orderbook.timestamp property lenght is 8 but Kraken's Websocket orderbook.timestamp lenght is 13. This creates incorrect Dates when you parse timestamp from Kraken's websocket endpoint.This fix, fixes that issue.
> [Kraken] Fixing adaptOrder timestamp issue for Kraken's websocket orderbook

- xchange-bitbay/src/main/resources/bitbay.json
Added missing GBP markets for Bitbay metadata: https://bitbay.net/en
> Added GBP markets for Bitbay

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeHistoryParams.java
[Binance]
- Add startTime and endTime fields for TradeHistoryParam.
- Fix AddressWithTag sometimes  returns empty destination tag instead of null.
> [Binance] Add timespan fields to BinanceTradeHistoryParams

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/KrakenAdaptersTest.java
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/trading/example-tradehistory-icn.json
The xchange library currently throws an NullPointerException when downloading historic trades from Kraken for my account because it can't handle a trade with trading pair "XICNXXBT":
```
Exception in thread "main" java.lang.NullPointerException
at org.knowm.xchange.kraken.KrakenAdapters.adaptTrade(KrakenAdapters.java:283)
at org.knowm.xchange.kraken.KrakenAdapters.adaptTradesHistory(KrakenAdapters.java:259)
at org.knowm.xchange.kraken.service.KrakenTradeService.getTradeHistory(KrakenTradeService.java:93)
```
This change fixes that. Probably this also closes #1826.
> Fix handling of unknown 5-letter currencies in Kraken

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/account/LedgerType.java
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-ledgerinfo-data.json
ICN was discontinued by kraken in Feb 2019. This gave two "adjustment" ledger entries (removing the ICN and adding some ETH), which crash xchange at this moment.
> [kraken] Fix handling of ICN ledger entries

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexTradeService.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexTradeServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexHmacSignature.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/trade/Trade.java
A bugfix was necessary because the adapt CurrencyPair method was using the format for API V2 and the getBitfinexTrades Methode was using the API V1
The current version get all Trades via V2.
> [bitfinex] Bugfix getTradeHistory

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAdapters.java
- xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v1/BitfinexAdaptersTest.java
- xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v2/BitfinexAdaptersTest.java
Was not working correctly for example for TKN/USD
> Fix string to currency pair conversion when base name starts with "t"

- xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/Balance.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trade.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/MarketOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/StopOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrade.java
- xchange-core/src/main/java/org/knowm/xchange/utils/ObjectMapperHelper.java
- xchange-core/src/test/java/org/knowm/xchange/dto/account/BalanceTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/LimitOrderTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/trade/UserTradeTest.java
Previously it allowed deserialization not to work when new properties were added.
Fixed a number of broken properties.
> Make testing for JSON serialization/deserialization stricter

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/account/LedgerType.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/dto/account/KrakenAccountJSONTest.java
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-ledgerinfo-data.json
Kraken has another ledger type "settled" which is absent in documentation but exists in API and csv
> Add ledger type settled to Kraken ledger

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceErrorAdapter.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/BinanceErrorAdapterTest.java
Fixed bug introduced in https://github.com/knowm/XChange/pull/3299.
It was introduced in 4.4.2-SNAPSHOT, so it was not released.
Bug description:
For error code -1013 from Binance was returned ExchangeUnavailableException instead of OrderAmountUnderMinimumException or OrderNotValidException.
Fixed in this PR.
> Fixed bug in BinanceErrorAdapter

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeServiceRaw.java
So that it hopefully comes back on the webSocket.
NB: Kraken userReference is a 32-integer stuffed in a string
> [Kraken] send userReference to the exchange

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
I am guessing Order.userReference got added later, and this may need to be done for each exchange
> [Kraken] adaptOrder - do not ignore userRefId()

- xchange-bibox/pom.xml
lombok dependency scope must be "provided", which is actually set correctly in the [root pom.xml](https://github.com/knowm/XChange/blob/develop/pom.xml#L316)
otherwise the lombok dependency is propagated and added to final artifacts, which is "_not necessary_"
> [bibox] lombok dependency scope

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexTradeServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/trade/OrderTrade.java
Change to support bitfinex v2 call - https://docs.bitfinex.com/reference#rest-auth-order-trades
> Issue 3403 - Introduce support for Bitfinex V2 API get order trades

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java
Binance started to return new deposit status, please check the docs: https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data
Without this fix requesting deposit history fails with RuntimeException("Unknown binance deposit status: 6") while BTC deposit has just 1 confirmation.
> [Binance] handle new deposit status "6: credited but cannot withdraw"

- xchange-core/src/main/java/org/knowm/xchange/utils/DateUtils.java
- xchange-core/src/main/java/org/knowm/xchange/utils/jackson/SqlUtcTimeDeserializer.java
- xchange-itbit/src/main/java/org/knowm/xchange/itbit/ItBitDateDeserializer.java
DateUtils throws an com.fasterxml.jackson.databind.exc.InvalidFormatException, but is using a deprecated constructor that doesn't require a JSONParser. This PR simply passes in null to remove the warning and keep the API from using deprecated methods.
> Remove warnings from not passing in a JSON Parser to the exception

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAdapters.java
"BitfinexAdapters - Unexpected market order on book. Defaulting to limit order"
I sent in a market order via XStream and got a dozen these warnings.  Two proposals:
a) this patch
b) just remove the warning at line 503
this is probably because XStream is also using this adaptOrders function when getting updates on the socket
Personally, I prefer this patch, as it extends the functionality of adaptOrders
> [bitfinex] Unexpected market order on book

- xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin/trade/KucoinTradeHistoryDemo.java
- xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin/trade/KucoinTradeRawDemo.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinBaseService.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinTradeHistoryParams.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinTradeService.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinTradeServiceRaw.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/HistOrdersResponse.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/HistOrdersAPI.java
KuCoin changed their system/API on 28th Feb 2019 and trades executed before that date do not show up in the regular trade history.
This fix automatically uses the **hist-orders** API endpoint when a date range before the 28th Feb 2019 is specified and the **fills** endpoint for dates after in tradeService.getTradeHistory(...) calls. It also checks if the date range specified complies with KuCoin API restrictions and adjusts if necessary.
Fixes #3377
> [KuCoin] Enable trade history queries before 28th Feb 2019 (using old API endpoint)

- xchange-coinegg/src/main/java/org/knowm/xchange/coinegg/CoinEgg.java
- xchange-coinegg/src/main/java/org/knowm/xchange/coinegg/service/CoinEggMarketDataService.java
- xchange-coinegg/src/main/java/org/knowm/xchange/coinegg/service/CoinEggMarketDataServiceRaw.java
- xchange-coinegg/src/test/java/org/knowm/xchange/coinegg/service/marketdata/CoinEggOrdersFetchIntegration.java
The specification for CoinEgg REST service defines that the request URI should specify the region, or in fact the counter currency. The current implementation omits the region part of the URI, thus working only for */BTC pairs.
This pull request adds the necessary part of the URI path and also provides a test to verify that it's working.
> [CoinEgg] Fix region when requesting market depth

- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java
- xchange-core/src/test/java/org/knowm/xchange/OrderBookTest.java
The contract for market updates (order books) specifies that when the amount for a given limit price is 0 (zero), then this bid/ask has been fulfilled and has to be removed from the order book. 
This is implemented in the `update(List<LimitOrder> asks, LimitOrder limitOrder)` and `update(OrderBookUpdate orderBookUpdate)` methods, but not in the `update(LimitOrder limitOrder)` method. The latter is not used at all in the project and there are no test cases for it. I assume that's the reason the issue was not caught earlier.
Also added a new test case to verify.
> Fix remove a single order from the order book

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
The return value of reason seems to have changed to "airdrop_generic". These modifications should be able to handle old and current reason values.
The Adaptor also uses now the new `FundingRecord.Type OTHER_INFLOW` as adujstmends are no `DEPOSIT`s
> [poloniex] Fixed Adapter due to changed return value from poloniex

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
It started returning "Signature for this request is not valid" for some reason. The documentation says "Note that for wapi, parameters must be sent in query strings." in the signed endpoint examples section: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md
Fixes #3495
> [binance] fix withdrawal

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/Status.java
- xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexStatusJSONTest.java
Extended the Status bean to handle additional fields:
- MARK_PRICE
- OPEN_INTEREST
> [bitfinex] extended status for derivatives pairs

- xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
Ping is triggered on open websocket when idle time is reached. Idle time is defaulted to 15 seconds, this is required to trigger ` protected void handleIdle(ChannelHandlerContext ctx)`.
> Websocket ping on idle + default idle time

- xchange-simulated/src/main/java/org/knowm/xchange/simulated/MatchingEngine.java
- xchange-simulated/src/main/java/org/knowm/xchange/simulated/MatchingEngineFactory.java
- xchange-simulated/src/main/java/org/knowm/xchange/simulated/SimulatedExchange.java
- xchange-simulated/src/main/java/org/knowm/xchange/simulated/SimulatedTradeService.java
- xchange-simulated/src/test/java/org/knowm/xchange/simulated/TestSimulatedExchange.java
Implemented additional functions on the Simulated exchange to allow getOder and cancel calls without passing in the currency pairs.
> [simulated] - Implemented additional cancel/getOrder functions 

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexUtils.java
- xchange-bittrex/src/test/java/org/knowm/xchange/bittrex/BittrexUtilsTest.java
Bittrex reversed the market names order with version 3
> [Bittrex] Deprecated methods with confusing names

- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/CoinbaseProTrades.java
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java
Coinbase pro have changed the case of their http response headers relating to pagination.
Calls to private endpoints to collect trades or funding history/ledgers currently fails (leads to NPE).
Issue https://github.com/knowm/XChange/issues/3579
> CoinbasePro - Updated header names, correct the case

- xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/BitmexStreamingService.java
See following announcement: https://blog.bitmex.com/api_announcement/deprecation-of-api-nonce-header/
> [BitMex Stream]: Remove nonce from BitMex stream as its now deprecated

- xchange-core/src/main/java/org/knowm/xchange/Exchange.java
- xchange-core/src/main/java/org/knowm/xchange/derivative/Derivative.java
- xchange-core/src/main/java/org/knowm/xchange/derivative/FuturesContract.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/AccountInfo.java
- xchange-core/src/main/java/org/knowm/xchange/dto/account/OpenPosition.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBookUpdate.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Ticker.java
- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trade.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/StopOrder.java
- xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrade.java
- xchange-core/src/main/java/org/knowm/xchange/exceptions/InstrumentNotValidException.java
- xchange-core/src/main/java/org/knowm/xchange/exceptions/MarketSuspendedException.java
- xchange-core/src/main/java/org/knowm/xchange/service/account/AccountService.java
- xchange-core/src/main/java/org/knowm/xchange/service/marketdata/MarketDataService.java
- xchange-core/src/main/java/org/knowm/xchange/service/marketdata/params/InstrumentsParams.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/DefaultTradeHistoryParamInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/DefaultTradeHistoryParamMultiInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/InstrumentParam.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/TradeHistoryParamInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/TradeHistoryParamMultiInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/TradeHistoryParamsAll.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/DefaultOpenOrdersParamInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/DefaultOpenOrdersParamMultiInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParamInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/orders/OpenOrdersParamMultiInstrument.java
- xchange-core/src/main/java/org/knowm/xchange/utils/jackson/InstrumentDeserializer.java
- xchange-core/src/test/java/org/knowm/xchange/derivative/FuturesContractTest.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/KrakenUserTrade.java
- xchange-ripple/src/main/java/org/knowm/xchange/ripple/dto/trade/RippleUserTrade.java
We are trying to implement the kraken futures and binance futures APIs. While implementing the *Raw services is straight forward, we are struggling with the non-*Raw services.
For some of those challenges this pull request offers solutions:
- some DTOs were still accepting only CurrencyPair, those now support Instrument
- some service methods accept only CurrencyPair, those now accept neutral Params
- There was no OpenPositions method: I added it to AccountInfo, because from our point of view a open positions is quite similar to a balance. 
- I added some interfaces and implementations for *InstrumentParam classes toi mirror existing *CurrencyPairParam classes
- I added a proposal for a FuturesContract, but I'm not very confided that it is already in a state to be used universally like …
> [core]Proposal for instrument enhancements and FuturesContract

- xchange-kraken/pom.xml
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/marketdata/KrakenAssetPair.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/dto/marketdata/KrakenAssetPairsJSONTest.java
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/marketdata/example-assetpairs-data.json
new field 'orderMin' is added to KrakenAssetPair
api doc: https://www.kraken.com/features/api#get-tradable-pairs
data: https://api.kraken.com/0/public/AssetPairs
uses lombok to reduce boilerplate code
> [kraken] added new field 'orderMin' to KrakenAssetPair

- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/request/InnerTransferRequest.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/AccountAPI.java
The [inner-transfer method at Kucoin API](https://docs.kucoin.com/#inner-transfer) swiched from v1 to v2
See [Changelog](https://docs.kucoin.com/#upcoming-changes) from 10/20/19:
> Deprecate '/api/v1/accounts/inner-transfer' endpoint for Inner Transfer.
> [kucoin] fixed inner-transfer method according to kucoin api v2

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
- xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
Updated `Currency` and added corresponding `CurrencyPair`.
This currency is supported by Luno ( see https://www.luno.com/en/developers/api#tag/Currency )
> Added support for ZMW (Zambian Kwacha)

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/Status.java
- xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexStatusJSONTest.java
updated the Status class according to the current api
see the api doc: https://docs.bitfinex.com/reference#rest-public-status
added fields like 'nextFundingEvtTimestampMillis'
> [bitfinex] updated the Status class according to the current api

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceCancelledOrder.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
Add missing reponse fields based on binance documentation [(Cancel Order)](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#cancel-order-trade)
```
{
"symbol": "LTCBTC",
"origClientOrderId": "myOrder1",
"orderId": 4,
"orderListId": -1, //Unless part of an OCO, the value will always be -1.
"clientOrderId": "cancelMyOrder1",
"price": "2.00000000",
"origQty": "1.00000000",
"executedQty": "0.00000000",
"cummulativeQuoteQty": "0.00000000",
"status": "CANCELED",
"timeInForce": "GTC",
"type": "LIMIT",
"side": "BUY"
}
```
and add new CancelAllOpenOrders service based on binance documentation [(Cancel All Open Orders)](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#cancel-all-open-orders-on-a-symbol-trade)
Cancel All Open …
> Improve Binance CancelOrder service

- pom.xml
- xchange-binance/src/main/java/org/knowm/xchange/binance/Binance.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/BinanceAccountInformation.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/BinanceSystemStatus.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/exchangeinfo/BinanceExchangeInfo.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/exchangeinfo/Symbol.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/service/marketdata/MarketDataServiceResilienceTest.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/dto/OutboundAccountInfoBinanceWebsocketTransaction.java
I think we can close [Binance - Deprecation of v1 endpoints](https://github.com/knowm/XChange/issues/3349) now!
> Upgrade Binance API based on change log release note.

- xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexBaseService.java
According to the latest [Bitmex REST API document](https://www.bitmex.com/app/restAPI#Viewing-Your-Request-Rate-Limit), the header field indicating rate limiting has changed as follows:
On each request to the API, these headers are returned:
```
"x-ratelimit-limit": 60
"x-ratelimit-remaining": 58
"x-ratelimit-reset": 1489791662
```
> [Bitmex] ratelimit header field for rate limiting changed

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexUserTrade.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
- make poloniex returnOrderTrades public (used to get total field)
There is a field that is not mapped to xchange common api (in this case total -> cost of trade).
- add global trade id
> [Poloniex] make poloniex returnOrderTrades public (used to get total field)

- xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/service/BitbayTradeServiceRaw.java
Use compact JSON instead of replacing whitespaces in String.
Issue: existing regexp is not replacing all whitespaces correctly, example (still new line in JSON):
```
{ "limit" : "300", "nextPageCursor" : "start", "markets" : [ ]
}
```
What is more, using the regex pattern is not necessary here, `ObjectMapperHelper.toCompactJSON` should be used.
> [Bitbay] Use compact JSON instead of replacing whitespaces in String

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampUserTransaction.java
Hi all.
This is a quite simple fix for issue : https://github.com/knowm/XChange/issues/3692
Basically I'm modifying the `BitstampUserTransaction` to add one function and then `BitstampAdapters` to handle this case.
I tested it locally (because I have Bitstamp subaccounts, which had sub account transfers and they were not showing up before the fix and are now showing up.
Best
> Fix for issue 3692

- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/CoinbaseProException.java
CoinbaseProException does not return original exchange message for `getMessage()`. It returns default `HttpStatusExceptionSupport.getMessage()`.
So `CoinbaseProException` currently returns:
`Invalid API Key  (HTTP status code: 401)`
instead of
`Invalid API Key`.
If we need to obtain http status code we can use: `HttpStatusExceptionSupport.getHttpStatusCode()`
This PR is fixing it.
> [CoinbasePro] CoinbaseProException - return original exchange message for getMessage()

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampUtils.java
- xchange-bitstamp/src/test/java/org/knowm/xchange/bitstamp/BitstampUtilsTest.java
Fixed problem that millis are lost in datetime for BitstampUserTransaction.
Bitstamp returns datetime with millis, but millis are ignored until this PR.
> [Bitstamp] Fixed: BitstampUserTransaction datetime has no millis

- pom.xml
Currently, by misconfiguration, it is not possible to skip generating sources and javadocs, because the configuration is hardcoded, so properties `maven.source.skip` and `maven.javadoc.skip` are ignored.
In this PR hardcoded config is removed. After this PR default generating sources and javadocs will be still enabled, but it will be possible to disable it.
Here are the results of building a project with 1 core (1 thread) without tests:
`mvn clean install -DskipTests -Dmaven.source.skip=true -Dmaven.javadoc.skip=true`
`Total time:  02:38 min`
vs
`mvn clean install -DskipTests`
`Total time:  13:13 min`  
So with skipping generating sources and javadocs build witout tests is 80% faster. It is very useful for development.
> Add possibility to skip generating sources and javadocs

- xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/BitmexMarketDataEvent.java
The current implementation assumes that the currency string is always at least 6 characters. However, some symbols are less than 6 characters e.g. https://www.bitmex.com/app/index/.BXBT
> [Bitmex-Stream] Relax restriction that currency string length must be >= 6

- xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/BitmexMarketDataEvent.java
Raising a PR to get this into the snapshot jar/develop branch. https://github.com/knowm/XChange/pull/3718
> [Bitmex-Stream] Relax restriction that currency string must be >= 6 (#1)

- pom.xml
- xchange-binance/pom.xml
- xchange-bittrex/pom.xml
- xchange-bittrexV3/pom.xml
- xchange-livecoin/pom.xml
Unfortunatelly XChange library is recognized as vulnerable library.
It is caused by using wiremock (I know - only for test, by auditing tools recognise this lib as vulnerable) for Java 7, which has dependencies to old libraries. This lib is for at least Java 8, so wiremock-jre8 should be used.
Referneces to isssues:
https://nvd.nist.gov/vuln/detail/CVE-2017-7656
https://nvd.nist.gov/vuln/detail/CVE-2017-7657
This PR is fixing those issues.
> [security] Fixed CVE-2017-7656 + CVE-2017-7657

- xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrade.java
UserTrade: added missing parameterless public static builder creation method that returns a builder, so in this way UserTrade(builder) is compliant with mapstruct framework: https://mapstruct.org/documentation/stable/reference/html/#mapping-with-builders
> UserTrade: added parameterless public static builder creation method

- .gitignore
- xchange-core/src/main/java/org/knowm/xchange/client/ExchangeRestProxyBuilder.java
- xchange-core/src/main/java/org/knowm/xchange/interceptor/InterceptorProvider.java
- xchange-core/src/test/java/org/knowm/xchange/interceptor/InterceptorProviderTest.java
- xchange-core/src/test/java/org/knowm/xchange/interceptor/TestInterceptor.java
- xchange-core/src/test/resources/META-INF/services/si.mazi.rescu.Interceptor
- xchange-examples/src/main/java/org/knowm/xchange/examples/interceptor/LoggingInterceptor.java
- xchange-examples/src/main/resources/META-INF/services/si.mazi.rescu.Interceptor
Added rescu Interceptor(s) support - added the possibility to use custom Interceptors.
Relates to #3272
Added rescu Interceptor(s) support to XChange library.
Based on Java ServiceLoader mechanism, so Interceptors can be easily added in client app by adding content to file:
```META-INF/services/si.mazi.rescu.Interceptor```
> [core] Added rescu Interceptor(s) support

- xchange-stream-gemini/src/main/java/info/bitrich/xchangestream/gemini/GeminiStreamingMarketDataService.java
Fix a null pointer exception in `GeminiStreamingMarketDataService` class, method `getOrderBook` caused by when `Object... args` is empty it will set `maxDepth` to null which would throw a NPE when we call `GeminiAdaptersX.toOrderbook(geminiOrderbook, maxDepth, new Date())` at the return for `getOrderBook`.
`toOrderBook` method signature is: `public static OrderBook toOrderbook(GeminiOrderbook geminiOrderbook, int maxLevels, Date timestamp)`
`maxLevels` is a primitive int, passing in a null here throws a NPE.
In the fix, instead of setting `maxDepth` to null we set it to zero.
> Fix NPE, maxDepth default to zero instead of null when args is empty

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingMarketDataService.java
volume on close is in "c" (not "b" for bid), and at index 1 (not 2)
https://docs.kraken.com/websockets/#message-ticker
> [Kraken] KrakenTicker copy paste error

- pom.xml
This reverts commit caceca7d
Currently `develop` branch is not building after https://github.com/knowm/XChange/pull/3760
@badgerwithagun next time please check if build is compiling.
https://travis-ci.org/github/knowm/XChange/builds/735640394
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project xchange-stream-service-pubnub: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/knowm/XChange/xchange-stream-service-pubnub/src/main/java/info/bitrich/xchangestream/service/pubnub/PubnubStreamingService.java:[15,53] cannot find symbol
[ERROR]   symbol:   class PNMembershipResult
[ERROR]   location: package com.pubnub.api.models.consumer.pubsub.objects
[ERROR] …
```
> Revert "Bump pubnub-gson from 4.31.3 to 4.33.2"

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingTradeService.java
As per the documentation at https://docs.kraken.com/websockets/#message-ownTrades , the tradeId should be the key of the map element. The current value ( dto.postxid ) is not unique and can be null.
> [Kraken][Streaming] - Restored original tradeId logic for userTrades stream

- xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java
- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java
- xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/WebSocketClientCompressionAllowClientNoContextHandler.java
Fixed a bug in the Kraken streaming client that started today resulting in the following error
```
Caused by: io.netty.handler.codec.CodecException: invalid WebSocket Extension handshake for "permessage-deflate; client_no_context_takeover"
```
Relates to https://github.com/netty/netty/issues/10191 , this change reuses the existing CoinbasePro handler which i moved to streaming-core-netty.
> [Streaming][Kraken] Fixed bug that caused `invalid WebSocket Extension handshake` message.

- xchange-stream-gemini/src/main/java/info/bitrich/xchangestream/gemini/GeminiStreamingMarketDataService.java
* Why would you ever want to fetch a zero-depth order book *by default*?
* Calling `getTicker()` fails with a NoSuchElementException because the order book is empty if you don't pass an argument to change it
* Changed a call to `currencyPair()` to `instrument()` to avoid using a deprecated method
* Removed logger and its dependencies because it is unused in this class
> change default order book size from 0 to 1

- xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
Stop allocated millions of Random() and StringBuilder() (nextInt() + "") 
when userReference is not supplied (Hitbtc)
> [Core][Order]Make Random static and remove StringBuilder allocation

- xchange-stream-cexio/src/main/java/info/bitrich/xchangestream/cexio/CexioStreamingRawService.java
When getSubscriptionData is called from
@Override
public String getUnsubscribeMessage(String channelName)
the "depth" parameter is missing, so this check is needed
> Fix missing depth parameter in case of call from unsubscribe

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
Official name was changed from "nuevo sol" to simply "sol" in 2015 by congress ruling 30381[1]
1- https://www.bcrp.gob.pe/transparencia/datos-generales/marco-legal/ley-que-cambia-el-nombre-de-la-unidad-monetaria-de-nuevo-sol-a-sol.html
> Official name was updated to just "sol" since 2015

- xchange-gemini/src/main/resources/gemini.json
Updated the metadata json file in accordance with https://docs.gemini.com/rest-api/#symbols-and-minimums
This is to fix an issue where getDynamicTradingFees() would only return fees for those currency pairs listed in the metadata file.
> Update Gemini ExchangeMetaData file

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
BinanceAdapters has special handling for pair extraction from binance's pair symbol. BUSD was not being handled correctly. For a pair such as "BTCBUSD", the resulting pair was "BTCB/USD" instead of "BTC/BUSD". This commit fixes this issue #3741
> [Binance] Add support to BUSD in Binance adapter. Fixes #3741

- xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java
- xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/CryptoFacilitiesTradeServiceRaw.java
Fixes issue #3934
* cryptofacilites fix: add missing stopPrice parameter to sendOrder
> Fix: [CryptoFacilities] stopPrice parameter is missing from sendOrder #3934

- xchange-btcmarkets/pom.xml
- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/dto/BTCMarketsOrderFlags.java
- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/dto/v3/trade/BTCMarketsPlaceOrderRequest.java
- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/service/BTCMarketsTradeService.java
- xchange-btcmarkets/src/main/java/org/knowm/xchange/btcmarkets/service/BTCMarketsTradeServiceRaw.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountServiceTest.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsMarketDataServiceTest.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsServiceTest.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsTestSupport.java
- xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsTradeServiceTest.java
- Added support for POST_ONLY order flag
- Restored tests disabled by @timmolter earlier this year
> [btcmarkets] - Restored service unit tests, added post only support

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/exchangeinfo/RateLimit.java
In the rate limit info of Binance, there is a field **intervalNum** that is not currently in the DTO. I use a custom Rate Limiter and this field is required for reliable validation.
See Binance API doc at https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#general-info-on-limits
**intervalNum describes the amount of the interval. For example, intervalNum 5 with intervalLetter M means "Every 5 minutes".**
Response from /api/v3/exchangeInfo
```
"rateLimits": [
{
"rateLimitType": "REQUEST_WEIGHT",
"interval": "MINUTE",
"intervalNum": 1,
"limit": 1200
},
{
"rateLimitType": "ORDERS",
"interval": "SECOND",
"intervalNum": 10,     <-----------------------------
"limit": 100
},
{
"rateLimitType": "ORDERS",
"interval": "DAY",
"intervalNum": 1,
"limit": 200000
}
],
```
> [Binance] Add intervalNum field in RateLimit class

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampOrderTransaction.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
- xchange-bitstamp/src/test/java/org/knowm/xchange/bitstamp/BitstampAdapterTest.java
Bitstamp had hardcoded set of currencies. 
Refactored using JsonAnySetter and list of markets form remoteInit.
> [bitstamp] do not hardcode currencies

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/Bitfinex.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexFundingOrder.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexFundingRawOrder.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexTradingOrder.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexTradingRawOrder.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BookPrecision.java
see api doc https://docs.bitfinex.com/reference#rest-public-book
unfortunatelly i had to separate the method, and make actually 4 different methods, depending on the input parameters
we differ between funding and trading books
we differ between raw (R0) and "aggrgated" (P0 ... P4) books
it would be difficult to handle those in one method, since the structure of the response depends on those input parameters
if, some one has a better idea, how to handle the different structures, would be happy to improve my implementation
> [bitfinex] added 'book' v2 api method

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceTicker24h.java
Add the closetime to the ticker, Binance is getting old tickers for markets that doesn't exist anymore and there is no way to know if they are good or not unless we have the time
> [Binance] ticker map closetime

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/resources/bitstamp.json
- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
As discussed in the issue, it's a simple fix that
Defines Doge as DOGE or XDG (not XDC)
And add a Currency for XinFin Network called XDC
As you can see on CMC : https://coinmarketcap.com/currencies/xinfin-network/
XDC is the official symbol of XinFin Network
And you can see on https://www.kraken.com/prices?quote=USD that the Kraken symbol for Doge is XDG (not XDC)
> Fix for Issue #4021 Bitfinex init exception and #4024 [Bitstamp] Some Currency Metadata and CurrencyPair Metadata are null

- xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAdapters.java
- xchange-ftx/src/test/java/org/knowm/xchange/ftx/FtxAdapterTest.java
The FTX adapter does not work for expiring futures, such as BTC-0625.
> [ftx] fix adapter for futures

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticated.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticatedV2.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampExchange.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampDigestV2.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java
- xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java
Hi All,
So this is a fix following the discussions in #3991 
It was a bit more complex than expected, here are some of the subtilities.
- We need both a UUID Nonce Factory and a millisecond time stamp (as string) factory because both are required in the requests.
- I had to write a new `BitstampDigestV2` because it changed completely from V1.
- All the authentication stuff is now in HeaderParams and not FormParams
- The content-type CANNOT be present if there is no body to the requests, hence the move of `@Consumes(MediaType.APPLICATION_FORM_URLENCODED)` from the top to the individual functions (when necessary). It's also taken into account into the `BitstampDigestV2` which includes it or doesn't include it for the signing process.
- Introduction of `apiKeyForV2Requests` as the api key …
> Fix for #3991 bitstamp v2 API should be taking UUID nonces

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingExchange.java
Added sandbox support for Binance exchange/streaming via exchangeSpecification.setExchangeSpecificParametersItem("Use_Sandbox", true)
The Binance spot testnet is located at https://testnet.binance.vision
> [Binance] Added sandbox support 

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAuthenticated.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexDigest.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeHistoryParams.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeService.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java
- xchange-bittrex/src/test/java/org/knowm/xchange/bittrex/service/BittrexDigestTest.java
This adds support for querying Bittrex trade history with a start and end time passed as a `TradeHistoryParamsTimeSpan`.
I had to tweak `BittrexDigest`, which provides the `Api-Signature` header value in authenticated requests, because Bittrex appears to use the unencoded URL when calculating this. When a date is specified in the query the `:` characters are URL-encoded.
Fixes #4050
> [Bittrex] Trade history query support for start and end time.

- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingAccountService.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/dto/BinanceWebsocketBalance.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/dto/OutboundAccountInfoBinanceWebsocketTransaction.java
Hi,
For some reason BinanceStreamingAccountService emits balance changes without timestamp, although it is present in server response. I'd like to include it with this PR.
I'm new to this project, hope someone can have a look. Thank you in advance.
> [Binance][Streaming] Preserving balance timestamp when converting from Binance balance DTO to core Balance

- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinExchange.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinMarketDataServiceRaw.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/CurrenciesResponse.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/SymbolAPI.java
Kucoin had no getCurrencies() implementation and because of that ExchangeMetaData was not properly created in KucoinAdapters.
> kucoin_currencies not implemented

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingExchange.java
`KrakenStreamingService` inherits a method `resubsribeChannels`(from `JsonNettyStreamingService`), so implementing it `KrakenStreamingExchange` is only a matter of calling the method on `streamingService` and `privateStreamingService` members
> Implement resubscribeChannels() for KrakenStreamingExchange

- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java
- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/marketdata/CoinmateTransactionsEntry.java
- xchange-stream-coinmate/src/main/java/info/bitrich/xchangestream/coinmate/v2/dto/CoinmateWebSocketTrade.java
`getMarketDataService.getTrades` is affected, not returning null for `type` property.
Small cleanup in adapters in same commit to avoid duplicity.
> Added OrderType when returning market trades

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexExchange.java
In generic implementation, Poloniex exchange service does not fills the currency data ( fee and wallet health ) in the remote initialization phase. This fix incorporates these data into currency metadata.
> Poloniex currency data

- xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
- xchange-stream-ftx/src/test/java/info/bitrich/xchangestream/ftx/FtxConvertDoubleForChecksumTest.java
- xchange-stream-ftx/src/test/java/info/bitrich/xchangestream/ftx/FtxStreamingMarketDataServiceTest.java
* scientific values for small values (0.0001 became 1E-4)
* Sub 1 values had to have a 0 (0.1234 should be 0.1234, not .1234)
* Whole numbers had to have a trailing .0 (1234 should be 1234.0 not
1234)
> [FTX] Solved issues with crc calculation.

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/service/BinanceBaseServiceTest.java
This change improves the ability of the API to handle a variety of types for the "recvWindow" parameter. This helps improve compatibility with services that load exchange parameters from files using generic deserializers.
I'm not sure what the consensus is regarding throwing exceptions or defaulting to `null` in the case of errors, so I have set it to throw an `IllegalArgumentException` for non-null values which could not be parsed.
I have also added a check to ensure that the obtained value is within the acceptable range [according to the Binance API specification](https://binance-docs.github.io/apidocs/spot/en/#signed-trade-user_data-and-margin-endpoint-security).
> One thing which I'm unsure about, is the creation of the test instances of `BinanceBaseService`, because what I am doing …
> [Binance] Improve Parsing of Exchange-Specific "recvWindow" Parameter

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampOrderStatus.java
This is a fix for issue #2590
Basically if the order was not filled, there are no transactions in the response from Bitstamp, example  : 
`{"status": "Canceled", "id": 1372542846992384, "amount_remaining": "0.00943030", "transactions": []}`
It is then impossible to compute or fill some informations in the Order, i have handled this case AND I have added the "Cancelled" Status which was not handled at the moment .. 
Let me know if this can be merged ..
> Fix for issue #2590

- xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxTradeService.java
- xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxTradeServiceRaw.java
In response to issue #4095
- All methods already exists now have their corresponding *ForSubaccount method
- All methods without *ForSubaccount now call to *ForSubaccount with `exspec.username` instead of null
- All non-`@Override` method were moved from `FtxTradeService` to `FtxTradeServiceRaw` for best practice
- Minor refactor for consistency
> [FTX] Completed *ForSubaccount methods

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/AssetDribbletLogResponse.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/BinanceWithdraw.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java
Fixed /sapi/v1/capital/withdraw/history applyTime field parsing. Fixes #4132
Also added toLocalDateTime/toDate parse support and refactor to use BinanceAdapters.toLocalDateTime new parsing methods.
> [Binance] Fixes #4132

- xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxAccountServiceRaw.java
Does not have a subaccount parameter in the FTX API, passing one causes NPE
this call changes MaxLeverage for whole account
> [FTX]changeLeverage

- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAuthenticated.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/Error.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/withdrawal/BittrexNewWithdrawal.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/withdrawal/BittrexWithdrawal.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/withdrawal/Status.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/withdrawal/Target.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountService.java
- xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountServiceRaw.java
Implemented method supporting "Create a new withdrawal" API endpoint - https://bittrex.github.io/api/v3#operation--withdrawals-post
> [Bittrex] API v3 add support for "Create a new withdrawal"

- xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
for BTC/ETH needs more decimal places  (not really sure why that DecimalFormat is need at all but ETH-BTC now works too)
> [FTX] Another orderbook checksum fix

- xchange-coinbasepro/pom.xml
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeService.java
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeServiceRaw.java
- xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/CoinbaseProAdaptersTest.java
- xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/CoinbaseProExchangeIntegration.java
- xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/service/BaseWiremockTest.java
- xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeServiceTest.java
- xchange-coinbasepro/src/test/resources/__files/openOrders.json
- xchange-coinbasepro/src/test/resources/__files/orders.json
This pull request will give users the ability to get open orders by currency pair. 
The implementation of get open orders prior to this pull request ignores the currency pair specification and returns all open orders.
> [CoinbasePro] Implement get open orders by currency pair

- xchange-dydx/pom.xml
Hi, I am a user of project **_org.knowm.xchange:xchange-dydx:5.0.10-SNAPSHOT_**. I found that its pom file introduced **_35_** dependencies. However, among them, **_4_** libraries (**_11%_**) have not been used by your project (the redundant dependencies are listed below). Reduce these useless dependencies can help prevent conflicts between library versions. MeanWhile, it can minimize the total added size to projects. It can also help enable advanced scenarios for this project. 
This PR helps **_org.knowm.xchange:xchange-dydx:5.0.10-SNAPSHOT_** lose weight :) I have tested the revised configuration in my local environment. It is safe to remove the unused libraries.
Best regards
> Could org.knowm.xchange:xchange-dydx:5.0.10-SNAPSHOT drop off redundant dependencies to loose weight?

- xchange-gemini/pom.xml
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiTradeService.java
- xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/GeminiAdaptersTest.java
- xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/service/BaseWiremockTest.java
- xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/service/GeminiTradeServiceTest.java
- xchange-gemini/src/test/resources/__files/example-open-orders-data.json
Filter open orders by currency pair.
The Gemini API does not allow for filtering by currency pair. This change filters by desired currency pair after retrieving all open orders from Gemini.
> Gemini open orders by pair

- xchange-core/src/main/java/org/knowm/xchange/ExchangeSpecification.java
- xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingExchange.java
- xchange-stream-coinbasepro/src/test/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingExchangeTest.java
Currently we are unable to override our websocket uris in our streaming projects. They are essentially hardcoded. There are situations that exist when one would want to change them like demos or due to internal servers structures.
This update would allow for any `xchange-stream` project to expose an override for their websocket uri via their respective `StreamingExchange`. In this pr, I have done this in `xchange-stream-coinbasepro` in the `CoinbaseProStreamingExchange`.
I could have implemented this via `ExchangeSpecification.getExchangeSpecificParametersItem` however I thought this functionality was something all streaming exchanges could benefit from. If there are strong objects, I can rework this pr to override the websocket uri only for `xchange-stream-coinbasepro` via …
> [Coinbasepro-Stream] Add support for overriding websocket uri

- xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingService.java
Some JSON messages dont have the channel field, like "AlreadySubscribed" error
> [FTX] - getChannelNameFromMessage fix

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdapters.java
Getting crossed books even after the checksum validation is passed, since we have re-subscription logic, triggered by IllegalStateException, we can use it.
> [KRAKEN] Crossed books that pass checksum

- xchange-core/src/main/java/org/knowm/xchange/service/trade/params/CancelOrderByInstrumentAndIdParams.java
- xchange-okex/src/main/java/org/knowm/xchange/okex/v5/OkexAdapters.java
- xchange-okex/src/main/java/org/knowm/xchange/okex/v5/dto/trade/OkexTradeParams.java
- xchange-okex/src/main/java/org/knowm/xchange/okex/v5/service/OkexTradeService.java
- xchange-okex/src/test/java/org/knowm/xchange/okex/v5/OkexExchangeIntegration.java
- xchange-okex/src/test/java/org/knowm/xchange/okex/v5/OkexTradeParams.java
Okex "adaptOrder" is fixed for "net_mode" accounts.
Also, "cancelOrder" input parameter is implemented using core classes to provide utilization of generic trading API.
> Okex trade service fix and cancel order param input generalization

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/DepositAddress.java
According to the binance API documentation, the fields informed in the response are slightly different from the properties of the DepositAddress class, notably the "addressTag" which made it impossible to use this information for deposits such as EOS, XRP, BNB, etc.
> [Binance][Accounts] updating the name of properties to correctly bind to the API

- xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java
- xchange-coinmate/src/test/java/org/knowm/xchange/coinmate/CoinmateAdapterTest.java
- xchange-coinmate/src/test/resources/org/knowm/xchange/coinmate/dto/trade/example-order1.json
- xchange-coinmate/src/test/resources/org/knowm/xchange/coinmate/dto/trade/example-order2.json
Avoid NPE when API sometimes sends null amounts in Order response
> [Coinmate] handle null amounts in order response

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceUsExchange.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceUsAccountService.java
- xchange-binance/src/main/resources/binanceus.json
- xchange-binance/src/test/java/org/knowm/xchange/binance/us/BinanceUsExchangeIntegration.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/us/ExchangeMetaDataIntegration.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingExchange.java
- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceUsStreamingExchange.java
- xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceUsIntegration.java
Adds support for Binance.US rest and streaming api. This does *not* guarantee 1:1 rest api support as .us and .com have diverged quite a bit. However, fetching candles, getting account info, and a few other things should work as expected.
For the streaming api, Trades, OrderBook, Tickers should all work (those I have in production already).
This addition is meant to get the ball rolling and will need to be further updated to support more rest features and probably streaming endpoints. The Binance.com api is quite different now so it's possible in the future that the .US code will need to be broken off into its own package(s).
> Binance.us support

- xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java
> [BitFinex] Streaming subscribe message

- xchange-binance/src/main/java/org/knowm/xchange/binance/Binance.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
If annotations are put above the javadoc, no javadoc can be consumed by calling methods. Hence, put annotations always below javadoc.
> [BINANCE] put annotations below javadoc

- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
- use type "Long" instead of "long" for parameter "orderId" in orderStatus() and cancelOrder()
The `BinanceTradeService` should use `Long orderId` instead of `long orderId` as parameter, because `orderId` is optional (see official Binance API documentation). If a user wants to set `clientOrderId`, then `orderId` must be set to null (which is actually not possible in BinanceTradeService).
Solves https://github.com/knowm/XChange/issues/4193
> [BINANCE] use "Long" instead of "long" for "orderId" 

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
According to actual Binance API:
```
2021-08-12
GET api/v3/myTrades has a new optional field orderId
```
This PR adds this field into myTrades().
Solves https://github.com/knowm/XChange/issues/4255
> [BINANCE] Add "orderId" in myTrades()

- xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
I'd like to use this library with bitfinex and their bitcoin lightning. Their supported ticker is `LNX` 
https://api-pub.bitfinex.com//v2/conf/pub:map:tx:method
> added LNX as lightning network ticker

- xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAdapters.java
- xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioBaseService.java
Fix Error:
`
{
"result":"false",
"code":5,
"message":"Error: empty key or sign"
}`
when try createExchange() without apiKey
> fix use gateio without apiKey

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceResilience.java
Motivated with the fact, that the Binance exchange refreshes permits per minute. Default xchange configuration (30s) looked for me as a bit too short. Waiting requests didn't wait enough for the permits to regenerate (if I understand everything correctly). Btw, this change was a successful remedy for my issues.
> [binance] Updated BinanceResilience timeout duration to one minute.

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
It's next to impossible to overwirte `withdraw type` to get deposit (and withdrawal) Bitfinex address for currencies not supported by XChange.
The `withdraw type` should be obtained through
https://api-pub.bitfinex.com/v2/conf/pub:map:tx:method
and name of the currency lowercased in order to get `withdraw type`
To make deposit/withdraw funcitonal for ETC and CLO, I add support manualy.
> Adding Bitfinex deposit/withdraw support for ETC, CLO

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingTradeService.java
Corected fee currency from **base** to **counter** currency in adaptKrakenUserTrade(), because the documentation of KrakenOwnTrade states that the fee relates to the "**quote** currency".
> Corrected fee currency in adaptKrakenUserTrade()

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceDribbletDetails.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceDribblets.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceDustLog.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/BinanceExchangeIntegration.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/service/trade/TradeServiceIntegration.java
- xchange-binance/src/test/resources/__files/dustlog.json
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
Adds new ability to get DustLog history from Binance. See https://github.com/knowm/XChange/issues/4371
Adds the new response "EGeneral:Too many requests" from Kraken to the base service. See https://github.com/knowm/XChange/issues/4369#issue-1088385658
> Adds DustLog History to Binance and adds additional response to Kraken.

- xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataService.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/WithdrawalAPI.java
With the new update of the Kucoin Sandbox API, in the `adaptCurrencyMetaData` method from `KucoinAdapters`, we get a `NullPointerException` because, for USDN currency, there is a null value for `currenciesResponse.getWithdrawalMinFee()` and `currenciesResponse.getWithdrawalMinSize()`.
With this update, I set a Zero value instead of triggering a `NullPointerException`.
> [Kucoin] NullPointerException when retrieving currencies metadata

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAuthenticated.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/KrakenStandardOrder.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/TimeInForce.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeServiceRaw.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/service/BaseWiremockTest.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/service/KrakenTradeServiceTest.java
Add support for Kraken "timeInForce" parameter - see https://docs.kraken.com/rest/#operation/addOrder
The case of the API field name appears to be wrong in the docs (`timeinforce`) or Kraken has a bug as only `timeInForce` is accepted by the API.
> Add Kraken timeinforce parameter

- xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingExchange.java
FTX streaming: take "overrideWebsocketApiUri" into account
e.g. to support FTX-US exchange
> FTX streaming: take "overrideWebsocketApiUri" into account

- xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAdapters.java
If I cancel the FTX order, the remainingAmount becomes 0 even though none of the orders are filled, and the cumulativeAmount is not specified, so the cumulativeAmount becomes the originalAmount.
It fixes one issue of #4440 and #4269
> Adapt cumulativeAmount of ftx limit orders

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdapters.java
- xchange-stream-kraken/src/test/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdaptersTest.java
askSize and bidSize are returned by the Kraken API (see https://docs.kraken.com/rest/#operation/getTickerInformation) , but not yet mapped into Ticker.
> Include askSize and bidSize in Kraken Ticker

- xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
`new DecimalFormat("0.0#######", new DecimalFormatSymbols(Locale.US)))`
The default DecimalFormat is created with the default locale. Which in some cases leads to incorrect formatting, the point is changed to a comma (0,0##)
```
if (!calculatedChecksum.equals(message.getChecksum())) {
final OrderBook sortedOrderBook =
new OrderBook(
Date.from(Instant.now()),
new ArrayList<>(orderBook.getAsks()),
new ArrayList<>(orderBook.getBids()),
true);
calculatedChecksum =
getOrderbookChecksum(sortedOrderBook.getAsks(), sortedOrderBook.getBids());
if (!calculatedChecksum.equals(message.getChecksum())) {
throw new IllegalStateException("Checksum is not correct!");
}
```
According to the specification of the FTX exchange API, the checksum is considered in the sorted list:
> …
> FtxStreamingAdapters 3 bugfix

- xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAdapters.java
- xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAuthenticated.java
- xchange-ftx/src/main/java/org/knowm/xchange/ftx/dto/trade/FtxFillDto.java
- xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxTradeServiceRaw.java
Change for #4496 
----------
Moved `getTradeHistoryForSubaccount()` to use that `/fills?market={market}`
DTO was added to process that API response.
Before:
`Pulled Trade: UserTrade[type=BID, originalAmount=0.001, instrument=ETH/USD, price=1752.0, timestamp=Sat Jun 04 02:06:55 HKT 2022, id=151761986698, orderId='151761986698', feeAmount=null, feeCurrency='null', orderUserReference='98d3e174-8d69-4431-89ba-2e9c7755831e']
`
After:
`Pulled Trade: UserTrade[type=BID, originalAmount=0.001, instrument=ETH/USD, price=1752.0, timestamp=Sat Jun 04 02:07:30 HKT 2022, id=8434794907, orderId='151761986698', feeAmount=-5E-9, feeCurrency='ETH', orderUserReference='null']`
`fee`, `feeCurrency` and `id` now consitent with `getStreamingTradeService().getUserTrades()` callback.
Reference: Callback result …
> Moved getTradeHistoryForSubaccount() to use /fills

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingTradeService.java
Otherwise, it will not subscribe again after reconnection
> Kraken: need to clear "is subscribed" internal flags when service is disconnected

- xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingMarketDataService.java
- xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java
- xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/dto/CoinbaseProWebSocketTransaction.java
Two optimizations that make it possible to process up to 10K transactions per second:
- reuse LimitOrder object if the size of a quote doesn't change
- parse snapshot and l2update transactions w/o involving Jackson library which looks quite slow for them
> Coinbase: order book subscription optimizations

- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexUtils.java
- xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/marketdata/PoloniexChartData.java
Poloniex API for returnChartData now returns only 100 candles + it returns millis instead of seconds for the time of the candle.
We are fixing millis - but anyone using the data needs to improve the fetching inside their project
> Fix Poloniex after API changes for returnChartData

- xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
If reconnection is handled by the client code every call of disconnect() and connecting again creates a new thread while the old one still lives
> Threads are leaking if disconnecting service that was closed by the server

- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountServiceRaw.java
- xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProDigest.java
Right now when digest is computed it is first stored to `signature` field and then returned. If we run this code in more threads there is a high risk that we return `signature` computed for different request in different thread. That causes "Invalid signature" errors when sent to CoinbasePro API.
This fix removes this unnecessary step of reassignment and return, we just simply return the signature value.
In the only case where we need to store the signature we rather wrap our singleton digest into proxy class that stores our signature for webhook auth in internal field. That way for each call we create a new class instance and avoid any synchronization issues.
> [CoinbasePro] Fixed synchronization in CoinbaseProDigest

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java
Hi, I suggest changing the default method of getting ETH deposit address from Kraken.
Kraken last year introduced a unified ERC20 deposit address for Ethereum deposits together with ERC20 tokens.
Where `Ether (Hex)` method in some time will be dropped.
You can find more details in the link below:
https://support.kraken.com/hc/en-us/articles/4410585641108-Important-change-to-ETH-and-ERC-20-deposits
```
kraken_request('/0/private/DepositMethods', {
"asset": "ETH"
})
```
```
{'error': [], 'result': [
{'method': 'Ether (Hex)', 'limit': False, 'gen-address': True}, 
{'method': 'Ethereum (ERC20)', 'limit': False, 'gen-address': True}
]}
```
> [kraken] Change deprecated Ethereum (Hex) method for Ethereum (ERC20)

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
After migration to `InstrumentMetaData` `marketOrderEnabled` is by default `false`. Previously the `CurrencyPairMetaData` constructor was used instead of a builder and that one used to set it correctly to `true`.
Added `marketOrderEnabled(true)` to the builder to revert this unintended change.
> [Kraken] Set marketOrderEnabled to true in InstrumentMetaData

- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinMarketDataServiceRaw.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/CurrencyResponseV2.java
- xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/SymbolAPI.java
- Added v2 get-symbols, marked v1 method as deprecated, see https://docs.kucoin.com/#get-symbols-list-deprecated
- Added getting of curerncy detail from api v2
> [kucoin] Add missing general api methods

- pom.xml
- xchange-core/pom.xml
Hello, first of all thank you for providing XChange!
We are looking to migrate our project from the javax to the jarkarta namespace and XChange currently brings a transient dependency to javax's cache API because XChange depends on resilience4j cache.
This PR replaces the resisilience4j dependency to the module that actually seem to be used.
> Replace dependency to resilience4j-all by actually used modules (ratelimiter and retry)

- xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingMarketDataService.java
Similar to `BinanceStreamingMarketDataService` which is also public this was needed to be able to use this class in my code which uses the XChange library.
Sample code that works for Binance, but not (yet) for KuCoin:
```
kucoinStreamingExchange
.getStreamingMarketDataService()
.getOrderBook(currencyPair)
.subscribe(orderBook -> log.debug("Received orderbook: {}", orderBook) );
```
`getStreamingMarketDataService()` returns a type which is not usable outside the package itself.
> Make `KucoinStreamingMarketDataService` available outside package

- xchange-kraken/src/test/java/org/knowm/xchange/kraken/KrakenUtilsTest.java
This PR fixes the non deterministic behaviour of a test `org.knowm.xchange.kraken.KrakenUtilsTest#testAdaptTradeHistoryByCurrencyPair`. This happens as the test assumes the order of keys in a hashmap, which is not guaranteed. It has been detected using [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
1. `mvn install -pl xchange-kraken`
2. `mvn -pl xchange-kraken edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.knowm.xchange.kraken.KrakenUtilsTest#testAdaptTradeHistoryByCurrencyPair`
```
[INFO] Running org.knowm.xchange.kraken.KrakenUtilsTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.452 s <<< FAILURE! -- in org.knowm.xchange.kraken.KrakenUtilsTest
[ERROR] org.knowm.xchange.kraken.KrakenUtilsTest.testAdaptTradeHistoryByCurrencyPair …
```
> Fix flaky test in kraken module

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/marketdata/BitstampPairInfo.java
Added missing mapping of field "instant_and_market_orders" in /v2/trading-pairs-info/ endpoint
> Added Bitstamp instant_and_market_orders mapping

- xchange-okex/src/main/java/org/knowm/xchange/okex/OkexAdapters.java
- xchange-okex/src/main/java/org/knowm/xchange/okex/dto/marketdata/OkexOrderbook.java
- xchange-stream-okex/src/main/java/info/bitrich/xchangestream/okex/OkexStreamingMarketDataService.java
add timestamp to each order in orderbook updates received by websockets
> [OKX} orderbook orders timestamp

- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingMarketDataService.java
- xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceManualExample.java
- xchange-stream-core/src/main/java/info/bitrich/xchangestream/core/StreamingMarketDataService.java
- xchange-stream-okex/src/main/java/info/bitrich/xchangestream/okex/OkexStreamingMarketDataService.java
Currently used in Binance Stream and Okx stream.
I also have a ready Bybit stream, which also has such a method.
> [CORE] Give ability to get separate snapshots of orderbook updates.

- xchange-bybit/src/main/java/org/knowm/xchange/bybit/BybitAuthenticated.java
- xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/trade/BybitPlaceOrderPayload.java
- xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitTradeServiceRaw.java
- xchange-bybit/src/test/java/org/knowm/xchange/bybit/TradeExample.java
- xchange-bybit/src/test/resources/logback.xml
fix  #4822 #4771 
thx to @pozheg
for error analysis
> [bybit] fix futures error "symbol invalid"

- xchange-core/src/main/java/org/knowm/xchange/exceptions/DepositAddressAmbiguousException.java
- xchange-core/src/main/java/org/knowm/xchange/exceptions/DepositAddressCreationException.java
- xchange-core/src/main/java/org/knowm/xchange/exceptions/DepositAddressNotFoundException.java
- xchange-core/src/main/java/org/knowm/xchange/service/account/AccountService.java
- xchange-core/src/main/java/org/knowm/xchange/service/account/params/DefaultRequestDepositAddressParams.java
- xchange-core/src/main/java/org/knowm/xchange/service/account/params/RequestDepositAddressParams.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java
- xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountServiceRaw.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/service/BaseWiremockTest.java
- xchange-kraken/src/test/java/org/knowm/xchange/kraken/service/KrakenAccountServiceTest.java
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-addresses-trx.json
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-addresses-xrp.json
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-addresses.json
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-methods-trx.json
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-methods-usdt.json
- xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-deposit-methods-xrp.json
The current implementation doesn't allow for getting addresses with tags (eg XRP) and also if you have currencies with multiple methods (eg USDT, USDC) it is not supported.
This PR introduces a new change to the AccountService interface to allow for more structured complex deposit address requests with a default to the current methods.
It implements this new method on Kraken also inferring the appropriate method where possible with some clear exceptions if it isn't able to do so, so the user can refine their request if desired.
> [kraken] add different network support for currency deposit addresses

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceKline.java
fix #4817 
it try to compatible `closed` field which is predicated from the official document
> compatible BinanceKline closed

- xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/account/LedgerType.java
https://support.kraken.com/hc/en-us/articles/360001169383-How-to-interpret-Ledger-history-fields
"sale" = this shows only as a filter option when viewing your Ledger history while signed in to your account, it is not shown in history exports. "Sale" is a filter that brings up all "Spend" and "Receive" entries from orders placed via the new Kraken app or Buy Crypto button.
> bugfix/ETD-1130 - added LedgerType SALE for tx - spend and received

- xchange-core/src/main/java/org/knowm/xchange/utils/BigDecimalUtils.java
Turns out, that DECIMAL32 is not enough. For example for TRX:
> Change MathContext to 64, as 32 is not enough for some coins

- pom.xml
The currently used lombok version is not compatible with JDK 21.
In addition, Its advised to switch from source/target to release (see https://openjdk.org/jeps/247 for details), introduced in Java 9.
The maven compiler plugin with translate this automatically to the old source/target/bootclasspath options for Java 8 compilers.
> Enable Compilation on JDK21

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdapters.java
- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingMarketDataService.java
- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java
- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenSubscriptionConfig.java
- xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
This PR adds support for OHLC Streaming for Kraken. It requires a (backward-compatible) change to NettyStreamingService in order to allow streaming of OHLC for multiple intervals for the same currrency pair.
Without this change the channelId won't be unique and interfere with each other.
> Kraken: add support for OHLC Streaming

- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioAccountServiceRaw.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioMarketDataService.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioTradeServiceRaw.java
- xchange-gateio-v4/src/test/resources/rest/spot.http
- xchange-stream-gateio/src/main/java/info/bitrich/xchangestream/gateio/GateioStreamingService.java
- xchange-stream-gateio/src/main/java/info/bitrich/xchangestream/gateio/config/IdGenerator.java
- xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingAccountServiceIntegration.java
- xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingMarketDataServiceIntegration.java
- xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingTradeServiceIntegration.java
Minor fixes:
- Replaced calls to deprecated code: `Validate.notNull(...)`, `RandomUtils`
- Added http requests to create and cancel order
- Speed up integration tests
> [gateio] [gateio-stream] Gateio minor fixes

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/WithdrawalRequest.java
Small followup to [the recent PR that added txid to the WithdrawalRequest object](https://github.com/knowm/XChange/pull/4889).
> [Bitstamp] include txid in toString()

- xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexAdapters.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexAuthenticated.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexErrorAdapter.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexExchange.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/CoinexJacksonObjectMapperFactory.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/converter/CurrencyPairToStringConverter.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/converter/OrderTypeToStringConverter.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/converter/StringToOrderStatusConverter.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/converter/StringToOrderTypeConverter.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/dto/account/CoinexMarketType.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/dto/account/CoinexOrder.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexTradeService.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexTradeServiceRaw.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexV2Digest.java
- xchange-coinex/src/test/java/org/knowm/xchange/coinex/service/CoinexV2DigestTest.java
- xchange-coinex/src/test/resources/rest/sign.js
- xchange-coinex/src/test/resources/rest/spot.v2.http
- Added placing of market orders
- Fixed digest function, so that the query params are also processed
- Added getting of orders
- Extended error adapter
- Fixed but with last price in ticker
> [coinex] Add market orders

- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java
- xchange-core/src/test/java/org/knowm/xchange/dto/marketdata/ConcurrencyTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/marketdata/OrderBookOld.java
- xchange-gateio-v4/src/test/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceTest.java
- xchange-gateio/src/test/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceTest.java
More flexible and faster OrderBook update synchronize, used StampedLock sync.
Added concurrency and integrity example(test)
1. New way - used stampedLock only.
2. Synchronized wrapped in stampedLock.
3. Old way - Synchronized only.
No concurrency exeption.
All results the same at same Seed number.
> [core] orderbook sync 2nd try

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampExchange.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampV2.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampMarketDataServiceRaw.java
> [bitstamp] Replace array with List in api call

- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticatedV2.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/WithdrawalFee.java
- xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java
- xchange-bitstamp/src/test/java/org/knowm/xchange/bitstamp/dto/account/WithdrawalFeesJSONTest.java
- xchange-bitstamp/src/test/resources/org/knowm/xchange/bitstamp/dto/account/withdrawal-fees.json
- xchange-examples/src/main/java/org/knowm/xchange/examples/bitstamp/account/BitstampAccountDemo.java
The Bitstamp V2 API has [an endpoint for requesting all withdrawal fees](https://www.bitstamp.net/api/#tag/Fees/operation/GetAllWithdrawalFees):
`https://www.bitstamp.net/api/v2/fees/withdrawal/`
This code implements the client code necessary to call that endpoint with the XChange lib: a `WithdrawalFee` object, the web service skeleton in `BitstampAuthenticatedV2`, and the implementation in the `BitstampAccountServiceRaw` class.
> [Bitstamp] Implement client code for withdrawal-fees endpoint

- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/BinanceSystemStatus.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataService.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceUsAccountService.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/service/marketdata/MarketDataServiceIntegration.java
- xchange-core/src/main/java/org/knowm/xchange/dto/meta/ExchangeHealth.java
- xchange-core/src/main/java/org/knowm/xchange/service/marketdata/MarketDataService.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/Gateio.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/config/Config.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/dto/marketdata/GateioServerTime.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioMarketDataService.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceRaw.java
- xchange-gateio-v4/src/test/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceIntegration.java
I think we need some exchange-health related functionality moved in core. Some exchanges provide a dedicated endpoint (e.g. binance), some not (e.g. gateio).
- Added exchange health to the core services
- Added sample implementation for binance (using `system/status` endpoint)
- Added sample implementation for gateio-v4 (using `spot/time` endpoint)
> [general] Add getting of exchange health

- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/GateioErrorAdapter.java
Added mapping of error when order size is too small, for example:
```
{
"label": "INVALID_PARAM_VALUE",
"message": "Your order size 0.600000 USDT is too small. The minimum is 3 USDT"
}
```
> [gateio-v4] Extend error mapping

- xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitMarketDataService.java
- xchange-bybit/src/test/resources/logback.xml
- Added default, so that `BybitMarketDataService.getTickers(null)` returns tickers for spot as default instead of throwing exception
- Disabled trace output for tests
> [bybit] Optimize getting of tickers

- xchange-stream-okex/src/main/java/info/bitrich/xchangestream/okex/OkexStreamingService.java
**fix(okex): Fix issue with resubscribing to channels after login**
- Added `loginDone` and `needToResubscribeChannels` flags
- Initialized the `loginDone` flag during connection setup
- Implemented the `resubscribeChannels` method to decide whether to resubscribe based on login status
- Checked if channel resubscription is needed after a successful login
**Steps to Reproduce:**  
1. Use the `getUserTrades` method to subscribe to order events.  
2. Disconnect and then reconnect the network.  
3. Place order on OKX; the order events will not be received.
> [okex-stream] all login-required channels become invalid after a network disconnection and reconnection

- pom.xml
- xchange-bitget/pom.xml
- xchange-coinex/pom.xml
- xchange-gateio-v4/pom.xml
- xchange-gateio/pom.xml
- xchange-stream-gateio/pom.xml
Moved version definition of `<artifactId>jackson-datatype-jsr310</artifactId>` to parent
> [general] Move jsr310 dependency version to parent

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java
- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenSubscriptionStatusMessage.java
Changes the field 'channelId' from Integer to Long, see https://github.com/knowm/XChange/issues/4961
> fix: fix channelId overflow

- xchange-core/src/main/java/org/knowm/xchange/utils/OrderValuesHelper.java
Added adapting the price to the step-size. 
For example, `bitmex` needs price of `ETH_USDT` to be adapted to smallest step `0.05`
> [core] Add adapting of price to step size

- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAdapters.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataService.java
- xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
Minor fixes for bitfinex:
- Replaced boilerplate code with lombok annotations
- fixed NPE when adapting `percentageChange` field
- Switched argument from `CurrencyPair` to recommended `Instrument` at getting of order book
- Replaced some direct member access with getters
> [bitfinex] Minor fixes

- xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/AscendexAdapters.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
- xchange-bitget/src/main/java/org/knowm/xchange/bitget/BitgetAdapters.java
- xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexAdapters.java
- xchange-gateio-v4/src/main/java/org/knowm/xchange/gateio/service/GateioAccountService.java
- xchange-stream-coinmate/src/main/java/info/bitrich/xchangestream/coinmate/v2/CoinmateStreamingAccountService.java
- Added `WalletFeature` values to wallets with id `"spot"`
- Replaced `HashSet` with `EnumSet`
> [general] Add WalletFeature to some created wallets

- xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java
- xchange-core/src/test/java/org/knowm/xchange/dto/marketdata/ConcurrencyTest.java
- xchange-core/src/test/java/org/knowm/xchange/dto/marketdata/OrderBookTest.java
In the previous implementation there was a bug if the size of the order array was zero.
I did not go through all the check options. And limited myself to only the two most common options. I do not want to make a mistake somewhere again.
add tests to recheckIdx method
> [CORE] orderbook recheckidx fix

- xchange-bybit/src/main/java/org/knowm/xchange/bybit/BybitAdapters.java
Get the parse date argment `Locale.US` back since pr #4912 removed it.
> [bybit] fix date parse locale

- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingMarketDataService.java
Added 'break' statement after KLINE case to prevent fall-through.
> [binance] fix missing control statements

- xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingChecksum.java
The original code is compiling a Regex in a loop which is inefficient in an active system. What I'm seeing is that most of the time, I/O threads spend on this Pattern compilation.
`
nioEventLoopGroup-18-1" #76 [85] prio=10 os_prio=0 cpu=78812.80ms elapsed=7034.36s tid=0x00007f4404302110 nid=85 runnable  [0x00007f44746ce000]
java.lang.Thread.State: RUNNABLE
at java.util.regex.Pattern$CharProperty.study(java.base@21.0.4/Pattern.java:4119)
at java.util.regex.Pattern$Start.<init>(java.base@21.0.4/Pattern.java:3777)
at java.util.regex.Pattern.compile(java.base@21.0.4/Pattern.java:1967)
at java.util.regex.Pattern.<init>(java.base@21.0.4/Pattern.java:1576)
at java.util.regex.Pattern.compile(java.base@21.0.4/Pattern.java:1101)
at java.lang.String.replaceFirst(java.base@21.0.4/String.java:3025)
at …
> [Kraken] - Improve performance of checksum computation

- xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
Some exchanges use DNS and CDN technologies. If the domain name is resolved locally, it will return the IP address of the nearest server to the exchange from the local network. In this case, the SOCKS client will pass this IP to the proxy server, and the proxy server will attempt to connect using this IP, leading to a timeout. The best approach is to have the proxy server handle the DNS resolution.
Here is an analysis of part of the Netty source code:
1. `Bootstrap.java`
2.`Socks5ProxyHandler.java`
> [fix]When using a proxy with WebSocket, the DNS resolution should be performed within the proxy server.

- xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
- xchange-binance/src/main/java/org/knowm/xchange/binance/dto/meta/exchangeinfo/Filter.java
- xchange-binance/src/test/java/org/knowm/xchange/binance/us/ExchangeMetaDataIntegration.java
Added support for parameters, which can filled from Binance.
> Add MaxNotional and PriceStepSize

- xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceUsStreamingExchange.java
BinanceUsStreamExchange can't inherit from BinanceStreamExchange becaus there is no way of telling that it should use the BinanceUs Base Class
> BinanceUsStreamExchange inherits from BinanceUsExchange
