xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcAdapters.java
Let me start https://github.com/timmolter/XChange/pull/816#issuecomment-69636987 with hitbtc :)
=> [hitbtc] Remove local timestamps from order book and its orders.

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoin.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinDigest.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OKCoinBaseTradePollingService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinAccountServiceRaw.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinTradeServiceRaw.java
'partner' key is no more longer supported by OkCoin usd
=> changed partner to api_key

pom.xml, xchange-empoex/api-specification.txt, xchange-empoex/pom.xml, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoEx.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExAdapters.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExAuthenticated.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExErrorException.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExException.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExExchange.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/EmpoExUtils.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/account/EmpoExBalance.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/marketdata/EmpoExLevel.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/marketdata/EmpoExTicker.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/marketdata/EmpoExTrade.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/trade/EmpoExOpenOrder.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/dto/trade/EmpoExOrderResponse.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/EmpoExBaseService.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/EmpoExHmacPostBodyDigest.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/EmpoExPayloadDigest.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExAccountService.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExAccountServiceRaw.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExBasePollingService.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExMarketDataService.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExMarketDataServiceRaw.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExTradeService.java, xchange-empoex/src/main/java/com/xeiam/xchange/empoex/service/polling/EmpoExTradeServiceRaw.java
=> EmpoEX Full Implementation

pom.xml
to  the `release-sign-artifacts` profile
=> [pom] Move maven-source-plugin and maven-javadoc-plugin executions

xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/Trade.java, xchange-core/src/main/java/com/xeiam/xchange/dto/trade/UserTrade.java, xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/service/polling/CryptsyBasePollingService.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenMarketDataService.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenTradeService.java
re: CryptsyBasePollingService now that it contains both the public and private API does it really make sense for it to stay templated in its current form? 
The Cryptsy fix was to stop the URL being generated as http://pubapi.cryptsy.com/api/api.php?method=orderdatav2
but instead http://pubapi.cryptsy.com/api.php?method=orderdatav2
=> Cryptsy public API bug fix for v3.0.0-SNAPSHOT, Kraken general enhancements, Trade Builder additions

xchange-bitvc/src/main/java/com/xeiam/xchange/bitvc/BitVcAdapters.java
Huobi timestamps are of the form "HH:mm:ss", and are converted by the BitVcAdapters class to timestamps with the same hour, minute and date on January 1st, 1970. This date is incorrect, but there is even another more serious problem when sorting the dates by this timestamp. If there are two consecutive trades with times 23:59:59 and 00:00:01 then the second trade is after first trade, but when sorting by the timestamp, it will be placed before the first (it will be placed in the beginning of the list instead of the end), since 00:00:01 January 1st, 1970 is before 23:59:59 January 1st, 1970.
The following patch converts the the HH:mm:ss time to a timestamp that is within a 24 hour window ending in the current time. The timestamp is allowed to be up to 5 minutes in the future to compensate …
=> Convert HH:mm:ss to timestamp within the last 24 hours.

pom.xml, xchange-bitso/pom.xml, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAuthenticated.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoExchange.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/dto/BitsoBaseResponse.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/dto/BitsoException.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/dto/account/BitsoBalance.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/dto/account/BitsoDepositAddress.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/BitsoDigest.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoAccountService.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoAccountServiceRaw.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoBasePollingService.java, xchange-bitso/src/main/resources/bitso.json, xchange-examples/pom.xml, xchange-examples/src/main/java/com/xeiam/xchange/examples/bitso/BitsoDemoUtils.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/bitso/account/BitsoAccountDemo.java
This is an initial partial implementation for #819.
It includes AccountService implementation (getAccountInfo, withdrawFunds, requestDepositAddress) plus withdrawToRipple.
=> Partial support for Bitso: PollingAccountService implementation and Ripple withdrawal

pom.xml, xchange-examples/src/main/java/com/xeiam/xchange/examples/okcoin/streaming/OkCoinSocketIODemo.java, xchange-okcoin/pom.xml, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinExchange.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/marketdata/OkCoinDepth.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/marketdata/OkCoinStreamingTicker.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/MD5Util.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinExchangeEvent.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinExchangeStreamingConfiguration.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinJsonAdapters.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinStreamingExchangeService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinWebSocketService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketBase.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketClientHandler.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketService.java
Initial commit for websocket market data streaming. It's based on the reference implementation by OkCoin and already contains its trade functionality, but has not been wired up into the XChange interface yet. It's mostly reusing the existing market data DTOs.
`OkCoinSocketIODemo` shows the standard demo for streaming.
=> OkCoin websocket initial commit

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/MonitorTask.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinWebSocketService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketBase.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketClientHandler.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/WebSocketService.java
DISCONNECT event is now put in the queue in case of websocket disconnect/reconnect
=> Add DISCONNECT event for OkCoin streaming

xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/dto/marketdata/ItBitTicker.java
=> Dont deserialise CurrencyPair for ItBitTicker

xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/streaming/BitstampPusherService.java, xchange-btcchina/src/main/java/com/xeiam/xchange/btcchina/service/streaming/BTCChinaSocketIOService.java, xchange-coinsetter/src/main/java/com/xeiam/xchange/coinsetter/service/streaming/CoinsetterSocketIOService.java, xchange-core/src/main/java/com/xeiam/xchange/service/streaming/BaseWebSocketExchangeService.java, xchange-core/src/main/java/com/xeiam/xchange/service/streaming/StreamingExchangeService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinStreamingExchangeService.java
see at https://github.com/timmolter/XChange/issues/870
=> proposal to add countEventsAvailable to StreamingExchangeService

xchange-coinsetter/src/main/java/com/xeiam/xchange/coinsetter/CoinsetterAdapters.java, xchange-coinsetter/src/main/java/com/xeiam/xchange/coinsetter/service/streaming/CoinsetterSocketIOService.java
Added support for 'last' (Trade) events in CoinsetterSocketIOService.java and CoinsetterAdapters.java
=> Added support for 'last' (Trade) events in Coinsetter

xchange-coinsetter/src/main/java/com/xeiam/xchange/coinsetter/service/streaming/CoinsetterSocketIOService.java, xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/OrderBook.java
CoinsetterSocketIOService does not return OrderBooks or Trades that are equal to previous
=> No duplicates added in CoinsetterSocketIOService 

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinAdapters.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/trade/OkCoinOrder.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinFuturesTradeService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinTradeServiceRaw.java
Think the following updates need to be made 
* allow setting of contract on limit orders
* update getFuturesOrder to support a status of 1 or 2 to indicate open or closing orders
* iterate over different futures contracts as well as each currency when getting open orders and cancelling orders.
=> Support trade methods on okcoin futures

xchange-anx/src/main/java/com/xeiam/xchange/anx/v2/ANXAdapters.java, xchange-anx/src/test/java/com/xeiam/xchange/anx/v2/ANXAdapterTest.java, xchange-bitcointoyou/src/test/java/com/xeiam/xchange/bitcointoyou/BitcoinToYouAdapterTest.java, xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/BitfinexAdapters.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java, xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/BitstampAdapters.java, xchange-bitstamp/src/test/java/com/xeiam/xchange/bitstamp/BitstampAdapterTest.java, xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/BittrexAdapters.java, xchange-bleutrade/src/main/java/com/xeiam/xchange/bleutrade/BleutradeAdapters.java, xchange-btcchina/src/main/java/com/xeiam/xchange/btcchina/BTCChinaAdapters.java, xchange-btctrade/src/main/java/com/xeiam/xchange/btctrade/BTCTradeAdapters.java, xchange-btctrade/src/test/java/com/xeiam/xchange/btctrade/BTCTradeAdaptersTest.java, xchange-bter/src/main/java/com/xeiam/xchange/bter/BTERAdapters.java, xchange-bter/src/test/java/com/xeiam/xchange/bter/BTERAdapterTest.java, xchange-campbx/src/main/java/com/xeiam/xchange/campbx/service/polling/CampBXAccountService.java, xchange-cexio/src/main/java/com/xeiam/xchange/cexio/CexIOAdapters.java, xchange-core/src/main/java/com/xeiam/xchange/dto/account/AccountInfo.java, xchange-core/src/main/java/com/xeiam/xchange/dto/trade/Wallet.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcAdapters.java, xchange-huobi/src/main/java/com/xeiam/xchange/huobi/HuobiAdapters.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java, xchange-loyalbit/src/main/java/com/xeiam/xchange/loyalbit/LoyalbitAdapters.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinAdapters.java, xchange-taurus/src/main/java/com/xeiam/xchange/taurus/TaurusAdapters.java, xchange-taurus/src/test/java/com/xeiam/xchange/taurus/TaurusAdapterTest.java
A proposal of differentiating the available and frozen amount in wallet.
refs #919
=> Add available, frozen fields to Wallet.

xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineExchange.java
Endpoint URL was a staging endpoint.
=> Replace obsolete staging endpoint with api.quoine.com

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/dto/trade/BitsoUserTransaction.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/bitso/trade/BitsoUserTradeHistoryDemo.java
This caused a NPE when attempting to access the user's trade history.
=> Bitso: Fix an incorrectly named json property.

xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java
ItBitTicker timestamp might be null sometimes now.
=> ItBit ticker timestamp might be null

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinAdapters.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/account/OkcoinFuturesFundsCross.java
Typo in extracting margin field when querying for cross margin funds.
=> OkCoin: Fix futures typo

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinUtils.java
Right now it just says "Unknown error" instead of extract an error code.
=> OkCoin: Extract futures error codes

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinExchange.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoinStreamingUtils.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/marketdata/OkCoinStreamingDepth.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/marketdata/OkCoinStreamingTicker.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/ChannelProvider.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/FuturesChannelProvider.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinStreamingExchangeService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinWebSocketService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/SpotChannelProvider.java
Support for websocket market data across all OkCoin configurations:
- OkCoin China
- OkCoin International Spot
- OkCoin International Futures
and improved error handling when decoding the json data
=> OkCoin: Market data streaming for Cn, Intl, Intl Futures

xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineAdapters.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineAuthenticated.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineExchange.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/dto/account/QuoineTradingAccountInfo.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/dto/trade/QuoineNewMarginOrderRequest.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/dto/trade/QuoineNewOrderRequest.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineAccountService.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineAccountServiceRaw.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineTradeService.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/service/polling/QuoineTradeServiceRaw.java
- Use `Use_Margin` param to indicate you want to trade on margin. Buy/Sells will automatically borrow.
- Use `Leverage_Level` to set the leverage
If `Use_Margin` false (default) then it will trade spot only.
=> Quoine: Enable margin trading and account info

xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseEx.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseExAdapters.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseExExchange.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/account/CoinbaseExAccount.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExIdResponse.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExOrder.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExPlaceOrder.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/CoinbaseExDigest.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExAccountService.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExAccountServiceRaw.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExBasePollingService.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExMarketDataService.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExMarketDataServiceRaw.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExTradeService.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExTradeServiceRaw.java
_Don't merge yet, see comments below_
- retrieve full orderbook from MarketDataService
- start of AccountService. I am really having issues getting the authentication (in `CoinbaseExDigest`) to work. Not sure what I'm doing wrong. You are supposed to decode the base64 secret key before instantiating a `SecretKeySpec`. Then just base64 encode the digest result. I'm putting this here in case someone else could have a look -- otherwise I'll get back to it later.
=> Coinbase Exchange: retrieve full orderbook, start of account service

xchange-core/src/main/java/com/xeiam/xchange/currency/Currencies.java, xchange-core/src/main/java/com/xeiam/xchange/currency/CurrencyPair.java
Stellar is available on various exchanges yet. Like on kraken.com as STR.
=> added currency: Stellar

xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyCurrencyUtils.java, xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/service/polling/CryptsyAccountService.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenAuthenticated.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/KrakenDepositAddress.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/KrakenDepositMethods.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/Withdraw.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/WithdrawInfo.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/results/KrakenDepositAddressResult.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/results/KrakenDepositMethodsResults.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/results/WithdrawInfoResult.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/account/results/WithdrawResult.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenAccountService.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenAccountServiceRaw.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/service/polling/KrakenBasePollingService.java
I added mapping for BTC/EUR and marketId 478 for cryptsy-exchange.
=> added mapping for marketIds and currencyPairs

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoMarketDataService.java, xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoMarketDataServiceRaw.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/bitso/marketdata/BitsoMarketDataDemo.java
Basically identical to how it's done with Bitstamp...
=> Added getTrades for Bitso

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/Bitso.java
=> Added BitsoException to Bitso

xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseExAdapters.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExBasePollingService.java, xchange-coinbaseex/src/test/java/com/xeiam/xchange/coinbaseex/CoinbaseExExchangeTest.java, xchange-coinbaseex/src/test/java/com/xeiam/xchange/coinbaseex/service/marketdata/CoinbaseExAvailableProductsIntegration.java
Load the exchange symbols from the exchange directly instead of loading the exchange symbols from a file.
=> Loading CoinbaseEx exchange symbols from the exchange itself

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java
modified:   xchange-bitso/src/main/java/com/xeiam/xchange/bitso/BitsoAdapters.java
=> Fixed lazy copy and pasting naming errors in BitsoAdapters

xchange-coinmate/src/test/java/com/xeiam/xchange/coinmate/service/polling/CoinmateBasePollingServiceIntegration.java, xchange-coinmate/src/test/java/com/xeiam/xchange/coinmate/service/polling/TradeServiceIntegration.java, xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/Trade.java, xchange-core/src/main/java/com/xeiam/xchange/dto/trade/UserTrade.java, xchange-core/src/test/java/com/xeiam/xchange/dto/trade/UserTradeTest.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/com/xeiam/xchange/kraken/dto/trade/KrakenUserTrade.java, xchange-kraken/src/test/java/com/xeiam/xchange/kraken/KrakenAdaptersTest.java
* removed additional data map from Trade, as discussed #990
* replaced it with KrakenUserTrade
* added inheritance to Trade.Builders
* renamed Coinmate integration test classes, as mentioned #982
=> [core,kraken,coinmate] removed additional data map from Trade

xchange-mexbt/src/main/java/com/xeiam/xchange/mexbt/dto/BigDecimalAsStringSerializer.java, xchange-mexbt/src/main/java/com/xeiam/xchange/mexbt/dto/account/MeXBTWithdrawRequest.java, xchange-mexbt/src/test/java/com/xeiam/xchange/mexbt/dto/account/MeXBTWithdrawRequestTest.java
=> [MeXBT] Serialize the amount(BigDecimal) as string for withdraw request.

xchange-bitkonan/src/main/java/com/xeiam/xchange/bitkonan/BitKonan.java, xchange-bitkonan/src/main/java/com/xeiam/xchange/bitkonan/BitKonanAdapters.java, xchange-bitkonan/src/main/java/com/xeiam/xchange/bitkonan/service/polling/BitKonanMarketDataService.java, xchange-bitkonan/src/main/java/com/xeiam/xchange/bitkonan/service/polling/BitKonanMarketDataServiceRaw.java, xchange-bitkonan/src/test/java/com/xeiam/xchange/bitkonan/BitKonanAdapterTest.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/bitkonan/marketdata/BitKonanMarketdataDemo.java
- accept LTC in getTicker and getOrderBook
- remove local date from orders in the order book
- add trustAllCerts in example code
=> BitKonan improvements

xchange-core/src/main/java/com/xeiam/xchange/dto/meta/ExchangeMetaData.java, xchange-core/src/main/java/com/xeiam/xchange/dto/meta/RateLimit.java, xchange-core/src/test/java/com/xeiam/xchange/dto/meta/ExchangeMetaDataTest.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/anx/v2/ANXMetaDataDemo.java
=> Add computing minimum poll delay from rateLimits

xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEAdapters.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEExchange.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcAdapters.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcExchange.java
make local metaData available before calling remoteInit()
=> [BTC-e, Hitbtc] initialize Exchange.metaData field in loadMetaData()

xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitTradeService.java
Previous code was causing a ClassCastException.
=> [itbit] properly cast List of open orders to Array

xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/HitbtcAuthenticated.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/dto/account/HitbtcDepositAddressResponse.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcAccountService.java, xchange-hitbtc/src/main/java/com/xeiam/xchange/hitbtc/service/polling/HitbtcAccountServiceRaw.java
=> Deposit address request implemented for Hitbtc

xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/OkCoin.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/dto/account/OKCoinWithdraw.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OKCoinBaseTradePollingService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinAccountService.java, xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/polling/OkCoinAccountServiceRaw.java
I have added a basic withdrawal support for OKCoin. 
This should go to version 3.1.0
=> - adding withdrawal support

xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/dto/account/ItBitWithdrawalRequest.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitAccountServiceRaw.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitTradeServiceRaw.java
ItBit doesn't support more than 4 decimals of precision in crypto amounts. Is rounding up the right answer? It seems so to me.
=> Fix ItBit withdrawal issue for high precision amounts

xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/BTCEAuthenticated.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/dto/account/BTCEWithDrawInfoReturn.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/dto/account/BTCEWithdrawInfo.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCEAccountService.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCEAccountServiceRaw.java, xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BTCETradeService.java
I have implemented withdrwals on BTC-e.
=> BTC-e withdraw support

xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyAdapters.java
=> Cryptsy ticker adapter update

xchange-core/src/main/java/com/xeiam/xchange/dto/Order.java, xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/OrderBook.java, xchange-core/src/main/java/com/xeiam/xchange/dto/marketdata/OrderBookUpdate.java, xchange-core/src/main/java/com/xeiam/xchange/dto/trade/LimitOrder.java
small doc adjustments I ran into while trying to understand these classes
=> [core] clarify some comments, note some potential issues

xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyAdapters.java
cryptsyAccountInfo.getHoldFunds() return null if no funds on hold
=> Cryptsy: fix adaptAccountInfo NullPointerException

xchange-bleutrade/src/main/java/com/xeiam/xchange/bleutrade/BleutradeAdapters.java, xchange-bleutrade/src/main/java/com/xeiam/xchange/bleutrade/BleutradeExchange.java, xchange-bleutrade/src/main/java/com/xeiam/xchange/bleutrade/service/polling/BleutradeMarketDataServiceRaw.java, xchange-bleutrade/src/test/java/com/xeiam/xchange/bleutrade/service/marketdata/TickerFetchIntegration.java
- Add remoteInit using markets and currencies
- Fix integration test since usd was removed
- !! Did not update local json metadata, it is still invalid
=> [bleutrade] Retreive metadata remotely

xchange-cryptsy/src/main/java/com/xeiam/xchange/cryptsy/CryptsyAdapters.java
cryptsyWallet.getHoldFunds() return null if no funds on hold
=> Cryptsy: Fix fix adaptAccountInfo NullPointerException

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoAccountServiceRaw.java, xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountServiceRaw.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/dto/account/TheRockWithdrawal.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockAccountService.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockAccountServiceRaw.java
Still testing this a bit, please don't merge just yet.
=> Use Currency (instead of String) as parameter to raw withdrawal methods

xchange-bitso/src/main/java/com/xeiam/xchange/bitso/service/polling/BitsoAccountServiceRaw.java, xchange-bitstamp/src/main/java/com/xeiam/xchange/bitstamp/service/polling/BitstampAccountServiceRaw.java, xchange-examples/src/main/java/com/xeiam/xchange/examples/therock/TheRockMarketDataDemo.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/TheRock.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/TheRockAdapters.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/dto/account/TheRockWithdrawal.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/dto/marketdata/TheRockBid.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/dto/marketdata/TheRockOrderBook.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockAccountService.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockAccountServiceRaw.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockMarketDataService.java, xchange-therock/src/main/java/com/xeiam/xchange/therock/service/polling/TheRockMarketDataServiceRaw.java
#1122 Should be merged before merging this PR.
=> Therock orderbook

xchange-cryptofacilities/pom.xml, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/CryptoFacilitiesAdapters.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesAccountService.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesMarketDataServiceRaw.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeService.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeServiceRaw.java, xchange-cryptofacilities/src/test/java/com/xeiam/xchange/cryptofacilities/service/marketdata/FetchIntegration.java
Previous version was based on old version. I merged to new snapshot.
=> Merged to new snapshot

xchange-bitfinex/src/main/resources/bitfinex.json, xchange-cexio/src/main/resources/cexio.json, xchange-clevercoin/src/main/resources/clevercoin.json
I've updated some json files with minimal order amounts so meta data is complete for all pairs my own trading bot is using.
=> Updated some json files with minimal order amount.

xchange-bittrex/src/main/java/com/xeiam/xchange/bittrex/v1/BittrexAdapters.java
Corrected balance information with frozen amount in orders. 
Current implementation gives :Bittrxjava.lang.IllegalArgumentException: total != available + frozen - borrowed + loaned + withdrawing + depositing if there is a frozen amount in orders.
=> Get correct balance information.

xchange-cexio/src/main/resources/cexio.json
cex.io removed again some markets: https://support.cex.io/hc/en-us/articles/214379428-Multipool-Suspension-and-Altcoin-Removali
=> Updated to latest active markets on cex.io

xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseEx.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/CoinbaseExAdapters.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExFill.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExPlaceOrder.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/dto/trade/CoinbaseExTradeHistoryParams.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExTradeService.java, xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExTradeServiceRaw.java
Support for market orders and retrieving trade history for coinbaseex
=> Support for market orders and retrieving trade history for coinbaseex

xchange-cryptofacilities/src/test/java/com/xeiam/xchange/cryptofacilities/service/marketdata/FetchIntegration.java
Fixes uppercase changes introduced in: #1148 Creates new currencies in
uppercase. Solves bug when calling getBalan…
=> #1162 CryptoFacilities: getOrderBook returns null for all tradeable forward contracts

xchange-gatecoin/src/main/java/com/xeiam/xchange/gatecoin/service/polling/GatecoinTradeService.java
Symbols and amount were wrong reported on open orders
=> Corrected wrong reported open orders.

xchange-core/src/main/java/com/xeiam/xchange/currency/Currency.java
Updated Doge with alternative code XDG (used on Kraken)
=> Updated Doge with alternative code XDG (used on Kraken)

xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/CryptoFacilitiesAdapters.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesCumulativeBidAsk.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeService.java, xchange-cryptofacilities/src/main/java/com/xeiam/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeServiceRaw.java, xchange-cryptofacilities/src/test/java/com/xeiam/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesCumulativeBidAskJSONTest.java
- Work around CF fwd contract case sensitivity in Currency pair
constructor.
- CryptoFacilites https api returns order book bids in reverse order.
Reorder them to standard (descending) order.
- Implement cancelOrder(orderID)
- Implement createTradeHistoryParams()
- Protect against NPE
=> [CryptoFacilities] fixes and enhancements

xchange-kraken/src/main/resources/kraken.json
Updated to latest information from kraken:
http://blog.kraken.com/post/139889536697/kraken-fee-change-important-updates
=> Updated kraken json file

xchange-bitfinex/src/main/resources/bitfinex.json
Bitfinex support for ETH in json file
=> Bitfinex support for ETH in json file

xchange-bitfinex/src/main/resources/bitfinex.json
Bitfinex changed the minimal order size of eth to 0.1
=> Bitfinex changed the minimal order size of eth to 0.1

.gitignore, xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/PoloniexAdapters.java, xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/dto/marketdata/PoloniexMarketData.java, xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/service/polling/PoloniexBasePollingService.java, xchange-poloniex/src/main/java/com/xeiam/xchange/poloniex/service/polling/PoloniexMarketDataServiceRaw.java
Resolve empty array mapping issue exception failure 
Map 24h market data values returned from exchange to API fields
I finally figured out how to put this into a branch and submit the pull request
was discussed in issue  #1167
=> Issue  #1167 poloniex bug fixes 

xchange-core/src/main/java/com/xeiam/xchange/currency/CurrencyPair.java, xchange-quoine/src/main/java/com/xeiam/xchange/quoine/QuoineUtils.java, xchange-quoine/src/main/resources/quoine.json
=> Update Quoine products with ETH. Add ETH currency pairs.

xchange-bitmarket/src/main/java/com/xeiam/xchange/bitmarket/BitMarketAdapters.java, xchange-bitmarket/src/main/java/com/xeiam/xchange/bitmarket/service/polling/BitMarketTradeServiceRaw.java, xchange-bitmarket/src/test/java/com/xeiam/xchange/bitmarket/service/polling/BitMarketTradeTest.java
This fixes wrong conversion in BitMarketTradeServiceRaw.java from ask to buy and fixes also wrong if statement in BitMarketAdapters.java.
Really fixes https://github.com/timmolter/XChange/issues/1140.
=> XChange-bitmarket: fix buy-bid and ask-sell conversion

xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBit.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitExchange.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/dto/marketdata/ItBitTrades.java, xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/service/polling/ItBitMarketDataServiceRaw.java
The endpoints for trades and order book have been updated. GetTrades() wraps the response in an object with a count now.
There are sometimes that the API returns 404 of course. Any pointer on how to bind these 404 responses to java classes or exceptions with rescu?..
=> ItBit: Update market data API endpoints.

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/Poloniex.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexUtils.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/marketdata/PoloniexChartData.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexChartDataPeriodType.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexMarketDataServiceRaw.java
Poloniex candlestick chart data request
=> Poloniex candlestick chart data request

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexTradeService.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexTradeServiceRaw.java
Added possibility to obtain Maker/Taker fee for the user.
=> New feature #1207 - POLONIEX: support maker/taker fee schedule.

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilities.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenPosition.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenPositions.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/polling/CryptoFacilitiesMarketDataServiceRaw.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/polling/CryptoFacilitiesTradeServiceRaw.java, xchange-cryptofacilities/src/test/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenPositionsJSONTest.java, xchange-cryptofacilities/src/test/resources/marketdata/example-openPositions-data.json
+ IOException propagation bug fix
=> [CryptoFacilities] Implementation of new v2 OpenPositions raw end point

xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/polling/ANXBasePollingService.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/polling/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/polling/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/polling/BitfinexTradeServiceRaw.java, xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/polling/BleutradeAccountServiceRaw.java, xchange-bleutrade/src/main/java/org/knowm/xchange/bleutrade/service/polling/BleutradeTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java, xchange-core/src/main/java/org/knowm/xchange/exceptions/ExchangeException.java, xchange-core/src/main/java/org/knowm/xchange/exceptions/FundsExceededException.java, xchange-empoex/src/main/java/org/knowm/xchange/empoex/service/polling/EmpoExAccountServiceRaw.java, xchange-empoex/src/main/java/org/knowm/xchange/empoex/service/polling/EmpoExTradeServiceRaw.java, xchange-lakebtc/src/main/java/org/knowm/xchange/lakebtc/service/polling/LakeBTCTradeServiceRaw.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexAccountServiceRaw.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexMarketDataServiceRaw.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexTradeServiceRaw.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/polling/QuoineAccountServiceRaw.java, xchange-vaultoro/src/main/java/org/knowm/xchange/vaultoro/service/polling/VaultoroAccountServiceRaw.java, xchange-vaultoro/src/main/java/org/knowm/xchange/vaultoro/service/polling/VaultoroTradeServiceRaw.java
Some exception handling from #1294
=> Altered exception handling

xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-examples/src/main/java/org/knowm/xchange/examples/independentreserve/account/IndependentReserveAccountDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/independentreserve/marketdata/DepthDemoEth.java, xchange-examples/src/main/java/org/knowm/xchange/examples/independentreserve/trade/IndependentReserveTradeDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/independentreserve/trade/IndependentReserveTradeDemoEth.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/polling/IndependentReserveMarketDataServiceRaw.java, xchange-independentreserve/src/main/resources/independentreserve.json
fixed order book to support ETH
fixed available and total balance bug
updated exchange metadata
added ETH_AUD and ETH_NZD currency pairs
=> [IndependentReserve] fixed order book to support ETH

xchange-examples/src/main/java/org/knowm/xchange/examples/therock/account/TheRockAccountDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/therock/marketdata/TheRockMarketDataDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/therock/trade/TheRockTradeDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/therock/trade/TheRockTradeRawDemo.java, xchange-therock/src/main/java/org/knowm/xchange/therock/TheRock.java, xchange-therock/src/main/java/org/knowm/xchange/therock/TheRockAdapters.java, xchange-therock/src/main/java/org/knowm/xchange/therock/TheRockAuthenticated.java, xchange-therock/src/main/java/org/knowm/xchange/therock/dto/trade/TheRockMeta.java, xchange-therock/src/main/java/org/knowm/xchange/therock/dto/trade/TheRockMetaItem.java, xchange-therock/src/main/java/org/knowm/xchange/therock/dto/trade/TheRockOrder.java, xchange-therock/src/main/java/org/knowm/xchange/therock/dto/trade/TheRockOrders.java, xchange-therock/src/main/java/org/knowm/xchange/therock/service/polling/TheRockTradeService.java, xchange-therock/src/main/java/org/knowm/xchange/therock/service/polling/TheRockTradeServiceRaw.java, xchange-therock/src/test/java/org/knowm/xchange/therock/dto/TheRockDtoTest.java, xchange-therock/src/test/java/org/knowm/xchange/therock/service/trade/AbstractTheRockTradeServiceIntegrationTest.java, xchange-therock/src/test/java/org/knowm/xchange/therock/service/trade/TheRockTradeServiceIntegrationTest.java, xchange-therock/src/test/java/org/knowm/xchange/therock/service/trade/TheRockTradeServiceRawIntegrationTest.java, xchange-therock/src/test/resources/TheRockOrders.json
Hi Tim,
I have done the following updates:
- Added place, get and cancel operations into raw trade service (with related changes to lower objects)
- Refactored place operation and added comments into trade service (with related changes to lower objects)
- Extension to TheRock dto's
- Added a DTO test 
- Added a template for service integration test
- Added related examples to xchange-examples
Let me know if anything has to be improved.
Andrea
=> Updating TheRock trade services

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexUtils.java
=> Reverted 'fix' for base/counter in PoloniexUtils.

xchange-therock/src/main/java/org/knowm/xchange/therock/TheRock.java
please see comments here: https://github.com/timmolter/XChange/pull/1307
=> Fix for TheRock api

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexTradeService.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/polling/PoloniexTradeServiceRaw.java, xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/dto/trade/PoloniexOrderTest.java
* postOnly and immediateOrCancel flags to order amend
* null pointer fix for trade history
=> [poloniex] added flags to raw order amend methods, trade history null check

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java
I need adaptTrade method for streaming support.
=> Coinmate: Extract adaptTrade method from adaptTrades.

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/marketdata/PoloniexMarketData.java
Can't use that class fully because of missing setters.
=> Missing setters for PoloniexMarketData.

xchange-examples/src/main/java/org/knowm/xchange/examples/quoine/QuoineExamplesUtils.java, xchange-examples/src/main/java/org/knowm/xchange/examples/quoine/account/AccountInfoDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/quoine/trade/QuoineOrdersListDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/quoine/trade/TradeDemo.java, xchange-quoine/pom.xml, xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineAdapters.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineAuthenticated.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineExchange.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/account/FiatAccount.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/account/QuoineAccountBalance.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/account/QuoineTradingAccountInfo.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/marketdata/QuoineOrderBook.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/trade/QuoineNewMarginOrderRequest.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/trade/QuoineNewOrderRequest.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/trade/QuoineNewOrderRequestWrapper.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineAccountService.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineAccountServiceRaw.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineBaseService.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineSignatureDigest.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineTradeService.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineTradeServiceRaw.java, xchange-quoine/src/test/java/org/knowm/xchange/quoine/dto/account/QuoineWalletJSONTest.java, xchange-quoine/src/test/java/org/knowm/xchange/quoine/dto/marketdata/QuoineOrderBookJSONTest.java, xchange-quoine/src/test/resources/account/example-account-data.json
API has changed, fields and authentication. 
I will need to revise `QuoineOrderResponse` as well to reflect the new fields when executing orders.
=> Refactor Quoine API to use new JWT based authentication

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/BitstampBalance.java, xchange-bitstamp/src/main/resources/bitstamp.json, xchange-bitstamp/src/test/java/org/knowm/xchange/bitstamp/BitstampAdapterTest.java, xchange-bitstamp/src/test/resources/account/example-accountinfo-data.json
PR as requested, to close https://github.com/timmolter/XChange/issues/1368.
Note: also edited bitstamp.json (hard-coded json for books & currencies).
=> Add XRP balances to Bitstamp.AccountInfo

README.md
Can I have this small kind of advertisement? I've release first version 4.2.0 based on your release.
=> Link to xchange-stream added.

xchange-quoine/src/main/java/org/knowm/xchange/quoine/Quoine.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/service/QuoineMarketDataServiceRaw.java
Some API calls didn't catch HTTP errors which can lead to issues no the calling side.
=> Catch all HTTP status errors in the Quoine API

xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/account/KrakenTradeVolume.java, xchange-kraken/src/test/java/org/knowm/xchange/kraken/dto/account/KrakenAccountJSONTest.java, xchange-kraken/src/test/resources/account/example-tradevolume-data.json
Added market maker fee to existing KrakenTradeVolume class. Market taker fee was already being read.
=> [kraken] add market maker fee component to KrakenTradeVolume

pom.xml, xchange-bitcoincore/README.md, xchange-bitcoincore/api-specification.txt, xchange-bitcoincore/pom.xml, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/BitcoinCore.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/BitcoinCoreAdapters.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/BitcoinCoreWallet.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/dto/BitcoinCoreException.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/dto/account/BitcoinCoreBalanceRequest.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/dto/account/BitcoinCoreBalanceResponse.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/dto/account/BitcoinCoreUnconfirmedBalanceRequest.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/service/BitcoinCoreAccountService.java, xchange-bitcoincore/src/main/java/org/knowm/xchange/bitcoincore/service/BitcoinCoreAccountServiceRaw.java, xchange-bitcoincore/src/main/resources/bitcoincore.json, xchange-bitcoincore/src/test/java/org/knowm/xchange/bitcoincore/BitcoinAdaptersTest.java, xchange-bitcoincore/src/test/java/org/knowm/xchange/bitcoincore/dto/account/BitcoinCoreBalanceResponseTest.java, xchange-bitcoincore/src/test/java/org/knowm/xchange/bitcoincore/dto/account/BitcoinCoreErrorTest.java, xchange-bitcoincore/src/test/resources/account/example-error.json, xchange-bitcoincore/src/test/resources/account/example-getbalance.json, xchange-bitcoincore/src/test/resources/account/example-getunconfirmedbalance.json
I'm not sure whether this is something that fits into XChange or not but I wanted something that would fetch a BitcoinCore wallet balance in the same way as an exchange. Thoughts?
=> BitcoinCore RPC interface to access wallet balance

xchange-bitstamp/src/main/resources/bitstamp.json
XRP order size minimal 5 euro, changed to new xrp values.
=> XRP order size minimal 5 euro.

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java, xchange-kraken/src/main/resources/kraken.json
Added DASH. Like USDT not fitting in x... schema.
=> Kraken added DASH

xchange-btce/src/main/java/org/knowm/xchange/btce/v3/BTCEAdapters.java, xchange-btce/src/main/java/org/knowm/xchange/btce/v3/BTCEAuthenticated.java, xchange-btce/src/main/java/org/knowm/xchange/btce/v3/dto/trade/BTCEOrderInfoResult.java, xchange-btce/src/main/java/org/knowm/xchange/btce/v3/dto/trade/BTCEOrderInfoReturn.java, xchange-btce/src/main/java/org/knowm/xchange/btce/v3/service/BTCETradeService.java, xchange-btce/src/main/java/org/knowm/xchange/btce/v3/service/BTCETradeServiceRaw.java, xchange-btce/src/test/java/org/knowm/xchange/btce/v3/BTCEAdapterTest.java, xchange-btce/src/test/java/org/knowm/xchange/btce/v3/dto/trade/BTCETradeDataJSONTest.java, xchange-btce/src/test/resources/v3/trade/example-order-info-data.json
Hi, nice lib :).
I tried to copy formatter manually, because I use NetBeans ;).
Tell me if you find some problem.
=> [btce] Implemented TradeService.getOrder().

xchange-yobit/src/main/java/org/knowm/xchange/yobit/YoBit.java, xchange-yobit/src/main/java/org/knowm/xchange/yobit/YoBitAdapters.java, xchange-yobit/src/main/java/org/knowm/xchange/yobit/dto/marketdata/YoBitTicker.java, xchange-yobit/src/main/java/org/knowm/xchange/yobit/dto/marketdata/YoBitTickers.java, xchange-yobit/src/main/java/org/knowm/xchange/yobit/service/YoBitMarketDataService.java, xchange-yobit/src/main/java/org/knowm/xchange/yobit/service/YoBitMarketDataServiceRaw.java, xchange-yobit/src/test/java/org/knowm/xchange/yobit/service/marketdata/TickerFetchIntegration.java
This PR grants you the capability to call Ticker APIs for YoBit Exchange.
=> YoBit Exchange - added Ticker call

xchange-bitstamp/src/main/resources/bitstamp.json
=> Increased minimal xrp order size to 200

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
Fixes #1452.
The existing code seems full of similar hacked corner cases, I'm sorry for one more.
=> Fix Kraken GNO parsing

xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXExchange.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXAccountServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXDigest.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXMarketDataServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/GDAXAdaptersTest.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/dto/trade/GDAXFillTest.java, xchange-gdax/src/test/resources/trade/example-fills.json
* Trade history changes - buy/sell side fix (as per #1451), added trade fee, increased trade history params flexibility.
* Date parsing more consistent and using switch statements
* Added some tests and removed compiler warnings
=> [GDAX] trade history and date parsing changes

xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/GDAXException.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXOrderFlags.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceOrder.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXTradeHistoryParams.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXAccountServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/dto/GDAXExceptionTest.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceOrderTest.java, xchange-gdax/src/test/resources/trade/example-order-entry-reject.json
- improved reject reporting with custom exception
- added order flags for IOC, FOK and post only 
- trade query param change to make consistent with common interface + fix #1324
=> [GDAX] reject handling improvements + order flags + trade param modification

pom.xml, xchange-btcc/pom.xml, xchange-btcc/src/main/java/org/knowm/xchange/btcc/BTCC.java, xchange-btcc/src/main/java/org/knowm/xchange/btcc/BTCCAdapters.java, xchange-btcc/src/main/java/org/knowm/xchange/btcc/BTCCExchange.java, xchange-btcc/src/main/java/org/knowm/xchange/btcc/dto/marketdata/BTCCTicker.java, xchange-btcc/src/main/java/org/knowm/xchange/btcc/service/BTCCBaseService.java, xchange-btcc/src/main/java/org/knowm/xchange/btcc/service/BTCCMarketDataService.java, xchange-btcc/src/test/java/org/knowm/xchange/btcc/MarketDataTest.java, xchange-btcc/src/test/resources/ticker.json
=> Add BTCC exchange ticker

xchange-kraken/src/main/resources/kraken.json
Updated kraken.json with new xrp fiat pairs
=> Updated kraken.json with new xrp fiat pairs

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
Anchor any crypto to USD value
=> Tether USD Anchor

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOArchivedOrder.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXDigest.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java
* implement getTradeHistory for CexIO
* fix gdax and livecoin adapters so they don't destroy configured currency data
* fix gdax getTradeHistory so it honours order_id parameter, and also adds optional product_id parameter
=> some fixed and improvments

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOArchivedOrder.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOOpenOrder.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
* made CexIO honour OpenOrdersParamCurrencyPair in getOpenOrders
* implemented getOrder for cexio
* added some type safety to CexIOTradeHistoryParams - todo: get date parameters working
* got status and limit working for cexio archivedOrders (aka getTradeHistory)
* added fees to the response from getTradeHistory
...and
* add a new currency (IOC)
=> CexIO  improvements

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/account/CexIOBalanceInfo.java
Removed the hard coded list of supported currencies (which was incomplete) with code that copes with a balance in any currency.
=> refactored CexIOBalanceInfo so that it supports any currency

xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/Gatecoin.java, xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/GatecoinExchange.java
=> [Gatecoin] Fix incorrect API host url

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java, xchange-kraken/src/test/java/org/knowm/xchange/kraken/dto/trading/KrakenTradeJsonTest.java, xchange-kraken/src/test/resources/trading/example-openorders-data.json, xchange-kraken/src/test/resources/trading/example-openorders-in-transaction-currency-data.json
The way, how we deal with currencies at kraken is not the most elegant one...
I just added small changes to be able to handle the EOS currency properly. A quick and dirty way...
In the future maybe we should refactor the whole currency thing at kraken, maybe using this API information https://api.kraken.com/0/public/AssetPairs
=> [kraken] added quick fix for EOS currency

xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
Available on Kraken for instance
=> Adding pair XRP_EUR

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/test/java/org/knowm/xchange/kraken/KrakenAdaptersTest.java, xchange-kraken/src/test/java/org/knowm/xchange/kraken/dto/trading/KrakenTradeJsonTest.java, xchange-kraken/src/test/resources/trading/example-openorders-data.json, xchange-kraken/src/test/resources/trading/example-openorders-in-transaction-currency-data.json
Not sure why this seems to have stopped working recently; possibly it was broken by 8b02aaf10dbbe87. Here's a fix.
=> Kraken open order pairs

xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
I implemented getOrder() in GDAXTradeService
=> Implemented getOrder() method in GDAXTradeService

xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiAdapters.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiAuthernticated.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiExchange.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/JubiUtils.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiOrder.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiOrderHistory.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiOrderStatus.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiOrderType.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiStatusType.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/dto/trade/JubiTradeResult.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiTradeHistoryParams.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiTradeService.java, xchange-jubi/src/main/java/org/knowm/xchange/jubi/service/JubiTradeServiceRaw.java, xchange-jubi/src/test/java/org/knowm/xchange/jubi/dto/trade/JubiOrderJsonTest.java, xchange-jubi/src/test/java/org/knowm/xchange/jubi/service/trade/TradeFetchIntegeration.java, xchange-jubi/src/test/resources/example-error-response.json, xchange-jubi/src/test/resources/example-open-order-list.json, xchange-jubi/src/test/resources/example-order-status.json, xchange-jubi/src/test/resources/example-trade-list.json
Implement jubi trade service and interfaces related to order query. 
Now jubi library supports fetching user's order history and order status by api keys.
=> add jubi trade service and implement order query interfaces

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/HitbtcAdapters.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/HitbtcAuthenticated.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/dto/trade/HitbtcMultiExecutionReportResponse.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeServiceRaw.java
- added support to cancel_orders api call
- updated the way some hitbtc api calls are read (some mechanisms were obsolete)
- lots size updated
=> new api call and better handling of api calls responses

xchange-anx/src/main/java/org/knowm/xchange/anx/v2/dto/account/ANXWithdrawalResponse.java, xchange-anx/src/main/java/org/knowm/xchange/anx/v2/dto/account/ANXWithdrawalResponseWrapper.java, xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXAccountService.java, xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXAccountServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeServiceRaw.java, xchange-quadrigacx/src/main/java/org/knowm/xchange/quadrigacx/service/QuadrigaCxAccountService.java
[anxpro] fixed error handling and response message for withdrawFrunds
[hitbtc] added lot size for XRP/BTC
... and added 'contains' method to Currency
=> [hitbtc, anxpro] some fixes and improvements

xchange-kraken/src/main/resources/kraken.json
Kraken increased almost all their minimal order amounts
See: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-
=> Updated with new minimal order amounts on kraken

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
Kraken: raw metaData: ExchangeMetaData [currencyPairs={USDT/USD=CurrencyPairMetaData [tradingFee=0.002, minimumAmount=5.0, maximumAmount=null, priceScale=4], XRP/USD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=6], XRP/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=30.00000000, maximumAmount=null, priceScale=6], ETC/ETH=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.300000000, maximumAmount=null, priceScale=8], XRP/CAD=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=null, maximumAmount=null, priceScale=6], ETH/BTC=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.020000000, maximumAmount=null, priceScale=6], DASH/EUR=CurrencyPairMetaData [tradingFee=0.0026, minimumAmount=0.030000000, …
=> Add also currency information to meta data

xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java
Adapt open order to include status and filled size.
=> [gdax] Adapt order status and filled size for limit order

xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/KrakenOrderType.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/KrakenStandardOrder.java
Add order type of settle position.
=> [kraken] Imeplement SettlePosition order

xchange-bter/src/main/resources/bter.json, xchange-coinfloor/src/main/resources/coinfloor.json, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/Cryptopia.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/CryptopiaAdapters.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/CryptopiaDigest.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/CryptopiaExchange.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/dto/CryptopiaBaseResponse.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaAccountService.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaAccountServiceRaw.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaMarketDataService.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaMarketDataServiceRaw.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaTradeService.java, xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service/CryptopiaTradeServiceRaw.java, xchange-gatecoin/src/main/resources/gatecoin.json, xchange-kraken/src/main/resources/kraken.json
New implementation of account service and trade service
=> [cryptopia] new implementation (and some metadata changes)

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAdapters.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexBalancesResponse.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexDepositHistory.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexWithdrawalHistory.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountService.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountServiceRaw.java
Just needed connected the code already there
=> Get Bittrex Withdrawals, Deposits & Balances working.

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
Currency/size of fee depends on buy or sell
=> Fix Poloniex trade history fee calculation.

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataService.java
If the length was > 1 it would ignore argument 0
=> [Gemini] Fixed args in getTrades

xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/Livecoin.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinDigest.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinExchange.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrderBook.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinRestriction.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinRestrictions.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinTicker.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinTrade.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinAccountService.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinAccountServiceRaw.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinBaseService.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinMarketDataService.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinMarketDataServiceRaw.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinPaginatedResponse.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinResponse.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinTradeService.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinTradeServiceRaw.java
@timmolter probably no point putting this in your release
=> [livecoin] first stab at implementing livecoin account and trade services

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
Improve limit order adapter to include order status, originalAmount and executedAmount
=> [Gemini] Improve adapt limit order

xchange-dsx/src/main/java/org/knowm/xchange/dsx/dto/trade/DSXCancelAllOrdersResult.java
Due to slight API incostitency, changes to Cancel all orders resulting JSON were made. This PR reflects these changes in XChange.
@Mikelle please approve
=> [DSX] reflects API changes in CancelAllOrdersResult

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/dto/trade/OkCoinFuturesOrder.java
Correcting typo in contract_name
=> Issue 1788

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/dto/trade/HitbtcExecutionReport.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeServiceRaw.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/AuthenticatedBaseTestCase.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/service/trade/HitbtcTradeServiceRawTest.java
@timmolter  Review this please
https://github.com/timmolter/XChange/issues/1803
=> Fixing order cancel API

xchange-kraken/src/main/resources/kraken.json
Kraken removed XRP/GBP and REP/CAD
=> Kraken removed 2 markets

xchange-core/src/main/java/org/knowm/xchange/ExchangeSpecification.java, xchange-core/src/main/java/org/knowm/xchange/service/BaseExchangeService.java
=> http proxy parameters passed to Rescu through ExchangeSpecification.

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/ArchivedOrdersRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexIORequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexioSingleOrderIdRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/PlaceOrderRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/account/CexIOBalanceInfo.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOAccountService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOAccountServiceRaw.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOBaseService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIODigest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java
refactoring the API to use application/json rather than form encoded parameters (as per the spec: https://cex.io/rest-api).
As a side effect I've fixed the `getTradeHistory` call (via `archivedOrders`) so that it now honours the date parameters
=> [cexio] do not merge yet - work in progress

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAdapters.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampUtils.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountService.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXCoinbaseAccount.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXCoinbaseAccountAddress.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXAccountService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXAccountServiceRaw.java
Bitstamp:
- Add support for funding history retrieval
GDAX:
- Small fixes in funding history retrieval
- Add support for requesting deposit addresses
=> New features for Bitstamp and GDAX

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAuthenticated.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRaw.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRawIntegration.java
@timmolter 
Sorry one more update.
Also a question as well. How do you feel about mocking out API server responses with a framework like WireMock? I could keep these tests running if I did that. But it would mean if the APIs changed, running the test would not identify that change.
=> Adding price to update order for Hitbtc

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcAccountService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcAccountServiceRaw.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeServiceRaw.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/Hitbtc.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRaw.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRaw.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/internal/HitbtcAdaptersTest.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRawIntegration.java
@timmolter  Reviewer
Also adding a test and some formatting.
=> Adding getTickers for MarketData Raw Service

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAdapters.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/trade/BittrexLimitOrder.java
Bug-fix in BittrexLimitOrder - Need to provide cumulative amount and not remaining amount
Bug-fix in BittrexAdapter
=> Bug fixes in Bittrex

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
=> Add Qtum currency

xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceIntegration.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeServiceRawIntegration.java
=> Adding Hitbtc V2 tests for BCC and BCH

xchange-bitso/src/main/java/org/knowm/xchange/bitso/Bitso.java, xchange-bitso/src/main/java/org/knowm/xchange/bitso/service/BitsoMarketDataService.java, xchange-bitso/src/main/java/org/knowm/xchange/bitso/service/BitsoMarketDataServiceRaw.java, xchange-bitso/src/test/java/org/knowm/xchange/bitso/TickerFetchIntegration.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bitso/marketdata/BitsoMarketDataDemo.java
=> BitsoExchange to pass currency pair to api

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/account/PoloniexWallet.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/account/TransferResponse.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/account/WithdrawalResponse.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexAccountServiceRaw.java
Hope implementation is OK.
Just another endpoint in PoloniexAuthenticated
=> Implementing transfer between Poloniex wallets

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexV2.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexMarketDataServiceRaw.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/marketdata/BittrexMarketDataDemo.java
Closes #1919 , Bittrex Add support for API v2 GetLatestTick method
=> Closes #1919 , Bittrex Add support for API v2 GetLatestTick method

pom.xml, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-examples/pom.xml, xchange-examples/src/main/java/org/knowm/xchange/examples/koineks/KoineksDemoUtils.java, xchange-examples/src/main/java/org/knowm/xchange/examples/koineks/marketdata/KoineksTickerDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/paribu/marketdata/ParibuTickerDemo.java, xchange-koineks/api-specification.txt, xchange-koineks/pom.xml, xchange-koineks/src/main/java/org/knowm/xchange/koineks/Koineks.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/KoineksAdapters.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/KoineksExchange.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/BaseKoineksTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksBTCTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksCurrency.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksDASHTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksDOGETicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksETHTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksLTCTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/dto/marketdata/KoineksTicker.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/service/KoineksBaseService.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/service/KoineksMarketDataService.java, xchange-koineks/src/main/java/org/knowm/xchange/koineks/service/KoineksMarketDataServiceRaw.java, xchange-koineks/src/main/resources/koineks.json, xchange-koineks/src/main/resources/logback.xml, xchange-koineks/src/test/java/org/knowm/xchange/koineks/KoineksAdapterTest.java, xchange-koineks/src/test/java/org/knowm/xchange/koineks/dto/marketdata/KoineksTickerTest.java, xchange-koineks/src/test/java/org/knowm/xchange/koineks/service/marketdata/TickerFetchIntegration.java, xchange-koineks/src/test/resources/marketdata/example-ticker-data.json
Other methods are not supported with the exchange's API.
=> [koineks] marketdata (ticker only) implementation.

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/resources/binance.json
=> [Binance] download currency pair meta-data from exchange

xchange-bitstamp/src/main/resources/bitstamp.json, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeService.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bitfinex/marketdata/BitfinexDepthDemo.java
Also fix bitstamp ETH resource values.
Fix Bittrex trade history params - use default values instead ZERO.
=> Add BCH to Bitstamp

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
=> Currency pair coverage

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAuthenticated.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountServiceRaw.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeHistoryParams.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcTradeService.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountServiceIntegration.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountServiceRawIntegration.java
=> Adding params to getFunding history

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexMarginAccountResponse.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
=> poloniex margin account implementation

xchange-examples/src/main/java/org/knowm/xchange/examples/poloniex/trade/PoloniexTradeDemo.java, xchange-poloniex/pom.xml, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/dto/trade/PoloniexMarginPostionResponse.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
Implement Poloniex margin position #1995
=> [Polniex] Margin position implementation

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
The recvWindow parameter can be set using:
`specification.setExchangeSpecificParametersItem("recvWindow", 10000L);`
=> Added recvWindow to binance

xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/Bitflyer.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerPosition.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerDigest.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerTradeServiceRaw.java, xchange-bitflyer/src/test/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerPositionJSONTest.java, xchange-bitflyer/src/test/resources/trade/example-position.json, xchange-examples/src/main/java/org/knowm/xchange/examples/bitflyer/trade/BitflyerTradeDemo.java
=> [BitFlyer] Position retrieval implementation

xchange-acx/src/main/java/org/known/xchange/acx/AcxApi.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxExchange.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxMapper.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxSignatureCreator.java, xchange-acx/src/main/java/org/known/xchange/acx/dto/account/AcxAccount.java, xchange-acx/src/main/java/org/known/xchange/acx/dto/account/AcxAccountInfo.java, xchange-acx/src/main/java/org/known/xchange/acx/service/account/AcxAccountService.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxAccountServiceTest.java, xchange-acx/src/test/resources/account/account_info.json
Continuation of https://github.com/timmolter/XChange/pull/2007
This PR adds support for getting account info.
=> [acx] Add account service

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountServiceRaw.java
=> [CoinMate] added FundingHistory implementation

xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrade.java, xchange-core/src/test/java/org/knowm/xchange/dto/trade/UserTradeTest.java
I'm a user of XChange but this is my first contribution. 
I would benefit from these modifications, and I thought others would too. 
If I am not following accepted conventions, proper PR protocol, etc please let me know and I'll try to make necessary changes.
=> Implementing equals() and hashCode() for UserTrade.

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/WithdrawRequest.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountServiceRaw.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
Add support ripple withdrawal.
Add returning withdraw tx id.
Fix: wrong cumulative amount in open orders.
=> [Binance] add support ripple withdrawal. fix returning withdraw tx id.

xchange-bitbay/src/main/resources/bitbay.json
I have update bitbay.json file in order to  support the new currency pairs of the exchange.
=> i have update the bitbay.json file

xchange-acx/src/main/java/org/known/xchange/acx/AcxApi.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxMapper.java, xchange-acx/src/main/java/org/known/xchange/acx/dto/marketdata/AcxMarket.java, xchange-acx/src/main/java/org/known/xchange/acx/service/marketdata/AcxMarketDataService.java, xchange-acx/src/main/java/org/known/xchange/acx/utils/ArgUtils.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxMarketDataServiceTest.java
* Allow passing bid/ask limits.
* Fix bug with timestamp conversions
Thanks :)
=> [acx] Allow passing bid/ask limits.

xchange-acx/src/main/java/org/known/xchange/acx/AcxApi.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxExchange.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxMapper.java, xchange-acx/src/main/java/org/known/xchange/acx/service/marketdata/AcxMarketDataService.java, xchange-acx/src/main/java/org/known/xchange/acx/service/trade/AcxTradeService.java, xchange-acx/src/main/java/org/known/xchange/acx/utils/AcxUtils.java, xchange-acx/src/main/java/org/known/xchange/acx/utils/ArgUtils.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxAccountServiceTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxMarketDataServiceTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxTradingServiceTest.java, xchange-acx/src/test/resources/trade/cancel_order.json, xchange-acx/src/test/resources/trade/open_orders.json
Initial version of the acx trading service:
* get orders
* cancel order
=> [acx] Trading service: get&cancel orders

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
Hello, i have add some new coins or tokens.I will add some others also but maybe not today.
=> i have add some currencies

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexLimitOrder.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexNewOrderRequest.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexReplaceOrderRequest.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java
BitFinex allows to create an order with stop loss.
https://bitfinex.readme.io/v1/reference#rest-auth-new-order
=> [BitFinex] OCO orders support

xchange-acx/src/main/java/org/known/xchange/acx/AcxApi.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxExchange.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxMapper.java, xchange-acx/src/main/java/org/known/xchange/acx/AcxSignatureCreator.java, xchange-acx/src/main/java/org/known/xchange/acx/service/trade/AcxTradeService.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxTradingServiceTest.java, xchange-acx/src/test/resources/trade/create_order.json
=> [acx] Add support for order creation

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexOrderFlags.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java
https://bitfinex.readme.io/v1/reference#rest-auth-new-order
=> [BitFinex] Implemented trailing stop order support

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
https://coinmarketcap.com/currencies/basic-attention-token/
=> Add `Basic Attention Token` (BAT)

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/dto/trade/BitfinexOrderFlags.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java
=> [BitFinex] Implemented support for Stop orders

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexAccountService.java, xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v1/BitfinexAdaptersTest.java, xchange-bitfinex/src/test/resources/v1/account/example-account-info-balance.json
Wallets are now separated by types
Fixes #1535
=> [BitFinex] Implemented proper wallets adaptation

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAuthenticated.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeService.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
returnOrderTrades from the Poloniex Trading API wasn't correctly implemented.
=> Poloniex return order trades fix

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/BinanceBalance.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java, xchange-binance/src/test/java/org/knowm/xchange/test/binance/AccountServiceIntegration.java
=> [Binance] Currency returned in balance cannot use ==

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java
=> [Binance] Compensate for delta in system vs. server time

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java
```CexIOAdapters.adaptOrder``` is currently not decoding the order status for raw orders coming from ```CexIOTradeService.getOrder```.
Unfortunately, CEX.IO order statuses are not properly documented in the official API docs (https://cex.io/rest-api#archived-orders).
This is the reason why the decoding logins is implemented by numerically comparing the ```amount``` and ```remains``` fields of the ```CexIOOpenOrder``` bean.
=> [CEX.IO] Added order status decoding logic

xchange-binance/src/main/java/org/knowm/xchange/binance/Binance.java, xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceKline.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinancePrice.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/KlineInterval.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeHistoryParams.java
=> [Binance] Improve support for candle stick market data

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexioCryptoAddressRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/account/CexIOCryptoAddress.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOAccountService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOAccountServiceRaw.java
Creating new branch trying to get clean file change history.
=> [cexio] Implementing requestDepositAddress.

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java, xchange-binance/src/test/java/org/knowm/xchange/test/binance/MarketDataServiceIntegration.java, xchange-binance/src/test/java/org/knowm/xchange/test/binance/TradeServiceIntegration.java, xchange-examples/src/main/java/org/knowm/xchange/examples/binance/trade/BinanceTradeDemo.java
=> [Binance] Improve trade service API

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampBaseService.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampMarketDataServiceRaw.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXMarketDataServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/GDAXAdaptersTest.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
I'm working on improving the exception mappings for some exchanges (where the exchange specific HTTP response exceptions aren't being mapped to the Xchange specific exceptions).
=> Improved Exception Mappings

xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsAccountServiceRaw.java, xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsMarketDataServiceRaw.java, xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeServiceRaw.java
Saw your feedback for my cexio changes so making the same correction to abucoins.
=> [abucoins] Replacing improper use of IOException with preferred ExchangeException

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiAccountServiceRaw.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiBaseService.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataServiceRaw.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiTradeServiceRaw.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
Added insufficient funds exception mapping for Gemini (and basic framework for more exceptions in the future). 
Added rate limit exception mapping for Kraken.
=> Exception mapping improvements

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/Hitbtc.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRaw.java
This is to add the optional "limit" parameter while retrieving order book on Hitbtc.
=> Added "limit" parameter on Hitbtc getOrderBook

xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/BitbayAuthenticated.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/service/BitbayAccountService.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/service/BitbayAccountServiceRaw.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/service/account/params/BitbayWithdrawFundsSwiftParams.java
Adding support for 'withdraw' and 'transfer' which correspond to fiat withdrawal and crypto withdrawal.
=> [bitbay] Bitbay withdraw support

xchange-abucoins/src/main/resources/abucoins.json, xchange-abucoins/src/test/java/org/knowm/xchange/abucoins/AbucoinsExchangeMetaDataTest.java, xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java
Updating metadata on currency pairs and currencies from ab
Also added Nem, Stratis, and Golem as currencies to base package.
=> [abucoins] Updating metadata on currency pairs and currencies from abucoins

xchange-bitfinex/src/main/resources/bitfinex.json, xchange-gateio/src/main/resources/gateio.json, xchange-gdax/src/main/resources/gdax.json, xchange-hitbtc/src/main/resources/hitbtc.json, xchange-kraken/src/main/resources/kraken.json, xchange-livecoin/src/main/resources/livecoin.json, xchange-wex/src/main/resources/btce.json
update withdrawl fees in json files
based on exchange websites
notice: bitfinex has also deposit fees for depoists of crypto currencies in values less then 1000$
=> update withdrawl fees 

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java
Remaining amount was being set as cumulative amount
=> [cexio] Bugfix in CexIOAdapters

xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
=> [GDAX] Added Stop Order Support

xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/Bitcoinde.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/BitcoindeAdapters.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeAccountWrapper.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeAllocation.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeAllocations.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeBalance.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeBalances.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeData.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeEncryptedInformation.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeFidorReservation.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeAccountService.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeAccountServiceRaw.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeMarketDataServiceRaw.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeTradeService.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeTradeServiceRaw.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindeIdResponse.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindeMaintenance.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindeMyOpenOrdersWrapper.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindeMyOrder.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindeOrderRequirements.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/trade/BitcoindePage.java, xchange-bitcoinde/src/test/java/org/knowm/xchange/bitcoinde/RFC3339DateTimeParseTest.java, xchange-bitcoinde/src/test/java/org/knowm/xchange/bitcoinde/dto/BitcoindeOpenOrdersTest.java, xchange-bitcoinde/src/test/java/org/knowm/xchange/bitcoinde/dto/account/BitcoindeAccountTest.java, xchange-bitcoinde/src/test/resources/account.json, xchange-bitcoinde/src/test/resources/orders.json
Added support for AccountInfo, OpenOrders and placement of LimitOrders
=> Added classes to get AccountInfo from Bitcoinde

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAdapters.java
the full list of all symbols:
https://api.hitbtc.com/api/2/public/symbol
USDT as counter was added
=> [hitbtc] new symbols are added with USDT as counter

xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/Bitflyer.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerAdapters.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerBalance.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountService.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountServiceRaw.java
Is it better to do this bit by bit or wait until I've got a larger change? I'm exploring using Bitflyer for a trading bot so I'll need to implement a lot of the functionality that is currently missing. I prefer small PRs but I don't want to be a nuisance. :)
=> Add support for Bitflyer's "me/getbalance" endpoint.

xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/Bitcoinde.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeDigest.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeTradeService.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/BitcoindeTradeServiceRaw.java, xchange-bitcoinde/src/main/java/org/knowm/xchange/bitcoinde/service/CancelOrderByIdAndCurrencyPair.java
Added missing cancelOrder Method & fixed BitcoindeDigest
=> Added cancelOrder method

xchange-binance/src/main/java/org/knowm/xchange/binance/Binance.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceTicker24h.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java, xchange-examples/src/main/java/org/knowm/xchange/examples/binance/marketdata/BinanceMarketDataDemo.java
=> [Binance] + service ticker24h() without pair param

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountService.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountServiceRaw.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexDigest.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java, xchange-bitmex/src/main/resources/bitmex.json
This PR adds methods for placing several order types with BitMEX.
=> Adding features for Bitmex

xchange-abucoins/pom.xml
Minor cut-n-paste error in POM, low risk.
=> [abucoins] Fixing name in pom which was cut-n-paste from another module.

xchange-anx/src/main/resources/anxpro.json
See http://support.anxintl.com/customer/en/portal/articles/2919892-are-there-minimum-order-limits-
=> [ANXPRO] Minimum LTC order is 0.1.

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountService.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountServiceRaw.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/KucoinAdapters.java
…s documented.  there is a parmeter that cnanot be sent a null, so it was commented out.  Bitmex only offers btc wallets.
fixes #2264
kucoin: kucoin was reporting only available Balance, not total.
fixes #2279
=> fixes bitmex AccountInfo results and kucoin BalanceAdapter

xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/Bitflyer.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerAdapters.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerUtils.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerAddress.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerBankAccount.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerBaseHistoryResponse.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerCoinHistory.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerDepositOrWithdrawal.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerWithdrawRequest.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/account/BitflyerWithdrawResponse.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountService.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountServiceRaw.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerTradeHistoryParams.java
I noticed a fair amount of Bitflyer isn't implemented, so I took the APIs in the area I was interested and fleshed them out.  There remain a fair number of others I think are not implemented as well.
=> [bitflyer] Fleshing out history and wallet related APIs

xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/AbucoinsAdapters.java
Prior implementation created a Wallet for each AbucoinsAccount entry (with a single currency Balance in the wallet).
Revised logic groups AbucoinsAccounts by their profileID.  It then creates a wallet per profileID which has multiple balances.
This seems more consistent with other exchanges.
=> [abucoins] Improved abucoins AbucoinsAccount to AccountInfo mapping

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java
=> [Binance] Initialize min/max quantity and tickSize properly

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
=> [bitfinex] Adding withdrawal types missing from current API doc.

xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
=> [core] Do not initialize Order fields in constructor

xchange-examples/pom.xml, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/AbucoinsDemoUtils.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/account/AccountInfoDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/marketdata/DepthDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/marketdata/TickerDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/marketdata/TradesDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/trade/TradeDemo.java
I hadn't realized there was this independent project so just adding an Abucoins variant.
=> [examples] Adding abucoins to samples project.

xchange-bibox/src/main/java/org/knowm/xchange/bibox/Bibox.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/BiboxAuthenticated.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/dto/BiboxAdapters.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/dto/BiboxCommands.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/dto/BiboxMultipleResponses.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/dto/marketdata/BiboxOrderBookCommand.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/dto/marketdata/BiboxOrderBookCommandBody.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/service/BiboxMarketDataService.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/service/BiboxMarketDataServiceRaw.java, xchange-bibox/src/test/java/org/knowm/xchange/bibox/service/marketdata/MarketDataServiceIntegration.java
=> [Bibox] retrieve all order books

xchange-bibox/src/main/java/org/knowm/xchange/bibox/Bibox.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/service/BiboxMarketDataService.java, xchange-bibox/src/main/java/org/knowm/xchange/bibox/service/BiboxMarketDataServiceRaw.java, xchange-liqui/src/main/java/org/knowm/xchange/liqui/LiquiAdapters.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/LivecoinAdapters.java
- [Bibox] https://github.com/timmolter/XChange/issues/2260: can now fetch a selection of order books
- [Livecoin] Fixed https://github.com/timmolter/XChange/issues/2346 + code cleaning
- [Liqui] Partly fixed https://github.com/timmolter/XChange/issues/2282 + code cleaning
=> [Bibox, Livecoin, Liqui] Various fixes + enhancements

xchange-anx/src/main/java/org/knowm/xchange/anx/v2/ANXV2.java, xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXAccountService.java, xchange-anx/src/main/java/org/knowm/xchange/anx/v2/service/ANXAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexExchange.java
…nteger
the amount_int parameter actually gets created by multiplying the exact amount with 1000000000, so flows out of range in int, for large number of XRP.
=> [ANXPRO, bitfinex] multiple changes

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
Got confirmation from developers via customer support on what withdrawal type to use for bch.
=> [bitfinex] Adding bitcoin cash as withdrawal type.

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAuthenticated.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeServiceRaw.java
Reverts timmolter/XChange#2365
=> Revert "[kraken] Various bug fixes"

xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/AbucoinsAdapters.java, xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsBaseService.java, xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeService.java, xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsTradeServiceRaw.java, xchange-examples/src/main/java/org/knowm/xchange/examples/abucoins/trade/TradeDemo.java
=> [abucoins] Abucoins trade history

xchange-abucoins/src/main/java/org/knowm/xchange/abucoins/service/AbucoinsBaseService.java
In working on the CobinHood implementation I learned more about the client config.
Apply back some of that learning to Abucoins.
=> [abucoins] Appropriately configuring clientConfig for REST interfaces.

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinTradeService.java
=> [OkCoin/OKEX] fix small logic error for cancelOrder(CancelOrderParams)

xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/OrderBook.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoin.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/dto/trade/OkCoinBatchTradeResult.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinTradeService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinTradeServiceRaw.java
Added support for cancelling up to 3 orders at the same time.
=> [OKCoin/OKEX] support for batch cancel

xchange-bitfinex/src/main/resources/bitfinex.json, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexKline.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataService.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-hitbtc/src/main/resources/hitbtc.json, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoin.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinMarketDataServiceRaw.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineExchange.java
- Rate limit added for Bitfinex (after experiencing rate limit errors)
- Bucketed trades added in Bitmex
- More flexible historical candles call for GDAX
- Add k-lines for OkCoin
- A timeout setup for Quoine
=> Various fixes and improvements

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
i intend to keep these updated after contract settlement dates have passed
=> add currencies/pairs

xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/trade/KrakenStandardOrder.java
=> [kraken] fix npe when no close order is specified

xchange-bitz/src/main/resources/bitz.json
Sets all the currency pairs of the BitZ exchange.
=> Update currency pairs

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiBaseService.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
Found several instances of "insufficient funds" that were not handled correctly.
=> Fixes for insufficient funds exceptions.

xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java
=> [gdax] Place stop order was using averagePrice instead of stopPrice.

xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAdapters.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAuthenticated.java
=> [Gate.io] fixed trade history api call

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
=> [Binance] Add support for client assigned order id

xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Ticker.java, xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/ItBitAdapters.java, xchange-itbit/src/main/java/org/knowm/xchange/itbit/v1/dto/marketdata/ItBitTicker.java
Some exchanges provide the size in addition to the price for ticker calls. The size information should be passed along when available. Implemented the additional fields for itBit.
=> Ticker bidSize askSize

xchange-gdax/pom.xml, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAX.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceLimitOrder.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceMarketOrder.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceOrder.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeService.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/service/GDAXTradeServiceRaw.java, xchange-gdax/src/test/java/org/knowm/xchange/gdax/dto/trade/GDAXPlaceOrderTest.java
Prior code didn't expose 1:1 the full variety/capability of the underlying GDAX API (for placing orders).
I've refactored to mirror the underlying API 1:1.
=> [Gdax] place order refactor

xchange-core/src/main/java/org/knowm/xchange/service/marketdata/MarketDataService.java, xchange-core/src/main/java/org/knowm/xchange/service/marketdata/params/CurrencyPairsParam.java, xchange-core/src/main/java/org/knowm/xchange/service/marketdata/params/Params.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenMarketDataService.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenMarketDataServiceRaw.java
This extends #2388 and implements `getTickers` for Kraken
=> Add getTickers to MarketDataService and implement Kraken

.gitattributes
(cherry picked from commit 46d6213)
the line ending refactor
=> this will reduce whitespace churn

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java
Add refresh delta time function  back to binance
=> Add refresh delta time function back to binance

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
some expired contracts still remain, i don't want to remove them yet and risk breaking someones code.
=> update bitmex futures pairs

xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/BitbayAdapters.java
price = amount * rate
this is NOT the transaction fee
=> This is not the fee

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/TimeInForce.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
Add TimeInForce FOK enum (in case of [official api](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#enum-definitions))
Add posibility to place limit order with any TimeInForce flag
=> [Binance] Add support for placing limit order with TimeInForce flags.

xchange-coinbase/src/main/java/org/knowm/xchange/coinbase/v2/Coinbase.java
as per: https://www.coinbase.com/settings/api - the latest 
<quote>
API Version: 2018-04-08 [YOU'RE UP-TO-DATE]
<quote>
=> Update to reflect latest Coinbase API Version

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/KucoinAccountService.java
Fixed nullpointer by adding a simple check on type and removed pageNumber +1 increment when variable is null.
=> Nullpointer on fundingHistory request

xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/BitbayAdapters.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/BitbayAuthenticated.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/BitbayDigest.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/BitbayExchange.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/dto/BitbayBaseResponse.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/dto/trade/BitbayUserTrade.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/dto/trade/BitbayUserTrades.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/dto/trade/BitbayUserTradesQuery.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/service/BitbayBaseService.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/service/BitbayTradeHistoryParams.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/service/BitbayTradeService.java, xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/v3/service/BitbayTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trades.java, xchange-core/src/main/java/org/knowm/xchange/dto/trade/UserTrades.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/params/TradeHistoryParamNextPageCursor.java
Its still not officially published but its the only option if you want to download any users full trades history.
Current official API only gives you past 3-4 months of data.
=> First endpoint from new Bitbay API

xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/GatecoinAuthenticated.java, xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/dto/trade/GatecoinPlaceOrderRequest.java, xchange-gatecoin/src/main/java/org/knowm/xchange/gatecoin/service/GatecoinTradeServiceRaw.java
=> [gatecoin] Fixed placement of orders

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountServiceRaw.java
Replace system.currentTimeMilllis to getTimestamp function
=> Fix binance withdraw issue

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
fixes https://github.com/knowm/XChange/issues/2490
=> [gemini] fix gemini user trade fee sign

xchange-quoine/src/main/java/org/knowm/xchange/quoine/QuoineAdapters.java, xchange-quoine/src/main/java/org/knowm/xchange/quoine/dto/trade/Model.java, xchange-quoine/src/test/resources/org/knowm/xchange/quoine/dto/trade/example-orders-list.json
in order to get a currencyPair with more that 3 chars in base or counter currency
=> Modify the QuoineAdapterOpenOrder

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexBaseService.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java
Adding exception mapping with a few exceptions to all BitFinex API calls.
=> [BitFinex] Added exception mapping

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeService.java
[Bitmex] Order returned by getOrder has status always null
=> [Bitmex] getOrder retrurn order status

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
Added rest method implementation
=> [Bitmex]  updateLeveragePosition call  rest service "position/leverage"

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinAdapters.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinDigest.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OKCoinBaseTradeService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinTradeServiceRaw.java, xchange-okcoin/src/test/java/org/knowm/xchange/okcoin/service/account/OkCoinAdaptersTest.java
additional smaller changes, like adapter methods for fund records
signatureCreator is newly created for every method, otherwise race conditions due to shared MessageDigest instance
=> [okcoin] defined fees for withdrawals

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOExchange.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOFullOrder.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java, xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java, xchange-therock/src/main/java/org/knowm/xchange/therock/TheRockAdapters.java
[TheRockAdapters] add to the  the ability to translate orderStatus.
[GDAX] adapter managed status conversion with some errors. 
[CexIO] added private method getOrderFullDetail that retreives traded amount and fee and it calculates average order price
=> [TheRock] added adaptOrderStatus, [GDAX] partially filled order status. [CexIO] add getOrderFullDetail method

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/Hitbtc.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAuthenticated.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/dto/HitbtcCurrency.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcAccountServiceRaw.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRaw.java, xchange-hitbtc/src/test/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRawIntegration.java
1. Improving withdraw functionality - include fee has been added
2. getCurrency for market data has been added
=> Improving withdraw functionality + getCurrency

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/BinanceTicker24h.java
Binance ticker some fields not filled
=> Issue #2641

xchange-bitfinex/src/main/resources/bitfinex.json
=> [Bitfinex] market update

xchange-coingi/src/main/java/org/knowm/xchange/coingi/service/CoingiAccountService.java, xchange-coingi/src/main/java/org/knowm/xchange/coingi/service/CoingiMarketDataService.java, xchange-coingi/src/main/java/org/knowm/xchange/coingi/service/CoingiTradeService.java, xchange-examples/pom.xml, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/CoingiDemoUtils.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/account/CoingiBalancesDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/marketdata/CoingiPublicOrderBookDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/marketdata/CoingiPublicTradesDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/trade/CoingBuyBtcForEurDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/trade/CoingiGetOpenOrdersDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/coingi/trade/CoingiGetOrderByIdDemo.java
Hey, I've added examples for https://coingi.com
They show how to:
* buy / sell BTC for EUR
* check what's in your wallet (balances)
* fetch your open orders
* find an order by Order ID
* fetch the public OrderBook (i.e. what's available for sale / to buy right now on Coingi)
* fetch the last trades (i.e. what was just traded by Coingi users)
=> [coingi] added demo examples

xchange-therock/src/main/java/org/knowm/xchange/therock/service/TheRockTradeService.java
market order is not working in this version
=> price for market order must be 0 not null

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/common/dto/BitfinexException.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/common/service/BitfinexHmacPostBodyDigest.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/common/service/BitfinexPayloadDigest.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/Bitfinex.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexBaseService.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/Bitfinex.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/service/BitfinexBaseService.java
=> [Bitfinex] common code to API v1 and v2 implementations factorized

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java
=> fix bitmex OrderType bug

xchange-dsx/src/main/java/org/knowm/xchange/dsx/DSXAdapters.java, xchange-dsx/src/main/java/org/knowm/xchange/dsx/dto/marketdata/DSXPairInfo.java, xchange-dsx/src/main/java/org/knowm/xchange/dsx/service/DSXBaseService.java, xchange-dsx/src/test/java/org/knowm/xchange/dsx/DSXAdapterTest.java
mapping is done using the meta information provided by DSX: https://dsx.uk/mapi/info
=> [dsx] fixed mapping of DSX currency pairs

xchange-core/src/main/java/org/knowm/xchange/exceptions/NotAvailableFromExchangeException.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeService.java
See https://github.com/knowm/XChange/pull/2695
=> [Poloniex] Place market order not supported

xchange-exmo/src/main/java/org/knowm/xchange/exmo/service/ExmoTradeServiceRaw.java
quantity is the correct field for volume, amount is just quantity * price
=> fix open orders volume for exmo

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReserveOpenOrderRequest.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReservePlaceLimitOrderRequest.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveMarketDataServiceRaw.java
there are additional currencies to Xbt and Eth like: Bch, Xrp, Ltc.
the mapping should be done outside of xchange code, otherwise every new currency will require the code to be modified...
=> [independentreserve] Currency mapping 

xchange-quadrigacx/src/main/java/org/knowm/xchange/quadrigacx/QuadrigaCxAuthenticated.java, xchange-quadrigacx/src/main/java/org/knowm/xchange/quadrigacx/service/QuadrigaCxAccountService.java, xchange-quadrigacx/src/main/java/org/knowm/xchange/quadrigacx/service/QuadrigaCxAccountServiceRaw.java
due to the quadriga API design, one needs to add extra method for every currency, unfortunatelly...
=> [quadrigacx] added withdrawal support for additional currencies: BCH, BTG, LTC

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeServiceRaw.java
the idea behind the usage of the reflection here is clear, still a mater of taste, if you ask me...
i would avoid the usage of reflection, unless its really necessary. in this case, its not necessary.
another point, which let me change the code, is simply the exception handling.
here is the stack trace, i currently get, ie if there are not enough funds:
```
java.lang.IllegalStateException: Reflective code failed
at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.orderEntry(PoloniexTradeServiceRaw.java:201)
at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.buy(PoloniexTradeServiceRaw.java:114)
at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:99)
...
Caused by: java.lang.reflect.InvocationTargetException: null
at …
```
=> [poloniex] avoid the reflection

xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAdapters.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioAuthenticated.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/GateioExchange.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/GateioBaseResponse.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/account/GateioDeposit.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/account/GateioDepositsWithdrawals.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/account/GateioWithdrawal.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioAccountService.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioAccountServiceRaw.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioTradeServiceRaw.java
added support for funding history (deposits / withdrawals)
additionally thrown away the nonce factory stuff for gate.io, the API does not require any nonce parameter
=> [gateio] Added support for funding history

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveAccountService.java
partially rollback the changes of https://github.com/knowm/XChange/pull/2739
see my comments
=> [independentreserve] wallet

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAuthenticated.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/account/IndependentReserveWithdrawDigitalCurrencyRequest.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveAccountService.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveAccountServiceRaw.java
see conversation https://github.com/knowm/XChange/pull/2739
=> [independentreserve] fixed funding history

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
Added some missing currencies for Binance exchange
=> [Core] Added 3 currencies for Binance

pom.xml
add xchange-exx in core pom.xml
<module>xchange-exx</module>
=> add xchange-exx in core pom.xml

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeServiceRaw.java
Dependent on Pull Request https://github.com/knowm/XChange/pull/2793
=> CoinbasePro add list orders by status

xchange-coinbasepro/pom.xml, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/CoinbaseProTrades.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/CoinbaseProTransfers.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProMarketDataService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProMarketDataServiceRaw.java, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/CoinbaseProExchangeIntegration.java, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/service/marketdata/HistoricalCandlesIntegration.java, xchange-gdax/README.md
@timmolter @IanWorthington
Merging changes from GDAX Pull Request https://github.com/knowm/XChange/pull/2784 into CoinbasePro
After this change we could consider GDAX branch dead and merge new features into CoinbasePro
=> [CoinbasePro] Merging - Add support for GDAX paginated getTrades #2784 - from gdax

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceOrderFlags.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/OrderType.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java
see doc for LIMIT_MAKER order type https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade
=> [binance] added LIMIT_MAKER order type

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexIOGetPositionRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexIOOpenPositionRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioClosePosition.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioClosePositionResponse.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioOpenPosition.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioOpenPositionResponse.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioOpenPositionsResponse.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioPosition.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioPositionPair.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioPositionResponse.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexioPositionType.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
[CEXIO] Added CexioPosition
[KRAKEN] Fixed bug Partially filled status for Kraken limit orders [#2843](https://github.com/knowm/XChange/issues/2843)
=> [CEXIO] Added CexioPosition - [KRAKEN] Fixed bug #2843

xchange-examples/src/main/java/org/knowm/xchange/examples/upbit/trade/UpbitLimitOrderDemo.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitAdapters.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitAuthenticated.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitExchange.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/dto/UpbitException.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/dto/trade/UpbitOrderRequest.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/dto/trade/UpbitOrderResponse.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/dto/trade/UpbitOrderTrade.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitTradeService.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitTradeServiceRaw.java
=> [Upbit] Added limit order request, cancel order, order info

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/Gemini.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/Hitbtc.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataService.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinExchange.java
Hitbtc -> add extra params in API (for download historical trades)
OkCoin -> API for OKCoin (no for Okex)
Gemini -> query param "since" (no "timestamp")
=> add extra params for Hitbtc and some bug fix

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOOpenOrders.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOOrder.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java
Add new function to get all open order by one call, instead of call for each currency pair.
=> [Cex.io] Add open orders function

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
funny stuff actually
```
if (originalMeta != null) {
...
} else {
...
OriginalMeta.getFeeTiers()
...
}
```
npe very likely ;-)
=> [bitmex] fixed npe

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkCoinExchange.java
Revert URI (from OKCoin.com to okex.com). It would be nice to rename OkCoinExchange to OkexExchange. But now I do not have time for it.
=> revert changes (OkCoinExchange)

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAdapters.java
I believe quantity increment can be safely used as minimum amount.
=> Use quantity increment as minimum amount

xchange-coinbene/src/main/java/org/knowm/xchange/coinbene/dto/CoinbeneAdapters.java
NPE fix for request of not provided pair
=> [COINBENE] NPE fix

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexBaseService.java, xchange-core/src/main/java/org/knowm/xchange/exceptions/SystemOverloadException.java
I added SystemOverloadException to common xchange module to manage http error 502.
I added support to SystemOverloadException to bitmex
=> [xchange] added SystemOrverloadedException

xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/Bitflyer.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerAdapters.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/BitflyerUtils.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerChildOrder.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerChildOrderType.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerOrderMethod.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerParentOrder.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerParentOrderConditionType.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerParentOrderParameter.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerSide.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/BitflyerTimeInForce.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/results/BitflyerChildOrderAcceptance.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/results/BitflyerParentOrderAcceptance.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/results/BitflyerQueryChildOrderResult.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/dto/trade/results/BitflyerTradingCommission.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountService.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerAccountServiceRaw.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerTradeService.java, xchange-bitflyer/src/main/java/org/knowm/xchange/bitflyer/service/BitflyerTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-core/src/main/java/org/knowm/xchange/dto/Order.java, xchange-core/src/main/java/org/knowm/xchange/dto/trade/LimitOrder.java
* Implementation of market and limit orders
* Framework and model for complex orders
* Fetch open orders
* Fetch trade commissions
=> [Bitflyer] send simple orders

xchange-bankera/src/main/java/org/knowm/xchange/bankera/BankeraAdapters.java
Invalid value was provided for UserTrade object
=> [Bankera] Fix order history bug

pom.xml
this will fix the build for: https://github.com/knowm/XChange/pull/2913
=> maven fix for java 11

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/dto/HitbtcCandle.java
- Fixes wrong `toString` in `HitbtcCandle`
- Adds missing public constructor of `HitbtcCandle`
=> [hitbtc] improvements in 'HitbtcCandle.java': fix typo, add public constructor

xchange-examples/src/main/java/org/knowm/xchange/examples/hitbtc/marketdata/HitbtcCandlesDemo.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/Hitbtc.java, xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/service/HitbtcMarketDataServiceRaw.java
API : https://api.hitbtc.com/#candles
I have added 
1. from, till date filters 
2. be able to specify sort criteria
3. support for offsets for pagination
=> [hitbtc] OHLC Added till and from date filter, sort and offset filters

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java
Upgrade send / cancel orders calls to POST from GET. Both currently work.
#2926
=> [cryptofacilities] authenticated calls

xchange-exmo/src/main/java/org/knowm/xchange/exmo/service/ExmoAccountServiceRaw.java, xchange-exmo/src/main/java/org/knowm/xchange/exmo/service/ExmoMarketDataServiceRaw.java
=> [Exmo] Add missing blochain hash on funding history

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAdapters.java
Again a fix for satoshis to btc conversion
=> [Bitmex] Fix funding record fee

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java
some how the annotation got lost during the mergings, sorry
=> [cryptofacilities] fixed the cancelOrder method

xchange-bankera/src/test/java/org/knowm/xchange/bankera/service/MarketDataServiceIntegration.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
Added new currency pairs for Bankera Exchange
=> Add new Tether pairs

xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiAdapters.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiTradeServiceRaw.java, xchange-huobi/src/main/resources/huobi.json, xchange-huobi/src/test/java/org/knowm/xchange/huobi/HuobiPrivateApiIntegration.java, xchange-huobi/src/test/java/org/knowm/xchange/huobi/HuobiProperties.java, xchange-huobi/src/test/java/org/knowm/xchange/huobi/HuobiPublicApiIntegration.java
Add missing mandatory account parameter at market order placing;
Add new min amounts values into metadata configuration from https://huobiglobal.zendesk.com/hc/en-us/articles/360000400491-Trade-Limits;
Fix scale for BTC metadata;
Refactor unittests and integration tests.
=> [Huobi] Metadata update and refactoring

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/Util.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesCancel.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesCancelStatus.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFill.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesFills.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesInstrument.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesInstruments.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenOrder.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenOrders.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenPosition.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOpenPositions.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOrder.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOrderBook.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesOrderStatus.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesPublicFill.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesPublicFills.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesTicker.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesTickers.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/CryptoFacilitiesTradeServiceRaw.java, xchange-cryptofacilities/src/test/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesInstrumentsJSONTest.java, xchange-cryptofacilities/src/test/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesTickersJSONTest.java
consistent date parsing using new instance of SDF to be thread safe
=> [cryptofacilities] consistent date parsing using new instance of SDF

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
=> [Binance] Improve symbol conversion method

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexExchange.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexTradeService.java, xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v1/service/BitfinexProperties.java, xchange-bitfinex/src/test/java/org/knowm/xchange/bitfinex/v1/service/trade/BitfinexTradeServiceIntegration.java
Add changeOrder for Bitfinex;
Add integration tests;
Parse symbols and symbols details errors by error adapter.
=>  [Bitfinex] Add changeOrder for Bitfinex, aka cancel/replace

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java, xchange-bitmex/src/test/java/org/knowm/xchange/bitmex/service/marketdata/BitmexOrderBookFetchIntegration.java, xchange-bitmex/src/test/java/org/knowm/xchange/bitmex/service/marketdata/BitmexTickerFetchIntegration.java, xchange-bitmex/src/test/java/org/knowm/xchange/bitmex/service/marketdata/BitmexTradesFetchIntegration.java
=> [Bitmex] Fix tests that would fail in the future

xchange-core/src/main/java/org/knowm/xchange/dto/account/Wallet.java
The class is lacking a hashCode implementation.
=> [core] Overrode the 'hashCode' method.

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/trade/BatchStatus.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/trade/OrderPlacement.java
added missing order status: 'maxPositionViolation'
added toString method for order placement
=> [cryptofacilities] added missing order status

xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAdapters.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/CexIOAuthenticated.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/CexioPlaceOrderRequest.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOOrderTransactionsResponse.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOOrderWithTransactions.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/dto/trade/CexIOTransaction.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeService.java, xchange-cexio/src/main/java/org/knowm/xchange/cexio/service/CexIOTradeServiceRaw.java, xchange-cexio/src/test/java/org/knowm/xchange/cexio/CexioProperties.java, xchange-cexio/src/test/java/org/knowm/xchange/cexio/service/TradeServiceIntegration.java
Get transactions;
Add market order placing into private implementation.
Cancel multiple orders by currency pair;
Add integration tests.
=> [Cex.io] Add missing functions

xchange-simulated/src/main/java/org/knowm/xchange/simulated/MatchingEngine.java, xchange-simulated/src/main/java/org/knowm/xchange/simulated/SimulatedTradeService.java, xchange-simulated/src/test/java/org/knowm/xchange/simulated/SimulatedExchangeExample.java
an implementation for cancelOrder and getOrder
=> Simulated Exchange CancelOrder / GetOrder

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/BinanceAccountInformation.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-core/src/main/java/org/knowm/xchange/dto/account/AccountInfo.java
Required for determining if the content of a REST request is older or newer than that from a web socket.
=> [binance] Add timestamp to balances

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/trade/BatchStatus.java
see https://cryptofacilities.zendesk.com/hc/en-us/articles/360000546054-Send-Order
=> [cryptofacilities] additional status for order placement

xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrder.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/dto/marketdata/LivecoinOrdersDeserializer.java
order of elements in array changed
=> [LIVECOIN] order book parsing fix

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java
There are some currencies which last price are null, it was giving NullPointerException. I'm not adding the ones with null values.
=> [Bitfinex] Adapter - Looks like some prices are coming null and make the adapt to break

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticatedV2.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java
Comment has been added to bitstamp withdrawal bank api
=> Bitstamp  add comment to bank withdrawal

xchange-exmo/src/main/java/org/knowm/xchange/exmo/Exmo.java
fix issue:
https://github.com/knowm/XChange/issues/3083
=> [EXMO] POST requests in body by new api

xchange-therock/src/main/java/org/knowm/xchange/therock/service/TheRockAccountService.java, xchange-therock/src/main/java/org/knowm/xchange/therock/service/TheRockFundingHistoryParams.java
I've added filtering by time span and `FundingRecord.Type`
=> [TheRock] Better support for querying funding history

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/resources/binance.json
Fix NP for users using the public API without credentials.
=> Fix assetdetails NP for users using public API

xchange-okcoin/pom.xml, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexAdaptersV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexDigestV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexExchangeV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/account/OkexFundingAccountRecord.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/account/OkexSpotAccountRecord.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/marketdata/OkexTokenPairInformation.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/FundsTransferRequest.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/FundsTransferResponse.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexOpenOrder.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexOrderFlags.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexResponse.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexTradeHistoryParams.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexTransaction.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OrderBatchCancellationRequest.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OrderCancellationRequest.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OrderCancellationResponse.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OrderPlacementRequest.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OrderPlacementResponse.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/Side.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexAccountService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexAccountServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexBaseService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexException.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexMarketDataService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexMarketDataServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexTradeService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexTradeServiceRaw.java, xchange-okcoin/src/main/resources/okex.json
implemented the new Okex API v3
it exists now in parallel to the old one
basically u can use the old one with `org.knowm.xchange.okcoin.OkCoinExchange`
or the new one v3 `org.knowm.xchange.okcoin.OkexExchangeV3`
=> [okcoin] Implementation of Okex API v3

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexAdapters.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
unfortunatelly we need to go this way, since the pairs at bitfinex are not very consequent
see 'dusk:xxx' pairs at https://api.bitfinex.com/v1/symbols_details
=> [bitfinex] special handling for inconsequent pairs

xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java
=> add missing currency pairs for Bankera exchange

xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAuthenticated.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountServiceRaw.java
Added all the current currencies to deposit for Kraken, if the wallet doesn't exist it will create it, but only once.
=> Kraken deposit

xchange-bittrex/src/main/resources/bittrex.json
=> [Bittrex] Add some missing currencies

xchange-tradeogre/api-specification.txt, xchange-tradeogre/pom.xml, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgre.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreAdapters.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreAuthenticated.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreExchange.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/account/TradeOgreBalance.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/account/TradeOgreBalances.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/marketdata/TradeOgreTicker.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreAccountService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreAccountServiceRaw.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreBaseService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreMarketDataService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreMarketDataServiceRaw.java, xchange-tradeogre/src/test/java/org/knowm/xchange/tradeogre/TradeOgreAdaptersTest.java, xchange-tradeogre/src/test/java/org/knowm/xchange/tradeogre/service/TradeOgreMarketDataServiceRawTest.java
only tickers and balances support
=> TradeOgre added

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/resources/bitfinex.json
Update some currencies and fees to withdraw
=> [Bitfinex] wallet addresses and update withdrawn fees

xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-kraken/src/main/resources/kraken.json, xchange-kraken/src/test/java/org/knowm/xchange/kraken/KrakenExchangeTest.java
There were some missing withdraw fees and price scales for some currencies
=> [Kraken] add missing metadata regarding currencies and currency pairs

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/WithdrawList.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/account/CoinbaseProFee.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/marketdata/CoinbaseProProduct.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/currency/CurrencyPair.java, xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyPairMetaData.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/params/DefaultWithdrawFundsParams.java
- Added dynamic trading fees.
- Currencies + pairs status validation.
- Add boolean to check if pair supports market order type.
=> Coinbase + Binance dynamic trading fees and pair order types

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/account/BitmexWalletTransaction.java
Added walletBalance and marginBalance to BitmexWalletTransaction
=> Added attributes to BitmexWalletTransaction

xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitJWTDigest.java
timestamp -> uuid random string.
https://github.com/knowm/XChange/issues/3188
=> upbit nonce change

xchange-core/src/main/java/org/knowm/xchange/utils/Assert.java, xchange-core/src/main/java/org/knowm/xchange/utils/BigDecimalUtils.java, xchange-core/src/test/java/org/knowm/xchange/utils/BigDecimalUtilsTest.java
functionality suggested by @makarid  in https://github.com/knowm/XChange/pull/3201
=> [core] BigDecimalUtils with rounding to step size

xchange-core/pom.xml, xchange-core/src/main/java/org/knowm/xchange/currency/Currency.java, xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trade.java, xchange-core/src/main/java/org/knowm/xchange/dto/meta/RateLimit.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/TradeService.java, xchange-core/src/main/java/org/knowm/xchange/utils/BigDecimalUtils.java, xchange-core/src/main/java/org/knowm/xchange/utils/OrderValuesHelper.java, xchange-core/src/test/java/org/knowm/xchange/utils/BigDecimalUtilsTest.java, xchange-core/src/test/java/org/knowm/xchange/utils/OrderValuesHelperTest.java
new OrderValuesHelper to validate and / or adjust order values based on CurrencyPairMetaData
it also introduces a new style (behavioral) of writing tests in OrderValuesHelperTest - tell me if you like it
=> [core] new OrderValuesHelper to validate and / or adjust order values

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexAccountService.java
Finishing the margin wallet support using the new wallet implementation
=> [Bitmex] Finishing bitmex margin wallet support.

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
- Added cumulativeQuoteAmount which is the quote amount which is filled against the order.
Binance
- Set correct stopPrice on StopOrder.
CoinbasePro
- Refactored adaptOrder method.
@walec51
=> [Binance,CoinbasePro] Added cumulativeQuoteAmount field into Order

xchange-bitstamp/src/main/resources/bitstamp.json
Fixed bitstamp withdrawal fees as per https://www.bitstamp.net/fee-schedule/
=> [bitstamp] Fixed withdrawal fees

xchange-itbit/src/main/java/org/knowm/xchange/itbit/ItBitAdapters.java
- Fix NP when there is a rebate on user fill and hence no fee commission ccy.
- Include rebates in total fees.
=> [ItBit] Include fill fee rebates

xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java, xchange-core/src/main/java/org/knowm/xchange/dto/Order.java
Hello, can you please tell me if it is ok, the way i have implemented? Thanks
=> [Core] Replace ioutils.closequitely with try-with-resources

xchange-acx/src/main/java/org/knowm/xchange/acx/AcxApi.java, xchange-acx/src/main/java/org/knowm/xchange/acx/AcxExchange.java, xchange-acx/src/main/java/org/knowm/xchange/acx/AcxMapper.java, xchange-acx/src/main/java/org/knowm/xchange/acx/AcxSignatureCreator.java, xchange-acx/src/main/java/org/knowm/xchange/acx/dto/AcxTrade.java, xchange-acx/src/main/java/org/knowm/xchange/acx/service/account/AcxAccountService.java, xchange-acx/src/main/java/org/knowm/xchange/acx/service/trade/AcxTradeService.java, xchange-acx/src/main/resources/acx.json, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxAccountServiceTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxMapperTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxMarketDataServiceTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/AcxTradingServiceTest.java, xchange-acx/src/test/java/org/knowm/xchange/acx/ExchangeUtils.java, xchange-acx/src/test/java/org/knowm/xchange/acx/service/trade/AcxTradeServiceIntegration.java
- Updated metadata
- Implemented getTradeHistory
- Fixed bug that failed to convert btcusdt to the correct currencypair
=> [acx] Added support for trade history, updated metadata.

xchange-core/src/main/java/org/knowm/xchange/dto/account/FundingRecord.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java, xchange-poloniex/src/test/java/org/knowm/xchange/poloniex/PoloniexAdapterTest.java
#3218 
Implemented the the FundingRecord.Type "Airdrop" for Poloniex
=> Ponloniex: Added FundingRecord.Type "Airdrop"

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java
Fixing orderbook timestamp in order to be compatible with websocket timestamp also.
=> [Kraken] Orderbook timestamp

pom.xml
=> add tradeogre to build

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/DepositList.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/WithdrawList.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java, xchange-core/src/main/java/org/knowm/xchange/dto/account/AddressWithTag.java, xchange-core/src/main/java/org/knowm/xchange/dto/account/FundingRecord.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/params/DefaultWithdrawFundsParams.java
[Core]
- Renamed destinationTag to addressTag
[Binance]
- Added addressTag to withdraw and deposit history.
=> [Core,Binance] Renamed destinationTag to addressTag

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/marketdata/OkexFutureInstrument.java
added new fields for future instruments, which did not exist before
additionally use SnakeCaseStrategy for json naming
=> [okcoin] new fields for future instruments

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/trade/CoinbaseProTradeHistoryParams.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeServiceRaw.java, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/service/marketdata/HistoricalCandlesIntegration.java
Added support for request parameter "limit" in trade history request to better support paging.
Also "fixed" a test which makes a live call and the response seems to have changed.
=> [coinbasepro] Added support for "limit" parameter in trade history request

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/WithdrawList.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java
Added response field "transactionFee" to deliver withdraw FundingRecord's with proper fees.
=> [binance] Added support for "transactionFee" in withdraw history

xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/PoloniexAdapters.java
=> [Poloniex] remove PoloniexLevel import

xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/DeribitAuthenticated.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/dto/trade/Settlement.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/dto/trade/SettlementType.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/dto/trade/UserSettlements.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/service/DeribitTradeServiceRaw.java
see https://docs.deribit.com/v2/#private-get_settlement_history_by_instrument
=> [deribit] added the get_settlement_history_by_instrument method

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/LedgerEntry.java
see https://docs.bitfinex.com/reference#rest-auth-ledgers
=> [bitfinex] added getLedgerEntries method

xchange-bitmex/pom.xml, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexAuthenticated.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/trade/BitmexCancelAll.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexTradeServiceRaw.java, xchange-cryptofacilities/pom.xml, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/CryptoFacilitiesAuthenticated.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/CryptoFacilitiesResult.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/dto/marketdata/CryptoFacilitiesCancelAllOrdersAfter.java, xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/CryptoFacilitiesTradeServiceRaw.java
implemented for
- bitmex https://www.bitmex.com/app/wsAPI#Dead-Mans-Switch-Auto-Cancel
- crypto facilities https://www.cryptofacilities.com/resources/hc/en-us/articles/360005994214-Cancel-All-Orders-After
=> Dead man's switch (auto cancel)

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampExchange.java
=> [Bitstamp] Invalid nonce errors

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAdapters.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexTradeServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
=> bitfinex fixes

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java
Bitfinex has endpoint to get all ledgers
=> Bitfinex add end point to get all ledgers

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java
coinbasePrime is the institutional version of CoinbasePro
=> [CoinbasePro] add support for coinbasePrime part#1

xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/CoindealAdapters.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/CoindealAuthenticated.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealAccountService.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealAccountServiceRaw.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealMarketDataService.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealMarketDataServiceRaw.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealTradeService.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealTradeServiceRaw.java
Support for getTradeHistory, canceling order, getOpenOrders.
Clean up some exception handling.
=> [Coindeal]Adding support for more operations in Coindeal.

xchange-coindeal/src/main/resources/coindeal.json
- Fixed incorrect values in Coindeal metadata
- Added missing CurrencyPair / Currency (BTC/CHF, CHF)
=> [Coindeal] Fixed incorrect values in Coindeal metadata

xchange-bitbay/src/main/java/org/knowm/xchange/bitbay/dto/marketdata/BitbayOrderBook.java
- Fixed toString() method for BitbayOrderBook
- Removed code smells for class BitbayOrderBook
=> [BitBay] Fixed toString() method for BitbayOrderBook

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/BitfinexErrorAdapter.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataServiceRaw.java
Use correct case comparing exchange error text, as soon it converted to lower case.
=> [Bitfinex] Rate limit error cannot be caught

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java, xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceExchange.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-core/src/main/java/org/knowm/xchange/dto/meta/CurrencyMetaData.java, xchange-core/src/main/java/org/knowm/xchange/dto/meta/WalletHealth.java, xchange-core/src/test/java/org/knowm/xchange/dto/account/BalanceTest.java
[Binance]
- Remove hard coded currencies when loading dynamically.
- Add canDeposit + canWithdraw for coins.
[CoinbasePro]
- Add canDeposit + canWithdraw for coins.
=> [Binance, CoinbasePro] Add canDeposit + canWthdraw in CoinMetaData

xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/HuobiFundingRecord.java
fix https://github.com/knowm/XChange/issues/3324
=> 3324 issue

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexBaseService.java, xchange-bitmex/src/test/resources/org/knowm/xchange/bitmex/logback.xml
Make sure we have all headers from exchange before rate limit calculation;
Make symbols parsing not so strict, and allow to skip unrecognisable symbols instead of error;
Polish tests logback.xml.
=> [Bitmex] Add more input data validity checks

xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeService.java
since we can now set this field, when creating orders
=> [Kraken] add support CancelOrderByUserReference

.gitignore, xchange-enigma/src/main/java/org/knowm/xchange/enigma/EnigmaAuthenticated.java, xchange-enigma/src/main/java/org/knowm/xchange/enigma/EnigmaExchange.java, xchange-enigma/src/main/java/org/knowm/xchange/enigma/service/EnigmaMarketDataService.java, xchange-enigma/src/main/java/org/knowm/xchange/enigma/service/EnigmaMarketDataServiceRaw.java, xchange-enigma/src/main/java/org/knowm/xchange/enigma/service/EnigmaTradeServiceRaw.java, xchange-enigma/src/test/java/org/knowm/xchange/enigma/EnigmaOrderBookTest.java, xchange-enigma/src/test/java/org/knowm/xchange/enigma/EnigmaProductIntegration.java
Fixed orderbook issues
Fixed some request paths
Changed to production url
=> [Enigma] Fixed orderbook issues

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAuthenticatedV3.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexExchange.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexAccountVolume.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountServiceRaw.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexBaseService.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexContentDigest.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexDigestV3.java
initial support for v3 bittrex api
getting 30 day volume information (for calculating fees)
=> support for bittrex v3 api

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java, xchange-binance/src/test/java/org/knowm/xchange/binance/service/trade/TradeServiceIntegration.java
Fixed issue: org.knowm.xchange.exceptions.ExchangeException: Parameter 'timeInForce' sent when not required for BinanceTradeService.placeTestOrder
=> [Binance] Fixed issue: Parameter 'timeInForce' sent when not required for BinanceTradeService.placeTestOrder

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAdapters.java
to IndependentReserveAdapters.
=> [IndependentReserve] Adding price to userTrades on adaptHistory

xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/account/LedgerType.java, xchange-kraken/src/test/resources/org/knowm/xchange/kraken/dto/account/example-ledgerinfo-data.json
solution for issue
https://github.com/knowm/XChange/issues/3426
=> [Kraken] New ledger type "staking"  #3426

xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/BithumbAuthenticated.java, xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/service/BithumbAccountServiceRaw.java, xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/service/BithumbDigest.java, xchange-bithumb/src/test/java/org/knowm/xchange/bithumb/service/BithumbDigestTest.java
- Fixed not to be affected by the execution order of other ParamDigests.
- Fixed accounts issue 
- Bithumb account specification is modified.
=> [Bithumb] Fixed getAccounts issue + multiple ParamDigest issue

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/AssetDividendResponse.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/AssetDribbletLog.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/AssetDribbletLogResponse.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/account/SapiResponse.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountServiceRaw.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceBaseService.java, xchange-coinbase/src/main/java/org/knowm/xchange/coinbase/v2/service/CoinbaseAccountServiceRaw.java
Added
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#asset-dividend-record-user_data
and
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#dustlog-user_data
endpoints.
Also small improvement in getRecvWindow
Made CoinbaseAccountServiceRaw public
=> Binance 2 endpoints + small improvements

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java
=> [Coinbase] add userReference to CoinbaseProAdapters

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
Since we now the order is open
=> [Bitstamp] Set OrderStatus on openOrders

xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/BithumbAdapters.java, xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/service/BithumbTradeService.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/params/CancelOrderByPairAndIdParams.java
=> [bithumb] bug fixes - averagePrice

xchange-gemini/pom.xml, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiBaseService.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiMarketDataServiceRaw.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v2/Gemini2.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v2/dto/marketdata/GeminiCandle.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v2/dto/marketdata/GeminiTicker2.java, xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/service/marketdata/TickerFetchIntegration.java
=> [Gemini] Candles in raw service

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAccountServiceRaw.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinMarketDataServiceRaw.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/request/CreateAccountRequest.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/AccountAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/SymbolAPI.java, xchange-kucoin/src/test/java/org/knowm/xchange/kucoin/KucoinMarketDataServiceIntegration.java
Fix orderbook time
CreateAccount API implemented
getPrices API implemented + test case
=> [Kucoin] fix orderbook time, createAccount API and getPrices API

xchange-cryptowatch/pom.xml, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/Cryptowatch.java, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/CryptowatchAdapters.java, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/dto/marketdata/CryptowatchOHLCs.java, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/service/CryptowatchBaseService.java, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/service/CryptowatchMarketDataService.java, xchange-cryptowatch/src/main/java/org/knowm/xchange/cryptowatch/service/CryptowatchMarketDataServiceRaw.java, xchange-cryptowatch/src/main/resources/cryptowatch.json, xchange-cryptowatch/src/test/java/org/knowm/xchange/cryptowatch/dto/marketdata/CryptowatchOHLCJSONTest.java, xchange-cryptowatch/src/test/java/org/knowm/xchange/cryptowatch/service/CryptowatchMarketDataServiceIntegration.java, xchange-cryptowatch/src/test/java/org/knowm/xchange/cryptowatch/service/CryptowatchMarketDataServiceRawIntegration.java
- fixed Cryptowatch url
- fixed missing start metadata
- added adapter for CurrencyPair to String
- added configuration to log error in results
- added integration tests
- fixed OHLC format
=> Fixed Cryptowatch module

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java
not documented but tested to be working
=> [bitfinex] fix bitcoin cash deposit address

README.md, xchange-stream-bankera/pom.xml, xchange-stream-binance/pom.xml, xchange-stream-bitfinex/pom.xml, xchange-stream-bitflyer/pom.xml, xchange-stream-bitmex/pom.xml, xchange-stream-bitstamp/pom.xml, xchange-stream-cexio/pom.xml, xchange-stream-coinbasepro/pom.xml, xchange-stream-coinmate/pom.xml, xchange-stream-core/pom.xml, xchange-stream-gemini/pom.xml, xchange-stream-hitbtc/pom.xml, xchange-stream-kraken/pom.xml, xchange-stream-lgo/pom.xml, xchange-stream-okcoin/pom.xml, xchange-stream-poloniex/pom.xml, xchange-stream-poloniex2/pom.xml, xchange-stream-service-core/pom.xml, xchange-stream-service-netty/pom.xml, xchange-stream-service-pubnub/pom.xml, xchange-stream-service-pusher/pom.xml, xchange-stream-service-wamp/pom.xml
I've also updated some Wiki pages with basic info.
=> README changes, some tidying of xchange-stream import

xchange-bittrex/pom.xml, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAuthenticatedV3.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexUtils.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/BatchOrderResponse.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/Payload.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/BatchOrder.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/Operation.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/OrderPayload.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/cancelorder/CancelOrderPayload.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/neworder/Direction.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/neworder/NewOrderPayload.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/neworder/TimeInForce.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/batch/order/neworder/Type.java
place order, cancel order, execute orders batch
=> [Bittrex] Some V3 Api endpoints calls added

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/trade/OkexResponse.java
OkCoin return errorCode "0" for some successful calls.
=> [OkCoin] Fix OkexResponse validation

xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java
bu - Balances updates are common, do not log them.
=> [BitFinex] Socket Debug logging Fix

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java, xchange-stream-btcmarkets/src/main/java/info/bitrich/xchangestream/btcmarkets/BTCMarketsStreamingMarketDataService.java, xchange-stream-btcmarkets/src/main/java/info/bitrich/xchangestream/btcmarkets/dto/BTCMarketsWebSocketOrderbookMessage.java, xchange-stream-btcmarkets/src/test/java/info/bitrich/xchangestream/btcmarkets/BTCMarketsManualExample.java, xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
https://github.com/bitrich-info/xchange-stream/pull/522
https://github.com/bitrich-info/xchange-stream/pull/566
=> [Core-Stream] Roll up of two excluded open PR during merge

xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexAdaptersV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/OkexV3.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/marketdata/OkexOrderBook.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/dto/marketdata/OkexOrderBookEntry.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexMarketDataService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexMarketDataServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexTradeService.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexTradeServiceRaw.java
Order Book is implemented to get market data. Order details implementation will used to know the status of order based on order Id.
=> [okex] Order Book and Order details implementation

xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenEvent.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenSubscriptionConfig.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenSubscriptionMessage.java
removing null fields from json serialized subscription message
=> [Streaming] issue #3542: Remove unused error field and ignore null fields when serializing

xchange-idex/src/main/java/org/knowm/xchange/idex/IdexMarketDataService.java, xchange-idex/src/test/java/org/knowm/xchange/idex/IdexExchangeIntegration.java, xchange-idex/src/test/java/org/knowm/xchange/idex/IdexExchangeTest.java
Idex Unreconginzed field "slug"
=> fix for issue:  #3530

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAuthenticated.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReservePlaceMarketOrderRequest.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/trade/IndependentReservePlaceMarketOrderResponse.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveTradeService.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveTradeServiceRaw.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/util/ExchangeEndpoint.java
Signed-off-by: Martin Zdarsky-Jones <zdary@zdary.cz>
=> [#3586] Independent Reserve - added placeMarketOrder function

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveAuthenticated.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/account/IndependentReserveDepositAddressRequest.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/dto/account/IndependentReserveDepositAddressResponse.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveAccountService.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/service/IndependentReserveAccountServiceRaw.java, xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/util/ExchangeEndpoint.java
Signed-off-by: Martin Zdarsky <zdary@zdary.cz>
=> [#3592] Independent Reserve - added requestDepositAddress function

xchange-huobi/src/main/java/org/knowm/xchange/huobi/Huobi.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiAdapters.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/HuobiUtils.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/HuobiResultV2.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/HuobiDepositAddress.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/HuobiFeeRate.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/HuobiTransactFeeRate.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/results/HuobiDepositAddressV2Result.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/results/HuobiFeeRateResult.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/account/results/HuobiTransactFeeRateResult.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/marketdata/HuobiAssetPair.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/HuobiMatchResult.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/HuobiOrder.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/trade/results/HuobiMatchesResult.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiAccountService.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiAccountServiceRaw.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiBaseService.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiTradeServiceRaw.java
huobi fixes & support for v2 api
=> huobi fixes & support for v2 api

xchange-independentreserve/src/main/java/org/knowm/xchange/independentreserve/IndependentReserveExchange.java
Signed-off-by: Martin Zdarsky <zdary@zdary.cz>
=> [#3619] Independent Reserve - corrected nonce for frequent calls

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAccountService.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAccountServiceRaw.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinExchange.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/AccountAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/DepositAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/FillAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/HistOrdersAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/OrderAPI.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/WithdrawalAPI.java
added optional parameters for pagination where possible: pageSize and currentPage
see doc at https://docs.kucoin.com/#pagination
=> [kucoin] added optional parameters for pagination where possible

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenAuthenticated.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountServiceRaw.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java
Kraken API: support for minimum order volume
1.
https://www.kraken.com/features/api#get-tradable-pairs
- ordermin = minimum order volume for pair
2.
- support for new deposit address
=> Kraken API: support for minimum order volume & support for new deposit address

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/Wallet.java
see api doc https://docs.bitfinex.com/reference#rest-auth-wallets
=> [bitfinex] added the wallets v2 method

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/BitmexExchange.java, xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/BitmexStreamingService.java
Addresses https://github.com/knowm/XChange/issues/3556
=> Fixing Bitmex bug, general NPE protections

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenBaseService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingService.java, xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java, xchange-stream-bitstamp/src/main/java/info/bitrich/xchangestream/bitstamp/v2/BitstampStreamingService.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingExchange.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingMarketDataService.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java
Allowed for increased configuration in constructor of some streaming exchanges, made minor code improvements.
=> [Streaming] Increasing configuration of various streaming exchanges, small improvements

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/CoinbaseProTransfer.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountServiceRaw.java
support for newer endpoint returning all transfers for deposit or withdraw at once
=> [CoinBasePro] support for /transfers (returning all transfers at once)

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/BinanceException.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java, xchange-bitfinex/src/main/resources/bitfinex.json
- Adding LINK/USD to Bitfinex
- Adding more information to `BinanceException`
- Minor spelling fixes
=> [Binance + Bitfinex] adding small exchange updates

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java
correctly handle 4/3 or LINK/USD for instance
=> [gemini] Update GeminiAdapters.java

xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/BittrexAuthenticated.java, xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexAddress.java, xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexDepositHistory.java, xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/dto/account/BittrexNewAddress.java, xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountService.java, xchange-bittrexV3/src/main/java/org/knowm/xchange/bittrex/service/BittrexAccountServiceRaw.java
Changes:
- support for get & generate deposit address 
- fix deposit history
=> [BittrexV3] support for get & generate deposit address

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAuthenticated.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateOrder.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateOrders.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateOrdersData.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateTradeService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateTradeServiceRaw.java
Add support for getting order by id on Coinmate.io exchange
=> [Coinmate] add support for orderById

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/CoinbaseProExchangeTest.java
- Fixed problem that CoinbaseProExchange.concludeHostParams  overrides provided exchangeSpecification.sslUri
- Added possibility to define custom sslUris and hosts for: CoinbasePro Sandbox / Prime / SandboxPrime
=> [CoinbasePro] Fixed problem that CoinbaseProExchange.concludeHostParams  overrides provided sslUri

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java
[Bitstamp] Fix: getUserTransactions - use correct method for currency pair null
=> [Bitstamp] Fix: getUserTransactions use correct method for currency pair null

xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/service/DeribitTradeServiceRaw.java
Note: First time proposal.
The /private/edit works fine if you don't add the MMP Flag to the Parameters.
I added the other Params only as comments, because I don't need them for my work.
Tested it, works. Much easier than deleting the existing order and placing a new one.
Best regards
=> [Deribit] Update DeribitTradeServiceRaw.java; added edit() for path: /private/edit

xchange-core/pom.xml
Removed duplicated dependencies.
Fixed problem "Some problems were encountered while building the effective model for org.knowm.xchange:xchange-core:jar:5.0.3-SNAPSHOT"
=> xchange-core pom cleanup

xchange-bitbay/src/main/resources/bitbay.json
Added USDT and LINK markets to static metadata
=> [Bitbay] Added USDT and LINK markets to static metadata

xchange-examples/pom.xml, xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/account/BittrexAccountDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/marketdata/BittrexMarketDataDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/trade/BittrexTradeDemo.java
migrate examples to bittrex v3 (closing #3672)
=> [Bittrex v3] migrate examples to bittrex v3

xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenOrderBook.java
=> [Kraken] KrakenOrderBook NPE Fix

pom.xml
=> Updated ciManagement url

xchange-stream-coinmate/pom.xml
Fixed problem with building the effective model for pom xchange-stream-coinmate
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.knowm.xchange:xchange-stream-coinmate:jar:5.0.4-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.mockito:mockito-core:jar -> duplicate declaration of version (?) @ org.knowm.xchange:xchange-stream-coinmate:[unknown-version], /home/travis/build/knowm/XChange/xchange-stream-coinmate/pom.xml, line 35, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
```
=> Fixed problem with building the effective model for pom xchange-stream-coinmate

README.md
Added badge to README.md - develop build status
=> Added badge to README.md - develop build status

pom.xml, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/CoinbaseProAdaptersTest.java, xchange-core/pom.xml, xchange-cryptopia/pom.xml, xchange-lgo/src/test/java/org/knowm/xchange/lgo/LgoAdaptersTest.java, xchange-lgo/src/test/java/org/knowm/xchange/lgo/LgoExchangeMarketDataIntegration.java, xchange-lgo/src/test/java/org/knowm/xchange/lgo/LgoExchangeMetadataIntegration.java, xchange-lgo/src/test/java/org/knowm/xchange/lgo/LgoExchangeTradeIntegration.java, xchange-lgo/src/test/java/org/knowm/xchange/lgo/service/LgoSignatureServiceLocalRsaTest.java, xchange-okcoin/src/test/java/org/knowm/xchange/okcoin/service/MetaDataFileTest.java, xchange-stream-bitmex/pom.xml, xchange-stream-hitbtc/src/test/java/info/bitrich/xchangestream/hitbtc/HitbtcStreamingMarketDataServiceTest.java, xchange-stream-hitbtc/src/test/java/info/bitrich/xchangestream/hitbtc/dto/HitbtcMessageTest.java, xchange-stream-huobi/pom.xml, xchange-stream-huobi/src/main/java/info/bitrich/xchangestream/huobi/HuobiStreamingService.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoStreamingExchange.java, xchange-stream-lgo/src/test/java/info/bitrich/xchangestream/lgo/LgoStreamingExchangeExample.java, xchange-stream-lgo/src/test/java/info/bitrich/xchangestream/lgo/LgoStreamingTradeServiceTest.java
Cleaning up
- commons-io
- fluent-hc
- fastjson
@timmolter
=> [Streaming] more dependency cleanup

xchange-bithumb/src/main/java/org/knowm/xchange/bithumb/BithumbAdapters.java, xchange-bithumb/src/test/java/org/knowm/xchange/bithumb/dto/marketdata/BithumbMarketDataTest.java
Fixed trade adaptor error 
#3632
=> [Bithumb] Fixed trade adaptor error

xchange-examples/pom.xml, xchange-examples/src/main/java/org/knowm/xchange/examples/deribit/DeribitDemoUtils.java, xchange-examples/src/main/java/org/knowm/xchange/examples/deribit/dto/marketdata/DeribitMarketdataDemo.java
Added examples for Deribit exchange
=> [Examples] Deribit examples

xchange-examples/src/main/java/org/knowm/xchange/examples/upbit/marketdata/UpbitOrderBookDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/upbit/marketdata/UpbitTickerDemo.java, xchange-examples/src/main/java/org/knowm/xchange/examples/upbit/trade/UpbitLimitOrderDemo.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/Upbit.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitAdapters.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitExchange.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/UpbitUtils.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/dto/marketdata/UpbitMarket.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitAccountService.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitAccountServiceRaw.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitMarketDataService.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitMarketDataServiceRaw.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitTradeService.java, xchange-upbit/src/main/java/org/knowm/xchange/upbit/service/UpbitTradeServiceRaw.java
- Implements getTickers() 
- Added Upbit util class
=> [Upbit] Implements getTickers()

xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticated.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampAuthenticatedV2.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampOrderCancelResponse.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/trade/BitstampOrderStatusResponse.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountServiceRaw.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java
bitstamp migrate to v2 (cancel order, order status)
=> [bitstamp] migrate to v2 (cancel order, order status)

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAdapters.java
OrderBook entries do not have userReference, so pass null to LimitOrder constructor
=> [HitBtc]OrderBook userReference

xchange-kraken/src/main/java/org/knowm/xchange/kraken/KrakenUtils.java
Completing according https://support.kraken.com/hc/en-us/articles/360001185506-How-to-interpret-asset-codes
=> Complete discontinued currencies on Kraken

xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/v2/HitbtcAdapters.java
We can recycle this builder to reduce GC
=> [HitBtc] OrderBook performance

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/LedgerRequest.java
see the api description for the new parameter 'category'
https://docs.bitfinex.com/reference#rest-auth-ledgers
=> [bitfinex] added the category parameter to ledger method

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbasePro.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountServiceRaw.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/interceptor/InterceptorProvider.java, xchange-core/src/main/java/org/knowm/xchange/utils/timestamp/TimestampFactory.java, xchange-core/src/main/java/org/knowm/xchange/utils/timestamp/UnixTimestampFactory.java, xchange-core/src/test/java/org/knowm/xchange/utils/timestamp/UnixTimestampFactoryTest.java
Fixes https://github.com/knowm/XChange/issues/3871
=> [CoinbasePro] Fix 'request timestamp expired'

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/TransferBetweenWalletsRequest.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/TransferBetweenWalletsResponse.java
Transfer funds between internal wallets. 
see https://docs.bitfinex.com/reference#rest-auth-transfer
=> [bitfinex] added the method to transfer funds between wallets

LICENSE
LICENSE file updated to the current year.
=> LICENSE file updated

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/BittrexAdapters.java, xchange-bittrex/src/test/java/org/knowm/xchange/bittrex/BittrexAdaptersTest.java
=> [bittrex] Fix UserTrade type classification

xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceUserDataStreamingService.java
Fix also on User Data streaming
=> #3907 Extended fix for binance stream due to invalid websocket exception

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/Bitfinex.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/Bitfinex.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexCandle.java, xchange-examples/src/main/java/org/knowm/xchange/examples/bitfinex/marketdata/CandlesDemo.java
Ability to fetch funding candles from Bitfinex
=> [Bitfinex] Add funding candles get

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java, xchange-stream-hitbtc/pom.xml
See https://bittrex.github.io/api/v3#topic-Placing-Orders
=> [Bittrex] Added order type specification possibility

xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/DeribitAuthenticated.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/dto/trade/UserSettlements.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/service/DeribitTradeServiceRaw.java
=> [Deribit] getSettlementHistoryByInstrument: continuation support

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/Wallet.java
Added additional fields provided by the API like ie "balance available"
see doc https://docs.bitfinex.com/reference#rest-auth-wallets
=> [bitfinex] added aditional fields for v2 Wallet

xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/dto/trade/Order.java
Fixes issue #3932
* deribit fix: handle non-numeric marker values in order.price
=> Fix: [Deribit] NumberFormatException while parsing stop market orders from json #3932

xchange-stream-binance/README.md, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingExchange.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingMarketDataService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceSubscriptionType.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/dto/BinanceWebSocketSubscriptionMessage.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/exceptions/UpFrontSubscriptionRequiredException.java, xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceLiveSubscriptionExample.java, xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
Add the Binance Live Subscribing/Unsubscribing to streams feature.
https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#live-subscribingunsubscribing-to-streams
=> Issue 3914/binance live subscription unsubscription

xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/BitmexStreamingMarketDataService.java, xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/BitmexTicker.java, xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/BitmexWebSocketTransaction.java, xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/RawOrderBook.java
implement Bitmex orderbook10 websocket channel connection
add BitmexStreamingMarketDataService.getRawOrderBook method
=> implement Bitmex orderbook10 ws connection, implement dataservice.getRawOrderBook

xchange-btcmarkets/src/test/java/org/knowm/xchange/btcmarkets/service/BTCMarketsAccountServiceTest.java
=> fixing broken btcmarkets test

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountServiceRaw.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/client/ResilienceRegistries.java, xchange-core/src/main/java/org/knowm/xchange/client/ResilienceUtils.java, xchange-core/src/main/java/org/knowm/xchange/service/BaseResilientExchangeService.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinAccountServiceRaw.java, xchange-livecoin/src/main/java/org/knowm/xchange/livecoin/service/LivecoinTradeServiceRaw.java
Minor library fixes/improvements
=> [Core] Fixing spelling and small library improvements

xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/marketdata/HuobiAssetPair.java
add more attributes for asset pair (like online offline state)
=> [Huobi] add more attributes for asset pair (like online offline state)

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/Bitfinex.java
Hi all,
I've added support for following REST endpoint as it was missing:
https://docs.bitfinex.com/reference#rest-public-candles
Have a great day :)
-mb
=> bitfinex: support for fetching candles history

xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAuthenticated.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/dto/account/FtxChangeSubAccountNamePOJO.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxAccountServiceRaw.java
=> Adding requests for subAccount FTX

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexMarketDataServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/Bitfinex.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/marketdata/BitfinexStats.java
see https://docs.bitfinex.com/reference#rest-public-stats1
=> [bitfinex] added the stats v2 method

pom.xml, xchange-bleutrade/src/test/java/org/knowm/xchange/bleutrade/service/BleutradeDigestTest.java, xchange-coinegg/src/test/java/org/knowm/xchange/coinegg/service/CoinEggDigestTest.java, xchange-fcoin/src/test/java/org/knowm/xchange/fcoin/ApiSignatureTest.java
See https://github.com/mmazi/rescu/pull/135.
=> Upgrade rescu to 2.1

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/Bitmex.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexFunding.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexFundingList.java, xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/service/BitmexMarketDataServiceRaw.java
Implement Bitmex "funding history" endpoint:
https://www.bitmex.com/api/explorer/#!/Funding/Funding_get
=> [bitmex] implement getFundingHistory

xchange-bitmex/src/main/java/org/knowm/xchange/bitmex/dto/marketdata/BitmexFunding.java
Add missing getter functions to BitmexFunding class.
Sorry, i was a bit too hasty creating #3988, and forgot to add the DTO getter funcions to the original PR yesterday.
=> [bitmex] BitmexFunding getter functions

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceHmacDigest.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiDigest.java
rescu upgrade support Query Param digest now, so the original code which use reflection becomes a bug mentioned here
https://github.com/knowm/XChange/pull/3986#issuecomment-805707311
=> Remove hacky reflection based digest in binance and huobi

xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/CryptoFacilitiesDigest.java
the code did not work with the new rescu version 2.1
see https://github.com/knowm/XChange/pull/3986
=> [cryptofacilities] fix for new rescu version

xchange-huobi/src/main/java/org/knowm/xchange/huobi/Huobi.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/marketdata/HuobiKline.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/marketdata/KlineInterval.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/dto/marketdata/results/HuobiKlinesResult.java, xchange-huobi/src/main/java/org/knowm/xchange/huobi/service/HuobiMarketDataServiceRaw.java, xchange-huobi/src/test/java/org/knowm/xchange/huobi/Examples.java
This small PR adds function "get_klines" for Huobi exchange.
=> add Huobi function "get_klines"

xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgre.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreAdapters.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreAuthenticated.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/TradeOgreExchange.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/marketdata/TradeOgreOrderBook.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/trade/TradeOgreOrder.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/dto/trade/TradeOgreTradeResponse.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreAccountService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreAccountServiceRaw.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreBaseService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreMarketDataService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreMarketDataServiceRaw.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreTradeService.java, xchange-tradeogre/src/main/java/org/knowm/xchange/tradeogre/service/TradeOgreTradeServiceRaw.java, xchange-tradeogre/src/test/java/org/knowm/xchange/tradeogre/TestTradeOgreAdapters.java, xchange-tradeogre/src/test/java/org/knowm/xchange/tradeogre/service/TestTradeOgreMarketDataServiceRawIntegration.java
private: buy, sell, cancel, getOrders
public: getOrderBook
=> [TradeOgre] more endpoints implemented

xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdapters.java, xchange-stream-kraken/src/test/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdaptersTest.java
Fixes https://github.com/knowm/XChange/issues/4022
=> Add missing timestamps to Kraken OrderBook WS messages

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProAdapters.java
Details of the issue here [4028](https://github.com/knowm/XChange/issues/4028)
=> Fix for issue https://github.com/knowm/XChange/issues/4028

xchange-gateio/src/main/java/org/knowm/xchange/gateio/Gateio.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/marketdata/GateioCandlestickHistory.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/marketdata/GateioKline.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/dto/marketdata/GateioKlineInterval.java, xchange-gateio/src/main/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceRaw.java, xchange-gateio/src/test/java/org/knowm/xchange/gateio/Examples.java
This small PR adds "getKline" function for GateIo exchange.
=> add GateIo function "get_klines"

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeService.java, xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java
support for bittrex market order
=> [bittrex] place market order

xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/Deribit.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/service/DeribitMarketDataServiceRaw.java, xchange-deribit/src/test/java/org/knowm/xchange/deribit/v2/service/marketdata/DeribitHistoricalVolatileIntegration.java
the relevant api docs :https://docs.deribit.com/#public-get_historical_volatility
=> [Deribit]feature:add support for historical volatility in Deribit

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java, xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/dto/FtxTickerResponse.java, xchange-stream-ftx/src/test/java/info/bitrich/xchangestream/ftx/FtxStreamingMarketDataServiceTest.java
Forgot to set values that was available, so last solution only gave bid and ask to the timestamp. Moved into the response object to make sure I don't forget it.
=> [FTX]  Bug: Fixed missing values that I forgot was added later on.

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/CurrenciesResponse.java
There has been an json deserialization error during wallet data fetch operation in kucoin. This PR fixes this issue.
=> Fix for proper currency wallet health assignment

xchange-bittrex/src/main/java/org/knowm/xchange/bittrex/service/BittrexTradeServiceRaw.java
=> [Bittrex] fix market order

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java, xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingMarketDataService.java, xchange-stream-ftx/src/test/java/info/bitrich/xchangestream/ftx/FtxStreamingMarketDataServiceTest.java
The code is based on existing `getTicker` and `getOrderBook` methods
=> [FTX] Implement trades streaming

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/account/CoinbaseProFee.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/marketdata/CoinbaseProProduct.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingExchange.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java
Add some missing fields to rest api and connection idle observable.
=> Coinbase improvements

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/service/BitfinexAccountServiceRaw.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/BitfinexAuthenticated.java, xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v2/dto/account/UpdateCollateralDerivativePositionRequest.java
see https://docs.bitfinex.com/reference#rest-auth-deriv-pos-collateral-set
=> [bitfinex] added UpdateCollateralDerivativePosition method

pom.xml, xchange-stream-bankera/src/main/java/info/bitrich/xchangestream/bankera/BankeraStreamingService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceUserDataStreamingService.java, xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java, xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/BitmexStreamingService.java, xchange-stream-bitstamp/src/main/java/info/bitrich/xchangestream/bitstamp/v2/BitstampStreamingService.java, xchange-stream-btcmarkets/src/main/java/info/bitrich/xchangestream/btcmarkets/BTCMarketsStreamingService.java, xchange-stream-cexio/src/main/java/info/bitrich/xchangestream/cexio/CexioStreamingRawService.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java, xchange-stream-coinjar/src/main/java/info/bitrich/xchangestream/coinjar/CoinjarStreamingService.java, xchange-stream-coinmate/src/main/java/info/bitrich/xchangestream/coinmate/v2/CoinmateStreamingService.java, xchange-stream-dydx/src/main/java/info/bitrich/xchangestream/dydx/dydxStreamingService.java, xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingService.java, xchange-stream-gateio/src/main/java/GateioStreamingService.java, xchange-stream-gemini-v2/src/main/java/info/bitrich/xchangestream/gemini/GeminiStreamingService.java, xchange-stream-gemini/src/main/java/info/bitrich/xchangestream/gemini/GeminiProductStreamingService.java, xchange-stream-hitbtc/src/main/java/info/bitrich/xchangestream/hitbtc/HitbtcStreamingService.java, xchange-stream-huobi/src/main/java/info/bitrich/xchangestream/huobi/HuobiStreamingService.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoStreamingService.java, xchange-stream-okcoin/src/main/java/info/bitrich/xchangestream/okcoin/OkCoinStreamingService.java, xchange-stream-poloniex2/src/main/java/info/bitrich/xchangestream/poloniex2/PoloniexStreamingService.java, xchange-stream-serum/src/main/java/info/bitrich/xchangestream/serum/SerumStreamingService.java, xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java
Required before merging in https://github.com/knowm/XChange/pull/4063
=> Added vararsg to streaming getUnsubscribeMessage

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
=> [FTX] Index Out of bound in getOrderbookChecksum (+BONUS+)

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
=> [FTX] getOrderbookChecksum FIX bad merge

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/WebsocketResponse.java
- Make `InstanceServer` public so it can actually be used
- Fix spelling of `pingInterval`
=> Fix KuCoin WebsocketResponse

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
a) DecimalFormat is not always thread safe
b) adaptTickerMessage returned an empty ticker, we need to filter that out before streaming it.
=> [FTX] 2 fixes

xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin/trade/KucoinTradeRawDemo.java
fixed adding extra param for kucoin api
=> [kucoin] fix kucoin build (demo)

xchange-ftx/src/main/java/org/knowm/xchange/ftx/Ftx.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAdapters.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/dto/marketdata/FtxCandleDto.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxMarketDataService.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxMarketDataServiceRaw.java
Basically I implemented :
- Getting a single market info in getMarket (instead of getMarkets)
- Getting historical candle data (getCandles)
- Using both of the above I implemented the getTicker method.
=> Implementation of getTicker, fix for 4195

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/marketdata/CoinmateTickerData.java
API reference:
https://coinmate.docs.apiary.io/#reference/ticker/get-ticker/get
Not sure, if percentageChange is supposed to be in 0-1.0 or 0-100 style.
=> Coinmate extra ticker properties

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java
checksum must be calculated using scientific format for price
=> [FTX] Orderbook XRP/BTC

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateTradeService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateTradeServiceRaw.java
Seems like it was already kinda prepared in the REST code, just History wasn't implementing the interface and passing arguments to raw service.
=> Implementing TradeHistoryParamsTimeSpan interface.

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAccountServiceRaw.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/service/AccountAPI.java
Updated the account ledgers api call and deprecated the old one.
=> Kucoin - Added in the updated account ledgers api call

xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAdapters.java, xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/GeminiAdaptersTest.java, xchange-gemini/src/test/resources/org/knowm/xchange/gemini/v1/trade/example-get-order-data.json
1970 date objects were being set on the Order object returned by this code.
=> Fix Gemini Order timestamps.

xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingService.java
Fix handling of channel and market fields
=> [FTX] subscribe ticker & Trades

xchange-bitfinex/src/main/java/org/knowm/xchange/bitfinex/v1/BitfinexUtils.java
Discussion in the [issue](https://github.com/knowm/XChange/issues/4257)
=> Fix for issue #4257

xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/AscendexAdapters.java
=> [ascendex] MinAmount

xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/dto/trade/AscendexOrderResponse.java
=> [ascendex] PlaceOrderInfo extra fields

xchange-ftx/src/main/java/org/knowm/xchange/ftx/Ftx.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxMarketDataService.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxMarketDataServiceRaw.java
=> Dev: Fix issue 4295

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProResilience.java, xchange-coinbasepro/src/main/resources/coinbasepro.json
https://docs.pro.coinbase.com/#rate-limits
=> Use up-to-date rate limit values.

xchange-coinbase/src/main/java/org/knowm/xchange/coinbase/v2/CoinbaseAuthenticated.java, xchange-coinbase/src/main/java/org/knowm/xchange/coinbase/v2/service/CoinbaseAccountServiceRaw.java
Cursor for paginated /accounts results
=> [Coinbase][Accounts] Fix issues 4268

xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/IAscendex.java, xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/dto/marketdata/AscendexBarDto.java, xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/dto/marketdata/AscendexBarHistDto.java, xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/service/AscendexMarketDataServiceRaw.java, xchange-ascendex/src/test/java/org/knowm/xchange/ascendex/AscendexMarketDataIntegrationTest.java
=> [ascendex] history-bar

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java
=> Updated rate limit of binance ticker24 call

xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java
Adds `binanceTime()` in `BinanceMarketDataServiceRaw`.
Solves https://github.com/knowm/XChange/issues/4139
=> [BINANCE] Add binanceTime()

xchange-stream-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingMarketDataService.java
needs "t" prefix in latest version,  also USDT -> UST
=> [BitFinex] Stream symbology

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceNewOrder.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceTradeServiceRaw.java
- Added the request param `NewOrderResponseType` to newOrder
- Added `fills` to `BinanceNewOrder`
Solves https://github.com/knowm/XChange/issues/4184.
=> [BINANCE] Add "NewOrderResponseType" to "BinanceNewOrder"

xchange-okex/src/main/java/org/knowm/xchange/okex/v5/Okex.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/dto/marketdata/OkexCandleStick.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/service/OkexMarketDataServiceRaw.java, xchange-okex/src/test/java/org/knowm/xchange/okex/v5/OkexMarketDataIntegrationTest.java
=> [OKEX] Add CandleStick API

xchange-okex/src/main/java/org/knowm/xchange/okex/v5/OkexAdapters.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/OkexAuthenticated.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/dto/account/PiggyBalance.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/dto/subaccount/OkexSubAccountDetails.java, xchange-okex/src/main/java/org/knowm/xchange/okex/v5/service/OkexAccountServiceRaw.java
and Piggy Account
just to Raw for now
=> [okex] add support for subaccounts

xchange-okex/src/main/java/org/knowm/xchange/okex/v5/OkexAdapters.java
This PR fixes orders state for Okex
=> [okex] adapt orders state fix

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountService.java
adding support for timestampFrom and timestampTo for querying coinmate funding history
=> coinmate getFundingHistory add support for querying by dates

xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceFutureStreamingExchange.java, xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceLiveFutureSubscriptionExample.java
Added simple access for the stream api overriding with the specific future endpoint.
=> [Binance][Stream] Added support for the future stream

xchange-itbit/src/main/java/org/knowm/xchange/itbit/service/ItBitAccountService.java
The solution to the reported issue: https://github.com/knowm/XChange/issues/4044
Protection against possible NPE in ItBit when the user has a wallet without any transactions.
=> [ItBit] Prevent NPE

xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/account/CoinbaseProTransfersWithHeader.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/trade/CoinbaseProTradeHistoryParams.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java
Hello,
please accept my changes where is prepared getting transfers with pagination.
Thank you!
=> CoinbasePro-deposit/withdrawals incl. pagination

xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java
Small commit. 
I was seeing errors from coinbase handshake similar to what we saw with binance before.
=> Updated the coinbase websocket extension handler 

xchange-ascendex/src/main/java/org/knowm/xchange/ascendex/service/AscendexTradeService.java, xchange-bankera/src/main/java/org/knowm/xchange/bankera/service/BankeraTradeService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/BinanceTrade.java, xchange-bitcointoyou/src/main/java/org/knowm/xchange/bitcointoyou/service/polling/BitcointoyouTradeService.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeService.java, xchange-bl3p/src/main/java/org/knowm/xchange/bl3p/service/Bl3pTradeService.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/dto/account/CoinbaseProTransfersWithHeader.java, xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/service/CoinbaseProAccountService.java, xchange-coindeal/src/main/java/org/knowm/xchange/coindeal/service/CoindealTradeService.java, xchange-coinsuper/src/main/java/org/knowm/xchange/coinsuper/service/CoinsuperTradeService.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/TradeService.java, xchange-examples/src/main/java/org/knowm/xchange/examples/binance/trade/BinanceTradeDemo.java, xchange-ftx/src/main/java/org/knowm/xchange/ftx/service/FtxTradeService.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/GeminiAuthenticated.java, xchange-gemini/src/main/java/org/knowm/xchange/gemini/v1/service/GeminiTradeServiceRaw.java, xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinFuturesTradeService.java, xchange-poloniex/src/main/java/org/knowm/xchange/poloniex/service/PoloniexTradeService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceFutureStreamingExchange.java, xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceLiveFutureSubscriptionExample.java
Just ran the code formatting plugin.
=> Code formatting

xchange-ftx/src/main/java/org/knowm/xchange/ftx/FtxAdapters.java
I think that amount step size should be a size increment instead of the price increment.
=> Fix ftx amount step size

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAdapters.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateTransferHistoryEntry.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountServiceRaw.java
- CoinmateExchange - added addresses  ( Coinmate call them destination ) data to FundingRecord.
- BugFix in class CoinmateTransferHistoryEntry ( replaced "id" by transactionId") in jsonProperty
=> Bugfix/etd 225 connectors coinmate api deposit 

xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingExchange.java, xchange-stream-bitstamp/src/main/java/info/bitrich/xchangestream/bitstamp/v2/BitstampStreamingExchange.java, xchange-stream-btcmarkets/src/main/java/info/bitrich/xchangestream/btcmarkets/BTCMarketsStreamingExchange.java, xchange-stream-cexio/src/main/java/info/bitrich/xchangestream/cexio/CexioStreamingExchange.java, xchange-stream-coincheck/src/main/java/info/bitrich/xchangestream/coincheck/CoincheckStreamingExchange.java, xchange-stream-coinjar/src/main/java/info/bitrich/xchangestream/coinjar/CoinjarStreamingExchange.java, xchange-stream-coinmate/src/main/java/info/bitrich/xchangestream/coinmate/v2/CoinmateStreamingExchange.java, xchange-stream-dydx/src/main/java/info/bitrich/xchangestream/dydx/dydxStreamingExchange.java, xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingExchange.java, xchange-stream-gateio/src/main/java/GateioStreamingExchange.java, xchange-stream-hitbtc/src/main/java/info/bitrich/xchangestream/hitbtc/HitbtcStreamingExchange.java, xchange-stream-huobi/src/main/java/info/bitrich/xchangestream/huobi/HuobiStreamingExchange.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingExchange.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoStreamingExchange.java, xchange-stream-okcoin/src/main/java/info/bitrich/xchangestream/okcoin/OkCoinStreamingExchange.java, xchange-stream-serum/src/main/java/info/bitrich/xchangestream/serum/SerumStreamingExchange.java
applyStreamingSpecification method should be a must for all streaming exchanges
=> apply streaming specification for all streaming exchanges

xchange-stream-bitmex/src/main/java/info/bitrich/xchangestream/bitmex/dto/BitmexWebSocketTransaction.java, xchange-stream-cexio/src/main/java/info/bitrich/xchangestream/cexio/CexioStreamingMarketDataService.java, xchange-stream-cexio/src/main/java/info/bitrich/xchangestream/cexio/CexioStreamingRawService.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java, xchange-stream-dydx/src/main/java/info/bitrich/xchangestream/dydx/dydxStreamingService.java, xchange-stream-ftx/src/main/java/info/bitrich/xchangestream/ftx/FtxStreamingAdapters.java, xchange-stream-gateio/src/main/java/GateioStreamingService.java, xchange-stream-gemini-v2/src/main/java/info/bitrich/xchangestream/gemini/GeminiStreamingService.java, xchange-stream-hitbtc/src/main/java/info/bitrich/xchangestream/hitbtc/HitbtcStreamingMarketDataService.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoLevel2BatchSubscription.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoStreamingAccountService.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoStreamingTradeService.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoTradeBatchSubscription.java, xchange-stream-lgo/src/main/java/info/bitrich/xchangestream/lgo/LgoUserBatchSubscription.java, xchange-stream-poloniex2/src/main/java/info/bitrich/xchangestream/poloniex2/PoloniexStreamingMarketDataService.java
replace mapper.readValue(json.toString(), CLASS.class) with mapper.treeToValue(json, CLASS.class) to avoid extra JSON parsing
=> Optimize JSON mapping when possible

xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingExchange.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/CoinbaseProStreamingService.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/dto/CoinbaseProOrderBookMode.java, xchange-stream-coinbasepro/src/main/java/info/bitrich/xchangestream/coinbasepro/dto/CoinbaseProWebSocketSubscriptionMessage.java, xchange-stream-coinbasepro/src/test/java/info/bitrich/xchangestream/coinbasepro/dto/CoinbaseProWebSocketSubscriptionMessageTest.java
Support Coinbase order book batch subscription mode
This mode can be enabled by
exchangeSpecification.setExchangeSpecificParametersItem("OrderBook_Mode", "Batch");
=> Coinbase: order book "batch" subscription mode

xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingAdapters.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingExchange.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingMarketDataService.java
Exchange's "ticker" feed doesn't provide last quote data (ask/bid)
=> Kraken: optionally subscribe to "spread" feed to get ticker updates

xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingExchange.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingMarketDataService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceSubscriptionType.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/KlineSubscription.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/dto/KlineBinanceWebSocketTransaction.java, xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceKlineExample.java, xchange-stream-binance/src/test/java/info/bitrich/xchangestream/binance/dto/KlineBinanceWebSocketTransactionTest.java, xchange-stream-binance/src/test/resources/info/bitrich/xchangestream/binance/dto/testKlineEvent.json
=> BinanceKline

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/marketdata/KlineInterval.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataService.java
feat: implement getCandleStickData
=> feat: implement getCandleStickData

xchange-bybit/src/main/java/org/knowm/xchange/bybit/Bybit.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/BybitExchange.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/BybitResult.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/account/BybitBalance.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/account/BybitBalances.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/marketdata/BybitSymbol.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/marketdata/BybitTicker.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/trade/BybitOrderDetails.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/dto/trade/BybitOrderRequest.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/mappers/MarketDataMapper.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitBaseService.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitJacksonObjectMapperFactory.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitMarketDataService.java, xchange-bybit/src/main/java/org/knowm/xchange/bybit/service/BybitMarketDataServiceRaw.java, xchange-bybit/src/main/resources/bybit.json, xchange-bybit/src/test/java/org/knowm/xchange/bybit/BybitExchangeTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitAccountServiceRawTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitAccountServiceTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitMarketDataServiceRawTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitMarketDataServiceTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitTradeServiceRawTest.java, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BybitTradeServiceTest.java, xchange-bybit/src/test/resources/getSymbols.json5, xchange-bybit/src/test/resources/getTicker.json5, xchange-core/src/main/java/org/knowm/xchange/utils/DateUtils.java, xchange-core/src/main/java/org/knowm/xchange/utils/jackson/UnixTimestampNanoSecondsDeserializer.java
- Refactored dto
- Added time_now field to responses payload
- Added getting of ticker
- Added loading of currency pairs metadata
=> [bybit] extend functionality

xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingExchange.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/KrakenStreamingService.java, xchange-stream-kraken/src/main/java/info/bitrich/xchangestream/kraken/dto/KrakenSubscriptionStatusMessage.java
fix + subscription to subscription status
=> Kraken: subscription to system status + subscription to subscription status

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/dto/response/SymbolResponse.java
Currently Kucoin symbols are missing minFunds value
=> Kucoin symbol - add min funds

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAuthenticated.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateUtils.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/CoinmateTradingFeesResponse.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/CoinmateTradingFeesResponseData.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountServiceRaw.java, xchange-coinmate/src/test/java/org/knowm/xchange/coinmate/service/AccountInfoFetchIntegration.java
Add implementation of getDynamicTradingFeesByInstrument for Coinmate
=> [coinmate] implement getDynamicTradingFeesByInstrument

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAdapters.java
When the totalPositionInUsd is ZERO then currentLeverage = ZERO
=> [binance] Fix a bug

xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/marketdata/KrakenPublicTrade.java, xchange-kraken/src/main/java/org/knowm/xchange/kraken/dto/marketdata/KrakenPublicTrades.java
add in KrakenPublicTrade and KrakenPublicTrades the node tradeId. now it is possible to get the trade_id as well which kraken provided
=> add tradeId functionality to get trade_id from MarketDataTrade as well

xchange-stream-okex/src/main/java/info/bitrich/xchangestream/okex/OkexStreamingMarketDataService.java
added a getOrderBookUpdates subscription so that you can receive updates to the orderbook, and not the entire orderbook.
For example, for data recording and subsequent analysis.
=> [Okx] implement getOrderBookUpdates

xchange-krakenfutures/src/main/java/org/knowm/xchange/krakenfutures/KrakenFuturesAdapters.java
=> [kraken-futures] Fix adaptInstrument issue when the first pair is stablecoin

xchange-bitstamp/pom.xml, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/BitstampV2.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/marketdata/BitstampPairInfo.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/marketdata/BitstampTicker.java, xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampMarketDataServiceRaw.java
- Added lombok to bitstamp module
- Added endpoint for getting all tickers
=> Bitstamp update

pom.xml, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java, xchange-stream-kucoin/pom.xml, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingAdapters.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingExchange.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingMarketDataService.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingService.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/KucoinStreamingTradeService.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinOrderBookChanges.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinOrderBookEvent.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinOrderBookEventData.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinOrderEventData.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinTickerConverter.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinTickerEvent.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinWebSocketEvent.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinWebSocketOrderEvent.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinWebSocketSubscribeMessage.java, xchange-stream-kucoin/src/main/java/info/bitrich/xchangestream/kucoin/dto/KucoinWebSocketUnsubscribeMessage.java
Implemented streaming market data and trading services
=> Kucoin streaming exchange implementation

xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/OrderType.java
If there's interest, I can create a PR with the support for placing such orders.
=> Add TRAILING_STOP_MARKET order type (Binance futures)

pom.xml, xchange-binance/pom.xml, xchange-binance/src/test/java/org/knowm/xchange/binance/AbstractResilienceTest.java, xchange-binance/src/test/java/org/knowm/xchange/binance/BinanceExchangeIntegration.java, xchange-binance/src/test/java/org/knowm/xchange/binance/service/account/AccountServiceTest.java, xchange-bittrex/pom.xml, xchange-bittrex/src/test/java/org/knowm/xchange/bittrex/service/BaseWiremockTest.java, xchange-blockchain/pom.xml, xchange-blockchain/src/test/java/org/knowm/xchange/blockchain/service/BlockchainBaseTest.java, xchange-bybit/pom.xml, xchange-bybit/src/test/java/org/knowm/xchange/bybit/service/BaseWiremockTest.java, xchange-coinbasepro/pom.xml, xchange-coinbasepro/src/test/java/org/knowm/xchange/coinbasepro/service/BaseWiremockTest.java, xchange-gateio/pom.xml, xchange-gemini/pom.xml, xchange-gemini/src/test/java/org/knowm/xchange/gemini/v1/service/BaseWiremockTest.java, xchange-kraken/pom.xml, xchange-kraken/src/test/java/org/knowm/xchange/kraken/service/BaseWiremockTest.java, xchange-krakenfutures/src/test/java/org/knowm/xchange/krakenfutures/KrakenFuturesPublicDataTest.java, xchange-livecoin/pom.xml, xchange-livecoin/src/test/java/org/knowm/xchange/livecoin/service/BaseMockedIntegrationTest.java, xchange-mexc/pom.xml, xchange-mexc/src/test/java/org/knowm/xchange/mexc/service/BaseWiremockTest.java, xchange-stream-krakenfutures/src/test/java/info/bitrich/xchangestream/krakenfutures/KrakenFuturesStreamingPublicDataTest.java
- Upgraded wiremock to latest version
- Changed wiremock rule to start on random port
- Disabled failing kraken tests (unrelated to the wiremock changes)
=> [general] Wiremock upgrade

xchange-bybit/src/main/java/org/knowm/xchange/bybit/BybitAdapters.java, xchange-deribit/src/main/java/org/knowm/xchange/deribit/v2/DeribitAdapters.java
#4828 
also find and fix similar error in DeribitAdapters
=> [bybit] [deribit] fix date parse locale

xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/CoinmateAuthenticated.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/AmountType.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/TransferHistoryOrder.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/UnconfirmedDeposits.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/account/UnconfirmedDepositsResponse.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/dto/trade/CoinmateTransferHistoryEntry.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountService.java, xchange-coinmate/src/main/java/org/knowm/xchange/coinmate/service/CoinmateAccountServiceRaw.java, xchange-coinmate/src/main/resources/coinmate.json
* Remove DASH currency
* update JSON config
* add new API call for generic crypto withdrawal/deposit
* add new API call for unconfirmed deposits
* introduce enum for AmountType and TransferHistoryOrder
* add txid field for TransferHistoryOrder
* add methods for XRP destination tag
=> Coinmate update withdrawals and deposits

xchange-stream-gateio/src/main/java/info/bitrich/xchangestream/gateio/GateioStreamingAdapters.java, xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingMarketDataServiceIntegration.java
- Fixed getting bids in orderbook
- Added regression test for that
=> [gateio-stream] Fix getting of orderbook

xchange-binance/src/test/java/org/knowm/xchange/binance/BinanceAdaptersTest.java, xchange-binance/src/test/java/org/knowm/xchange/binance/ExchangeMetaDataIntegration.java, xchange-binance/src/test/java/org/knowm/xchange/binance/us/ExchangeMetaDataIntegration.java
- Fixed failing integration tests
- Replaced calls to deprecated code
=> [binance] Test fixes

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceFutures.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceMarketDataServiceRaw.java, xchange-examples/src/main/java/org/knowm/xchange/examples/binance/marketdata/BinanceMarketDataDemo.java
=> [binance] get tickers fix

xchange-okex/src/main/java/org/knowm/xchange/okex/dto/trade/OkexCancelOrderRequest.java, xchange-okex/src/main/java/org/knowm/xchange/okex/dto/trade/OkexOrderRequest.java
Fixes https://github.com/knowm/XChange/issues/4932
=> [okx] Fix wrong field name

xchange-gateio-v4/src/test/java/org/knowm/xchange/gateio/service/GateioMarketDataServiceIntegration.java, xchange-gateio-v4/src/test/resources/rest/spot.http
- Added integration test
- Added http requests
=> [gateio-v4] Minor improvements

xchange-stream-gateio/.gitignore, xchange-stream-gateio/README.md, xchange-stream-gateio/example.integration-test.env.properties, xchange-stream-gateio/pom.xml, xchange-stream-gateio/src/main/java/info/bitrich/xchangestream/gateio/GateioStreamingService.java, xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingAccountServiceIntegration.java, xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingExchangeIT.java, xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingMarketDataServiceIntegration.java, xchange-stream-gateio/src/test/java/info/bitrich/xchangestream/gateio/GateioStreamingTradeServiceIntegration.java
Fixes https://github.com/knowm/XChange/issues/4958
- Fixed wrong channel id
- Added configs for authenticated integration tests
- Extended integration tests
=> [gateio] Streaming fixes

xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceStreamingMarketDataService.java, xchange-stream-binance/src/main/java/info/bitrich/xchangestream/binance/BinanceSubscriptionType.java
Offical API document:
https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#all-market-rolling-window-statistics-streams
https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#individual-symbol-rolling-window-statistics-streams
=> [Binance] Support rolling window

xchange-coinex/src/main/java/org/knowm/xchange/coinex/Coinex.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/Config.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/dto/marketdata/CoinexMaintainInfo.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexMarketDataService.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexMarketDataServiceRaw.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexTradeService.java, xchange-coinex/src/test/java/org/knowm/xchange/coinex/service/CoinexMarketDataServiceIntegration.java, xchange-coinex/src/test/resources/rest/common.http
- Implemented getting of exchange health
- Fixed typo
=> [coinex] Add exchange health

xchange-coinex/pom.xml, xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexAdapters.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/CoinexAuthenticated.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/config/converter/OrderTypeToStringConverter.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/dto/trade/CoinexCancelOrderRequest.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexTradeService.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/CoinexTradeServiceRaw.java, xchange-coinex/src/main/java/org/knowm/xchange/coinex/service/params/CoinexOpenOrdersParams.java, xchange-coinex/src/test/java/org/knowm/xchange/coinex/CoinexExchangeWiremock.java, xchange-coinex/src/test/java/org/knowm/xchange/coinex/service/CoinexTradeServiceTest.java, xchange-coinex/src/test/resources/__files/v2_spot_cancel-order.json, xchange-coinex/src/test/resources/__files/v2_spot_market.json, xchange-coinex/src/test/resources/__files/v2_spot_pending-order_all-open-orders.json, xchange-coinex/src/test/resources/__files/v2_spot_pending-order_filtered-open-orders.json, xchange-coinex/src/test/resources/mappings/v2_spot_cancel-order.json, xchange-coinex/src/test/resources/mappings/v2_spot_market.json, xchange-coinex/src/test/resources/mappings/v2_spot_pending-order_all-open-orders.json, xchange-coinex/src/test/resources/mappings/v2_spot_pending-order_filtered-open-orders.json, xchange-coinex/src/test/resources/rest/spot.v2.http
- Implemented getting of open orders
- Implemented order cancelling
- Added wiremock tests
=> [coinex] Extend functionality

xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinAdapters.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinMarketDataService.java, xchange-kucoin/src/main/java/org/knowm/xchange/kucoin/KucoinMarketDataServiceRaw.java
Changed `CurrencyPair` parameter to `Instrument` for getting of orderbook
=> [kucoin] Implement orderbook for Instrument

xchange-binance/src/main/java/org/knowm/xchange/binance/BinanceAuthenticated.java, xchange-binance/src/main/java/org/knowm/xchange/binance/dto/trade/TimeInForce.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountService.java, xchange-binance/src/main/java/org/knowm/xchange/binance/service/BinanceAccountServiceRaw.java, xchange-core/src/main/java/org/knowm/xchange/service/trade/params/NetworkWithdrawFundsParams.java
* Adds support to set which network to withdraw to
* Allows requesting deposit addresses for specific network
* Fixes deserialization issue with Jackson 2.15.x
=> [binance] add support for network specific withdrawals and deposit addresses
